import {
  AlertTriangle, Bot, Check, CheckCircle2, ChevronRight, Download, FileCheck2, Fingerprint,
  FolderPlus, GitBranch, KeyRound, Link2, LoaderCircle, LockKeyhole, Play, RefreshCw,
  Shield, ShieldCheck, ShieldOff, UserRound, X
} from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type {
  AuthorityApprovalState, ContextBrokerState, EvidenceExplorerState, FinalAcceptanceAttackId,
  GoalWorkGraphState, OrganizationAuthorityState, ProjectDeliveryState, SecurityValidationState
} from '@h2a/contracts';
import { defaultEvidenceQuery } from '@h2a/contracts';
import { purposeActor, timeRemaining } from './workspaceModel';

type ProofRequest = (purpose: string, humanId?: string) => void;

export function WorkspaceAuthoritySummary({ state, onProof }: { state: OrganizationAuthorityState; onProof: ProofRequest }): React.JSX.Element {
  const now = Date.now();
  const active = state.memberships.filter((item) => item.status === 'active');
  return <section className="ws-native-panel"><div className="ws-native-hero"><ShieldCheck size={25} /><div><h3>People remain accountable for every agent</h3><p>Directory access, authority roles, and fresh Human Proof are separate controls. Nothing here grants authority by visibility alone.</p></div></div><div className="ws-native-metrics"><span><strong>{active.length}</strong> active people</span><span><strong>{state.roles.filter((item) => item.status === 'active').length}</strong> roles</span><span><strong>{state.credentials.filter((item) => item.status === 'active' && Date.parse(item.expires_at) > now).length}</strong> current credentials</span></div><div className="ws-native-list">{active.map((member) => { const credentials = state.credentials.filter((item) => item.membership_id === member.membership_id); const assurance = state.assurance.find((item) => item.membership_id === member.membership_id && Date.parse(item.expires_at) > now); const name = authorityName(state, member.human_id); return <article key={member.membership_id}><UserRound size={20} /><div><h3>{name}</h3><p>{member.department} · {credentials.length} authority credentials</p><small>{assurance ? `Human Proof ${timeRemaining(assurance.expires_at, now)}` : 'Fresh Human Proof required for protected actions'}</small></div>{!assurance && !name.startsWith('[DEMO]') && <button className="ws-secondary" onClick={() => onProof('administer organization authority', member.human_id)}><Fingerprint size={15} />Verify</button>}</article>; })}</div></section>;
}

export function WorkspacePlanSummary({ state, selectedGoalId, organization, onStateChange, onProof }: { state?: GoalWorkGraphState; selectedGoalId?: string; organization: OrganizationAuthorityState; onStateChange(state: GoalWorkGraphState): void; onProof: ProofRequest }): React.JSX.Element {
  const goal = state?.goals.find((item) => item.goal_id === selectedGoalId) ?? state?.goals[0];
  const graph = state?.graphs.find((item) => item.goal_id === goal?.goal_id);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function start(): Promise<void> {
    if (!window.h2a || !goal || !graph) return;
    const actor = purposeActor(organization, goal.created_by_human_id, 'approve collaborative work graph', Date.now());
    if (!actor) { onProof('approve collaborative work graph', goal.created_by_human_id); return; }
    setBusy(true); setError('');
    try { if (graph.status === 'draft') await window.h2a.approveWorkGraph({ graph_id: graph.graph_id, expected_revision: graph.revision, actor }); onStateChange(await window.h2a.runWorkGraph({ graph_id: graph.graph_id, actor })); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'The mission could not continue.'); }
    finally { setBusy(false); }
  }
  if (!goal || !graph) return <section className="ws-native-empty"><GitBranch size={27} /><h3>No work plan is selected</h3><p>Create a mission from Agent canvas. H2A will propose accountable agents, permissions, and dependencies before anything runs.</p></section>;
  return <section className="ws-native-panel"><div className="ws-native-hero"><GitBranch size={25} /><div><h3>{goal.title}</h3><p>One approval starts all independent work and continues dependency-ready assignments automatically.</p></div><span className={`ws-status ${graph.status}`}>{graph.status}</span></div>{error && <InlineError message={error} />}<div className="ws-plan-list">{graph.nodes.map((node, index) => <article key={node.node_id}><span className="ws-plan-order">{index + 1}</span><span className={`ws-provider-mark provider-${node.provider}`}><Bot size={18} /></span><div><h3>{node.title}</h3><p>{authorityName(organization, node.human_owner_id)} · {node.provider}</p><small>{node.allowed_tools.length} tools · {node.allowed_context_fields.length} shared fields · {node.withheld_context_fields.length} withheld</small></div><span className={`ws-status ${node.status}`}>{node.status}</span></article>)}</div><div className="ws-native-actions"><button className="ws-primary" disabled={busy || graph.status === 'completed'} onClick={() => void start()}>{busy ? <LoaderCircle className="ws-spin" size={16} /> : <Play size={16} />}{graph.status === 'draft' ? 'Approve & start' : 'Continue ready work'}</button></div></section>;
}

export function WorkspaceDecisionCenter({ state, organization, onStateChange, onProof }: { state: AuthorityApprovalState; organization: OrganizationAuthorityState; onStateChange(state: AuthorityApprovalState): void; onProof: ProofRequest }): React.JSX.Element {
  const now = Date.now();
  const requests = [...state.requests].sort((a, b) => Date.parse(b.requested_at) - Date.parse(a.requested_at));
  const [selectedId, setSelectedId] = useState(requests.find((item) => item.status === 'pending' && Date.parse(item.expires_at) > now)?.approval_request_id ?? requests[0]?.approval_request_id ?? '');
  const [approverHumanId, setApproverHumanId] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const pendingDecision = useRef<{ requestId: string; humanId: string; decision: 'approve' | 'reject'; purpose: string } | undefined>(undefined);
  const request = requests.find((item) => item.approval_request_id === selectedId);
  const context = state.request_contexts.find((item) => item.approval_request_id === selectedId);
  const policy = state.policies.find((item) => item.approval_policy_id === request?.approval_policy_id);
  const requesterMembership = organization.memberships.find((item) => item.membership_id === context?.requesting_membership_id);
  const approvers = organization.memberships.filter((item) => item.status === 'active' && item.membership_id !== context?.requesting_membership_id && !authorityName(organization, item.human_id).startsWith('[DEMO]'));
  useEffect(() => { if (!approvers.some((item) => item.human_id === approverHumanId)) setApproverHumanId(approvers[0]?.human_id ?? ''); }, [approverHumanId, approvers]);
  useEffect(() => { const pending = pendingDecision.current; if (!pending) return; const actor = purposeActor(organization, pending.humanId, pending.purpose, Date.now()); if (!actor) return; pendingDecision.current = undefined; void decide(pending.decision, actor); }, [organization]);
  async function decide(decision: 'approve' | 'reject', resolvedActor?: ReturnType<typeof purposeActor>): Promise<void> {
    if (!window.h2a || !request || !approverHumanId) return;
    const purpose = policy?.proof_purpose ?? 'approve protected action';
    const actor = resolvedActor ?? purposeActor(organization, approverHumanId, purpose, Date.now());
    if (!actor) { pendingDecision.current = { requestId: request.approval_request_id, humanId: approverHumanId, decision, purpose }; onProof(purpose, approverHumanId); return; }
    setBusy(true); setError('');
    try { onStateChange(await window.h2a.submitApprovalDecision({ approval_request_id: request.approval_request_id, approver: actor, decision, conditions: [] })); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'The decision could not be recorded.'); }
    finally { setBusy(false); }
  }
  async function resume(): Promise<void> { if (!window.h2a || !request || !context) return; setBusy(true); setError(''); try { onStateChange(await window.h2a.consumeApprovalResume({ approval_request_id: request.approval_request_id, idempotency_key: context.idempotency_key })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The protected action could not resume.'); } finally { setBusy(false); } }
  async function withdraw(): Promise<void> {
    if (!window.h2a || !requesterMembership || !request) return;
    const assurance = organization.assurance.find((item) => item.human_id === requesterMembership.human_id && item.purpose === 'withdraw protected approval request' && Date.parse(item.expires_at) > Date.now());
    if (!assurance) { onProof('withdraw protected approval request', requesterMembership.human_id); return; }
    setBusy(true); setError(''); try { onStateChange(await window.h2a.withdrawApprovalRequest({ approval_request_id: request.approval_request_id, requesting_human_id: requesterMembership.human_id, human_proof_id: assurance.human_proof_id })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The request could not be withdrawn.'); } finally { setBusy(false); }
  }
  return <section className="ws-native-panel"><div className="ws-native-hero"><Fingerprint size={25} /><div><h3>Human decisions</h3><p>Protected effects pause here. A different eligible person verifies the exact purpose, decides, and the effect resumes at most once.</p></div><span className="ws-status waiting">{requests.filter((item) => item.status === 'pending' && Date.parse(item.expires_at) > now).length} waiting</span></div>{error && <InlineError message={error} />}<div className="ws-decision-layout"><nav aria-label="Approval requests">{requests.map((item) => <button key={item.approval_request_id} className={item.approval_request_id === selectedId ? 'selected' : ''} onClick={() => setSelectedId(item.approval_request_id)}><span><strong>{item.required_action}</strong><small>{item.required_resource}</small></span><span className={`ws-status ${Date.parse(item.expires_at) <= now && item.status === 'pending' ? 'expired' : item.status}`}>{Date.parse(item.expires_at) <= now && item.status === 'pending' ? 'expired' : item.status}</span></button>)}</nav>{request ? <article className="ws-decision-detail"><h3>{request.required_action}</h3><p>{request.required_resource}</p><dl><Fact label="Requester" value={requesterMembership ? authorityName(organization, requesterMembership.human_id) : context?.requesting_membership_id} /><Fact label="Effect hash" value={request.requested_effect_hash} /><Fact label="Expires" value={timeRemaining(request.expires_at, now)} /><Fact label="Policy" value={request.approval_policy_id} /></dl>{request.status === 'pending' && Date.parse(request.expires_at) > now && <><label>Eligible approver<select value={approverHumanId} onChange={(event) => setApproverHumanId(event.target.value)}>{approvers.map((item) => <option value={item.human_id} key={item.membership_id}>{authorityName(organization, item.human_id)} · {item.department}</option>)}</select></label><div className="ws-native-actions"><button className="ws-secondary ws-stop" disabled={busy || !approverHumanId} onClick={() => void decide('reject')}><X size={15} />Reject</button><button className="ws-primary" disabled={busy || !approverHumanId} onClick={() => void decide('approve')}><Check size={15} />Verify & approve</button><button className="ws-secondary" disabled={busy} onClick={() => void withdraw()}><ShieldOff size={15} />Withdraw request</button></div></>}{request.status === 'approved' && <button className="ws-primary" disabled={busy || state.resumes.some((item) => item.approval_request_id === request.approval_request_id && item.status === 'completed')} onClick={() => void resume()}><Play size={15} />Resume exactly once</button>}</article> : <div className="ws-native-empty"><CheckCircle2 size={25} /><h3>No decisions yet</h3></div>}</div></section>;
}

export function WorkspaceSharingCenter({ state, organization, onStateChange, onProof }: { state: ContextBrokerState; organization: OrganizationAuthorityState; onStateChange(state: ContextBrokerState): void; onProof: ProofRequest }): React.JSX.Element {
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  async function revoke(grantId: string): Promise<void> { if (!window.h2a) return; const admin = organization.memberships.find((item) => item.status === 'active' && !authorityName(organization, item.human_id).startsWith('[DEMO]')); if (!admin) return; const actor = purposeActor(organization, admin.human_id, 'administer protected context', Date.now()); if (!actor) { onProof('administer protected context', admin.human_id); return; } setBusy(grantId); setError(''); try { onStateChange(await window.h2a.updateContextGrant({ actor, context_grant_id: grantId, action: 'revoke' })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The grant could not be revoked.'); } finally { setBusy(''); } }
  return <section className="ws-native-panel"><div className="ws-native-hero"><LockKeyhole size={25} /><div><h3>Least-context sharing</h3><p>Each agent receives an explicit projection. Fields outside that projection remain withheld, even when another agent saw them earlier.</p></div></div>{error && <InlineError message={error} />}<div className="ws-sharing-grid">{state.grants.map((item) => <article key={item.grant.context_grant_id}><header><KeyRound size={18} /><div><h3>{item.grant.recipient_agent_id}</h3><p>{item.status} · {item.grant.task_id}</p></div><span className={`ws-status ${item.status}`}>{item.status}</span></header><div><strong>Released</strong><p>{item.field_rules.map((rule) => `${rule.field} (${rule.transformation})`).join(', ') || 'No protected fields'}</p></div><div className="withheld"><strong>Kept back</strong><p>{item.grant.withheld_field_hashes.length ? `${item.grant.withheld_field_hashes.length} protected values retained as hashes` : 'All fields outside this explicit grant'}</p></div><small>{item.maximum_uses - item.use_count} uses left · {timeRemaining(item.grant.expires_at, Date.now())}</small>{item.status === 'active' && <button className="ws-secondary ws-stop" disabled={busy === item.grant.context_grant_id} onClick={() => void revoke(item.grant.context_grant_id)}><ShieldOff size={15} />Revoke</button>}</article>)}</div>{state.grants.length === 0 && <div className="ws-native-empty"><LockKeyhole size={25} /><h3>No active sharing grants</h3><p>H2A issues exact grants when a governed mission is approved.</p></div>}</section>;
}

const attackNames: Record<FinalAcceptanceAttackId, string> = { replay: 'Replay request', 'forged-approval': 'Forged approval', 'over-broad-delegation': 'Over-broad delegation', 'context-leakage': 'Context leakage', tamper: 'Federation tamper', 'provider-failure': 'Provider failure' };
export function WorkspaceSecurityCenter({ onRefresh }: { onRefresh(): Promise<void> }): React.JSX.Element {
  const [state, setState] = useState<SecurityValidationState>(); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  async function refresh(): Promise<void> { if (window.h2a) setState(await window.h2a.getSecurityValidationState()); }
  useEffect(() => { void refresh(); }, []);
  async function attack(id: FinalAcceptanceAttackId): Promise<void> { if (!window.h2a) return; setBusy(id); setError(''); try { setState(await window.h2a.runSecurityAttack({ attack_id: id })); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The challenge could not run.'); await refresh(); } finally { setBusy(''); } }
  async function contain(id: 'operator-cancel' | 'authority-revocation' | 'restart-recovery'): Promise<void> { if (!window.h2a) return; setBusy(id); setError(''); try { setState(await window.h2a.runContainmentControl({ control_id: id })); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The containment proof could not run.'); await refresh(); } finally { setBusy(''); } }
  if (!state) return <div className="ws-native-empty"><LoaderCircle className="ws-spin" /><h3>Loading security controls</h3></div>;
  return <section className="ws-native-panel"><div className="ws-native-hero"><Shield size={25} /><div><h3>Security controls</h3><p>These challenges cross the real policy boundary. A green result requires a persisted denial or containment receipt.</p></div><span className={`ws-status ${state.status}`}>{state.attacks.filter((item) => item.status === 'blocked').length}/6 blocked</span></div>{error && <InlineError message={error} />}<div className="ws-security-control-grid">{state.attacks.map((item) => <article key={item.control_id}>{item.status === 'blocked' ? <CheckCircle2 size={20} /> : <Shield size={20} />}<div><h3>{attackNames[item.control_id]}</h3><p>{item.reason_code ?? 'Ready for challenge'}</p><small>{item.evidence_ref ?? 'No receipt yet'}</small></div><button className="ws-secondary" disabled={!!busy || state.evidence_integrity === 'failed'} onClick={() => void attack(item.control_id)}>{busy === item.control_id ? <LoaderCircle className="ws-spin" size={15} /> : <Play size={15} />}{item.status === 'blocked' ? 'Run again' : 'Run'}</button></article>)}</div><div className="ws-section-heading ws-subheading"><h2>Containment</h2><button className="ws-icon" aria-label="Refresh security controls" title="Refresh" onClick={() => void refresh()}><RefreshCw size={17} /></button></div><div className="ws-containment-list">{state.containment.map((item) => <article key={item.control_id}>{item.status === 'passed' ? <CheckCircle2 size={19} /> : <AlertTriangle size={19} />}<div><h3>{item.control_id.replaceAll('-', ' ')}</h3><p>{item.reason_code ?? item.status}</p></div><span className={`ws-status ${item.status}`}>{item.status}</span><button className="ws-secondary" disabled={!!busy || item.status === 'armed'} onClick={() => void contain(item.control_id)}>{item.control_id === 'restart-recovery' ? 'Arm restart' : 'Run'}</button></article>)}</div></section>;
}

export function WorkspaceReceipts({ state, initialSearch, onStateChange }: { state: EvidenceExplorerState; initialSearch?: string; onStateChange(state: EvidenceExplorerState): void }): React.JSX.Element {
  const [search, setSearch] = useState(initialSearch ?? ''); const [selectedId, setSelectedId] = useState(state.events[0]?.event.event_id ?? ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [receipt, setReceipt] = useState('');
  useEffect(() => { if (initialSearch) { setSearch(initialSearch); void query(initialSearch); } }, [initialSearch]);
  useEffect(() => { if (!state.events.some((item) => item.event.event_id === selectedId)) setSelectedId(state.events[0]?.event.event_id ?? ''); }, [selectedId, state.events]);
  const selected = state.events.find((item) => item.event.event_id === selectedId);
  async function query(value = search): Promise<void> { if (!window.h2a) return; setBusy(true); setError(''); try { onStateChange(await window.h2a.getEvidenceExplorerState({ ...defaultEvidenceQuery, search: value })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Evidence could not be searched.'); } finally { setBusy(false); } }
  async function exportEvidence(): Promise<void> { if (!window.h2a) return; setBusy(true); setError(''); try { const result = await window.h2a.exportEvidenceBundle({ query: { ...defaultEvidenceQuery, search } }); setReceipt(`${result.relativePath} · ${result.bundleHash}`); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Evidence could not be exported.'); } finally { setBusy(false); } }
  const chain = selected?.identityChain;
  return <section className="ws-native-panel"><div className="ws-native-hero"><FileCheck2 size={25} /><div><h3>Work receipts</h3><p>Reconstruct one trace from its person and Human Proof through the agent, runtime, mandate, decision, and output.</p></div><span className={`ws-status ${state.integrity.status}`}>{state.integrity.status}</span></div>{error && <InlineError message={error} />}{receipt && <div className="ws-native-success"><CheckCircle2 size={17} />{receipt}</div>}<form className="ws-receipt-search" onSubmit={(event) => { event.preventDefault(); void query(); }}><input aria-label="Search work receipts" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search trace, person, agent, mandate, or reason" /><button className="ws-primary" disabled={busy}>Search</button><button type="button" className="ws-secondary" disabled={busy} onClick={() => void exportEvidence()}><Download size={15} />Export</button></form><div className="ws-receipt-layout"><nav>{state.events.map((item) => <button key={item.event.event_id} className={item.event.event_id === selectedId ? 'selected' : ''} onClick={() => setSelectedId(item.event.event_id)}><span><strong>{item.event.event_type.replaceAll('_', ' ').toLowerCase()}</strong><small>{item.event.actor.type} · {item.event.actor.id}</small></span><time>{new Date(item.event.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></button>)}</nav>{selected ? <article><h3>Authority chain</h3><div className="ws-chain"><Chain icon={UserRound} label="Human" value={chain?.humanDisplayName ?? chain?.humanId} /><Chain icon={Fingerprint} label="Human Proof" value={chain?.humanProofId} /><Chain icon={Bot} label="Agent Passport" value={chain?.agentName ?? chain?.passportId} /><Chain icon={Link2} label="Runtime" value={chain?.runtimeId} /><Chain icon={ShieldCheck} label="Mandate" value={chain?.mandateId} /></div><dl><Fact label="Trace" value={selected.event.trace_id} /><Fact label="Event hash" value={selected.event.event_hash} /><Fact label="Previous hash" value={selected.event.previous_hash ?? 'Genesis'} /><Fact label="Resolution" value={selected.resolutionStatus} /><Fact label="Reason" value={selected.decision?.reasonCode} /></dl></article> : <div className="ws-native-empty"><FileCheck2 size={25} /><h3>No matching receipts</h3></div>}</div></section>;
}

export function WorkspaceProjectConnector({ state, onStateChange }: { state: ProjectDeliveryState; onStateChange(state: ProjectDeliveryState): void }): React.JSX.Element {
  const [name, setName] = useState(''); const [path, setPath] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(): Promise<void> { if (!window.h2a) return; setBusy(true); setError(''); try { onStateChange(await window.h2a.registerProject({ display_name: name.trim(), root_path: path.trim(), protected_paths: ['.git/**', '.env*', '**/secrets/**'], allowed_commands: [], network_hosts: [] })); setName(''); setPath(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The workspace could not be connected.'); } finally { setBusy(false); } }
  return <section className="ws-native-panel"><div className="ws-native-hero"><FolderPlus size={25} /><div><h3>Connect a project workspace</h3><p>H2A inspects the real local path and keeps agents inside assignment-owned boundaries. Connecting does not grant write authority.</p></div></div>{error && <InlineError message={error} />}<form className="ws-project-form" onSubmit={(event) => { event.preventDefault(); void submit(); }}><label>Project name<input value={name} onChange={(event) => setName(event.target.value)} required maxLength={120} placeholder="Website delivery" /></label><label>Local project path<input value={path} onChange={(event) => setPath(event.target.value)} required maxLength={1000} placeholder="C:\Projects\website" /></label><button className="ws-primary" disabled={busy || !name.trim() || !path.trim()}>{busy ? <LoaderCircle className="ws-spin" size={16} /> : <FolderPlus size={16} />}Connect workspace</button></form><div className="ws-native-list">{state.projects.map((project) => <article key={project.project_id}><GitBranch size={20} /><div><h3>{project.display_name}</h3><p>{project.canonical_root}</p><small>{project.repository_mode} · {state.assignments.filter((item) => item.project_id === project.project_id).length} assignments</small></div><span className="ws-status ready">connected</span></article>)}</div></section>;
}

function Chain({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value?: string }): React.JSX.Element { return <div className={value ? '' : 'missing'}><span><Icon size={16} /></span><div><small>{label}</small><strong>{value ?? 'Not linked'}</strong></div><ChevronRight size={14} /></div>; }
function Fact({ label, value }: { label: string; value?: string }): React.JSX.Element { return <div><dt>{label}</dt><dd>{value ?? 'Not linked'}</dd></div>; }
function InlineError({ message }: { message: string }): React.JSX.Element { return <div className="ws-blocker-message" role="alert"><AlertTriangle size={18} /><div><strong>This step needs attention</strong><p>{message}</p></div></div>; }
function authorityName(state: OrganizationAuthorityState, humanId: string): string { return state.memberships.find((item) => item.human_id === humanId)?.employee_id ?? humanId; }
