import { useState } from 'react';
import {
  Bot, BrainCircuit, Check, CheckCircle2, ChevronRight, CircleHelp,
  Download, FileCheck2, FileText, KeyRound, LockKeyhole, Network, Search,
  ShieldCheck, UserRound, Users, X, MessageSquareText
} from 'lucide-react';
import { providerCatalog, type Agent, type MemoryRecord, type Page, type Person, type Review, type SharedContext, type Workspace, type WorkspaceTab, type WorkStep } from './model';

export type DomainAction = 'organization' | 'help' | 'account' | 'notifications' | 'search' | 'invite' | 'notes' | 'share' | 'workspace' | 'addStep' | 'connections' | 'policies' | 'integrations' | 'memoryAdd' | 'memoryPolicy' | 'memoryRecord' | 'deliverable' | 'step' | 'participant' | 'agentActivity' | 'export';

function Shell({ eyebrow, title, children, onClose, drawer = false, large = false }: { eyebrow: string; title: string; children: React.ReactNode; onClose: () => void; drawer?: boolean; large?: boolean }): React.JSX.Element {
  return <div className={`dialog-layer ${drawer ? 'drawer-layer' : ''}`} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className={`${drawer ? 'detail-drawer' : 'dialog'} ${large ? 'dialog-large' : ''}`} role="dialog" aria-modal="true" aria-label={title}><header className="dialog-header"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20} /></button></header>{children}</section></div>;
}

export function MissionDialog({ initial, workspaces, onClose, onCreate }: { initial?: string; workspaces: Workspace[]; onClose: () => void; onCreate: (title: string, workspaceId: string) => void }): React.JSX.Element {
  const [title, setTitle] = useState(initial || 'Launch a governed customer support assistant'); const [workspaceId, setWorkspaceId] = useState(workspaces[0]?.id ?? '');
  return <Shell eyebrow="New mission · 1 of 2" title="What should your agent team accomplish?" onClose={onClose}><div className="dialog-body"><label className="field-label" htmlFor="mission-title">Mission brief</label><textarea id="mission-title" rows={4} value={title} onChange={(event) => setTitle(event.target.value)} /><label className="field-label field-label-spaced" htmlFor="mission-workspace">Workspace</label><select id="mission-workspace" value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select><div className="dialog-preview"><BrainCircuit size={20} /><span><strong>H2A will propose the team and plan.</strong><small>You review scope once before agents begin.</small></span></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!title.trim() || !workspaceId} onClick={() => onCreate(title.trim(), workspaceId)}>Create and review plan</button></footer></Shell>;
}

export function ConnectAgentDialog({ onClose, onDone }: { onClose: () => void; onDone: (provider: string, name: string) => void }): React.JSX.Element {
  const [choice, setChoice] = useState('OpenAI Codex'); const [step, setStep] = useState(1); const [name, setName] = useState('My governed agent');
  return <Shell eyebrow={`Connect an agent · ${step} of 2`} title={step === 1 ? 'Choose an agent provider' : `Set up ${choice}`} onClose={onClose} large>{step === 1 ? <div className="dialog-body"><div className="provider-choice-grid">{providerCatalog.map((provider) => <button key={provider.name} className={choice === provider.name ? 'provider-choice selected' : 'provider-choice'} onClick={() => setChoice(provider.name)}><Bot size={20} /><span><strong>{provider.name}</strong><small>{provider.detail}</small></span>{choice === provider.name ? <Check size={18} /> : null}</button>)}</div></div> : <div className="dialog-body"><div className="connection-hero"><span className="agent-logo"><Bot size={24} /></span><div><strong>{choice}</strong><small>Owned by Varun Khatr · employee-bound connection</small></div><span className="status-pill ready"><span />Ready</span></div><label className="field-label field-label-spaced" htmlFor="agent-name">Agent display name</label><input className="text-input" id="agent-name" value={name} onChange={(event) => setName(event.target.value)} /><div className="access-preview"><div><Check size={16} /><span><strong>Employee binding</strong><small>Varun remains accountable for this connection</small></span></div><div><LockKeyhole size={16} /><span><strong>No ambient access</strong><small>Workspace scope is granted only when assigned</small></span></div><div><ShieldCheck size={16} /><span><strong>Provider authentication</strong><small>Sign-in and token exchange occur in this step when connected</small></span></div></div></div>}<footer className="dialog-footer"><button className="secondary-button" onClick={step === 1 ? onClose : () => setStep(1)}>{step === 1 ? 'Cancel' : 'Back'}</button><button className="primary-button" disabled={step === 2 && !name.trim()} onClick={step === 1 ? () => setStep(2) : () => onDone(choice, name.trim())}>{step === 1 ? 'Continue' : 'Connect agent'}</button></footer></Shell>;
}

export function ReviewDialog({ review, onClose, onDecision }: { review: Review; onClose: () => void; onDecision: (id: string, status: 'approved' | 'denied') => void }): React.JSX.Element {
  const [confirmed, setConfirmed] = useState(false);
  return <Shell eyebrow="Independent approval" title={review.title} onClose={onClose}><div className="dialog-body"><div className="verification-person"><span className="avatar" style={{ background: '#0f766e' }}>VK</span><span><strong>Varun Khatr</strong><small>Eligible approver · exact-purpose verification</small></span><ShieldCheck size={22} /></div><dl className="review-facts"><div><dt>Purpose</dt><dd>{review.purpose}</dd></div><div><dt>Exactly-once effect</dt><dd>{review.effect}</dd></div><div><dt>Requester</dt><dd>{review.requester}</dd></div></dl><label className="check-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>I reviewed the exact purpose and bounded effect.</span></label></div><footer className="dialog-footer spread"><button className="danger-button" onClick={() => onDecision(review.id, 'denied')}>Deny</button><div><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!confirmed} onClick={() => onDecision(review.id, 'approved')}>Approve once</button></div></footer></Shell>;
}

export function RepairDialog({ agent, onClose, onDone }: { agent?: Agent; onClose: () => void; onDone: () => void }): React.JSX.Element {
  return <Shell eyebrow="One required action" title={`Renew ${agent?.name ?? 'agent'} permission`} onClose={onClose}><div className="dialog-body"><div className="repair-summary"><ShieldCheck size={24} /><div><strong>Verify only the current assignment</strong><p>The renewed scope applies to this agent’s current work. Other agents and workspaces remain unchanged.</p></div></div><div className="scope-box"><span>Allowed</span><strong>{agent?.permissions.join(', ') || 'Approved assignment inputs'}</strong><span>Withheld</span><strong>Credentials, private notes, unrelated workspaces</strong></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={onClose}>Not now</button><button className="primary-button" onClick={onDone}>Verify and renew</button></footer></Shell>;
}

export function ProofDialog({ title, workspace, agents, onClose }: { title: string; workspace: Workspace; agents: Agent[]; onClose: () => void }): React.JSX.Element {
  const steps = workspace.steps.slice(0, 5);
  return <Shell eyebrow="Evidence trail" title={title} onClose={onClose} drawer><div className="drawer-body"><div className="evidence-summary"><ShieldCheck size={24} /><div><strong>Attributable chain</strong><small>Demo trace generated from the selected workspace state</small></div></div><div className="trace-list"><div className="trace-event"><span><UserRound size={16} /></span><div><small>Initiated by</small><strong>Varun Khatr</strong><code>human_varun · HP Enterprise</code></div></div>{steps.map((step, index) => { const agent = agents.find((item) => item.id === step.agentId); return <div className="trace-event" key={step.id}><span>{step.status === 'done' ? <Check size={16} /> : index + 2}</span><div><small>{step.status === 'done' ? 'Signed output' : 'Bound assignment'}</small><strong>{step.title}</strong><p>{agent?.name} · {step.context.length} released · {step.withheld.length} withheld</p><code>evt_{workspace.id}_{step.id.slice(0, 12)}</code></div></div>; })}</div><div className="truth-boundary"><LockKeyhole size={17} /><span><strong>Presentation evidence</strong><small>These records reflect the browser demo dataset, not backend cryptographic receipts.</small></span></div></div><footer className="dialog-footer"><button className="primary-button" onClick={onClose}>Close trail</button></footer></Shell>;
}

interface DomainProps {
  action: DomainAction; targetId?: string; selectedWorkspace: Workspace | null; workspaces: Workspace[];
  agents: Agent[]; people: Person[]; reviews: Review[]; memoryRecords: MemoryRecord[]; search: string;
  onSearch: (value: string) => void; onClose: () => void;
  onOpenWorkspace: (workspace: Workspace, tab?: WorkspaceTab) => void; onNavigate: (page: Page) => void;
  onInvite: (workspaceId: string, entityId: string, kind: 'person' | 'agent') => void;
  onAddNote: (workspaceId: string, body: string) => void; onShare: (workspaceId: string, item: SharedContext) => void;
  onAddStep: (workspaceId: string, step: WorkStep) => void; onAddMemory: (record: MemoryRecord) => void;
  notify: (message: string) => void;
}

export function DomainDialog(props: DomainProps): React.JSX.Element {
  const workspace = props.workspaces.find((item) => item.id === props.targetId) ?? props.selectedWorkspace ?? props.workspaces[0];
  if (props.action === 'search') return <SearchPanel {...props} />;
  if (props.action === 'invite') return <InvitePanel {...props} workspace={workspace} />;
  if (props.action === 'notes') return <NotesPanel {...props} workspace={workspace} />;
  if (props.action === 'share') return <SharePanel {...props} workspace={workspace} />;
  if (props.action === 'addStep') return <AddStepPanel {...props} workspace={workspace} />;
  if (props.action === 'memoryAdd') return <MemoryAddPanel {...props} />;
  if (props.action === 'participant') return <PersonPanel {...props} person={props.people.find((item) => item.id === props.targetId) ?? props.people[0]} />;
  if (props.action === 'agentActivity') return <AgentPanel {...props} agent={props.agents.find((item) => item.id === props.targetId) ?? props.agents[0]} />;
  if (props.action === 'memoryPolicy' || props.action === 'memoryRecord') return <MemoryPanel {...props} record={props.memoryRecords.find((item) => item.id === props.targetId) ?? props.memoryRecords[0]} policy={props.action === 'memoryPolicy'} />;
  if (props.action === 'step' || props.action === 'deliverable') return <StepPanel {...props} workspace={workspace} step={workspace.steps.find((item) => item.id === props.targetId) ?? workspace.steps[0]} />;
  if (props.action === 'export') return <ExportPanel {...props} />;
  return <ManagementPanel {...props} workspace={workspace} />;
}

function SearchPanel(props: DomainProps): React.JSX.Element {
  const query = props.search.toLowerCase();
  const results = [
    ...props.workspaces.map((item) => ({ id: item.id, title: item.name, meta: `Workspace · ${item.team}`, kind: 'workspace' })),
    ...props.people.map((item) => ({ id: item.id, title: item.name, meta: `Person · ${item.team}`, kind: 'person' })),
    ...props.agents.map((item) => ({ id: item.id, title: item.name, meta: `Agent · ${item.provider}`, kind: 'agent' })),
    ...props.memoryRecords.map((item) => ({ id: item.id, title: item.title, meta: `Memory · ${item.owner}`, kind: 'memory' }))
  ].filter((item) => !query || `${item.title} ${item.meta}`.toLowerCase().includes(query)).slice(0, 10);
  function open(result: typeof results[number]): void { props.onClose(); if (result.kind === 'workspace') props.onOpenWorkspace(props.workspaces.find((item) => item.id === result.id)!); else if (result.kind === 'person') setTimeout(() => props.onNavigate('people'), 0); else if (result.kind === 'agent') setTimeout(() => props.onNavigate('agents'), 0); else setTimeout(() => props.onNavigate('memory'), 0); }
  return <Shell eyebrow="Search" title="Find work, people, agents, and knowledge" onClose={props.onClose} large><div className="dialog-body"><label className="dialog-search"><Search size={18} /><input autoFocus value={props.search} onChange={(event) => props.onSearch(event.target.value)} placeholder="Search H2A" /></label><div className="search-results">{results.map((result) => <button key={`${result.kind}-${result.id}`} onClick={() => open(result)}><span className="result-icon">{result.kind === 'agent' ? <Bot /> : result.kind === 'person' ? <UserRound /> : result.kind === 'memory' ? <BrainCircuit /> : <FileText />}</span><span><strong>{result.title}</strong><small>{result.meta}</small></span><ChevronRight size={17} /></button>)}</div></div></Shell>;
}

function InvitePanel(props: DomainProps & { workspace: Workspace }): React.JSX.Element {
  const available = [...props.people.filter((person) => !props.workspace.memberIds.includes(person.id)).map((person) => ({ id: person.id, kind: 'person' as const, title: person.name, meta: `${person.role} · ${person.team}` })), ...props.agents.filter((agent) => !props.workspace.agentIds.includes(agent.id)).map((agent) => ({ id: agent.id, kind: 'agent' as const, title: agent.name, meta: `${agent.provider} · accountable to ${agent.owner}` }))];
  const [workspaceId, setWorkspaceId] = useState(props.workspace.id); const [selected, setSelected] = useState(available[0]);
  return <Shell eyebrow="Workspace membership" title="Add a person or agent" onClose={props.onClose} large><div className="dialog-body"><div className="form-grid"><label><span>Workspace</span><select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}>{props.workspaces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Access</span><select><option>Collaborator · mission context only</option><option>Viewer · no agent instructions</option></select></label></div><h3 className="dialog-section-title">Available in HP Enterprise</h3><div className="selectable-list">{available.map((item) => <button key={`${item.kind}-${item.id}`} className={selected?.id === item.id ? 'selected' : ''} onClick={() => setSelected(item)}><span className="result-icon">{item.kind === 'person' ? <UserRound /> : <Bot />}</span><span><strong>{item.title}</strong><small>{item.meta}</small></span>{selected?.id === item.id ? <Check size={17} /> : null}</button>)}</div><div className="truth-boundary"><ShieldCheck size={17} /><span><strong>Membership is durable</strong><small>Agents still receive only the context released for each assignment.</small></span></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={props.onClose}>Cancel</button><button className="primary-button" disabled={!selected} onClick={() => selected && props.onInvite(workspaceId, selected.id, selected.kind)}>Add to workspace</button></footer></Shell>;
}

function NotesPanel(props: DomainProps & { workspace: Workspace }): React.JSX.Element {
  const [body, setBody] = useState('Keep the CISO demo focused on governed collaboration and visible evidence.');
  return <Shell eyebrow="Live room" title="Mission notes" onClose={props.onClose} drawer><div className="drawer-body"><div className="note-thread">{props.workspace.notes?.map((note) => <article key={note.id}><span className="avatar" style={{ background: '#0f766e' }}>VK</span><div><strong>{note.author}</strong><small>{note.createdAt}</small><p>{note.body}</p></div></article>)}{!props.workspace.notes?.length ? <div className="empty-inline"><MessageSquareText /><strong>No shared notes yet</strong><span>Add the first direction for people in this room.</span></div> : null}</div><label className="field-label field-label-spaced" htmlFor="new-note">Add a note</label><textarea id="new-note" rows={5} value={body} onChange={(event) => setBody(event.target.value)} /><p className="field-help">People see the note. Agents receive it only when included in an assignment grant.</p></div><footer className="dialog-footer"><button className="secondary-button" onClick={props.onClose}>Cancel</button><button className="primary-button" disabled={!body.trim()} onClick={() => props.onAddNote(props.workspace.id, body.trim())}>Post note</button></footer></Shell>;
}

function SharePanel(props: DomainProps & { workspace: Workspace }): React.JSX.Element {
  const [name, setName] = useState('HP storefront brief.pdf'); const [audience, setAudience] = useState('Research Scout and Claude Design Partner');
  return <Shell eyebrow="Bounded context" title="Share context with this mission" onClose={props.onClose}><div className="dialog-body"><label className="field-label" htmlFor="context-name">File or knowledge item</label><input className="text-input" id="context-name" value={name} onChange={(event) => setName(event.target.value)} /><label className="field-label field-label-spaced" htmlFor="context-audience">Recipients</label><select id="context-audience" value={audience} onChange={(event) => setAudience(event.target.value)}><option>Research Scout and Claude Design Partner</option><option>All people in the room</option><option>Codex Builder and Antigravity QA</option></select><div className="context-preview"><div><Check /><span><strong>Released</strong><small>Document content, title, source</small></span></div><div><LockKeyhole /><span><strong>Withheld</strong><small>Credentials, personal data, unrelated files</small></span></div></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={props.onClose}>Cancel</button><button className="primary-button" disabled={!name.trim()} onClick={() => props.onShare(props.workspace.id, { id: `context-${Date.now()}`, name: name.trim(), audience, sharedBy: 'Varun Khatr', createdAt: 'Now' })}>Share approved context</button></footer></Shell>;
}

function AddStepPanel(props: DomainProps & { workspace: Workspace }): React.JSX.Element {
  const [title, setTitle] = useState('Prepare executive security summary'); const [agentId, setAgentId] = useState(props.workspace.agentIds[0] ?? props.agents[0]?.id); const [dependsOn, setDependsOn] = useState(props.workspace.steps.at(-1)?.id ?? '');
  return <Shell eyebrow="Plan editor" title="Add a mission step" onClose={props.onClose}><div className="dialog-body"><label className="field-label" htmlFor="step-title">Required outcome</label><input className="text-input" id="step-title" value={title} onChange={(event) => setTitle(event.target.value)} /><div className="form-grid field-label-spaced"><label><span>Eligible agent</span><select value={agentId} onChange={(event) => setAgentId(event.target.value)}>{props.agents.filter((agent) => agent.status !== 'offline').map((agent) => <option key={agent.id} value={agent.id}>{agent.name} · {agent.provider}</option>)}</select></label><label><span>Runs after</span><select value={dependsOn} onChange={(event) => setDependsOn(event.target.value)}><option value="">No dependency</option>{props.workspace.steps.map((step) => <option key={step.id} value={step.id}>{step.title}</option>)}</select></label></div><div className="assignment-preview"><Bot /><span><strong>{props.agents.find((agent) => agent.id === agentId)?.name}</strong><small>Receives mission brief and predecessor output · credentials withheld</small></span></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={props.onClose}>Cancel</button><button className="primary-button" disabled={!title.trim() || !agentId} onClick={() => props.onAddStep(props.workspace.id, { id: `step-${Date.now()}`, title: title.trim(), summary: 'New outcome added by Varun Khatr.', agentId, status: dependsOn && props.workspace.steps.find((step) => step.id === dependsOn)?.status !== 'done' ? 'blocked' : 'ready', dependsOn: dependsOn || undefined, context: ['Mission brief', 'Approved predecessor output'], withheld: ['Credentials', 'Unrelated workspace data'] })}>Add bounded step</button></footer></Shell>;
}

function MemoryAddPanel(props: DomainProps): React.JSX.Element {
  const deliverables = props.workspaces.flatMap((workspace) => workspace.steps.filter((step) => step.output).map((step) => ({ workspace, step })));
  const [selectedId, setSelectedId] = useState(deliverables[0]?.step.id ?? ''); const [title, setTitle] = useState('Reviewed mission learning'); const [access, setAccess] = useState('Enterprise Security team only');
  const source = deliverables.find((item) => item.step.id === selectedId);
  return <Shell eyebrow="Company memory" title="Promote reviewed knowledge" onClose={props.onClose} large><div className="dialog-body"><div className="review-path"><span className="complete"><Check />Completed output</span><span className="complete"><Check />Private context removed</span><span className="active">3 Human review</span></div><label className="field-label field-label-spaced" htmlFor="memory-source">Completed deliverable</label><select id="memory-source" value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{deliverables.map((item) => <option key={item.step.id} value={item.step.id}>{item.workspace.name} · {item.step.title}</option>)}</select><label className="field-label field-label-spaced" htmlFor="memory-title">Reusable knowledge title</label><input className="text-input" id="memory-title" value={title} onChange={(event) => setTitle(event.target.value)} /><label className="field-label field-label-spaced" htmlFor="memory-access">Audience</label><select id="memory-access" value={access} onChange={(event) => setAccess(event.target.value)}><option>Enterprise Security team only</option><option>Company-wide read</option><option>Purpose-bound grant required</option></select><div className="truth-boundary"><LockKeyhole size={17} /><span><strong>Raw source context will not be retained</strong><small>Only the reviewed output and its provenance enter company memory.</small></span></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={props.onClose}>Cancel</button><button className="primary-button" disabled={!source || !title.trim()} onClick={() => source && props.onAddMemory({ id: `memory-${Date.now()}`, title: title.trim(), type: 'Learning', owner: source.workspace.team, used: '0 missions', access, x: '48%', y: '18%', tone: '#3767dc', sourceWorkspace: source.workspace.name, reviewedBy: 'Varun Khatr' })}>Review and add to memory</button></footer></Shell>;
}

function PersonPanel(props: DomainProps & { person: Person }): React.JSX.Element {
  const owned = props.agents.filter((agent) => agent.owner === props.person.name); const rooms = props.workspaces.filter((workspace) => workspace.memberIds.includes(props.person.id));
  return <Shell eyebrow="Organization identity" title={props.person.name} onClose={props.onClose} drawer><div className="drawer-body"><div className="profile-hero"><span className="large-avatar" style={{ background: props.person.color }}>{props.person.initials}</span><div><strong>{props.person.role}</strong><span>{props.person.team}</span><small><i className={`presence ${props.person.status}`} />{props.person.status}</small></div></div><DetailSection title="Accountable agents">{owned.length ? owned.map((agent) => <div className="detail-row static-row" key={agent.id}><Bot /><span><strong>{agent.name}</strong><small>{agent.provider} · {agent.status}</small></span></div>) : <p>No directly accountable agents.</p>}</DetailSection><DetailSection title="Shared workspaces">{rooms.map((room) => <button className="detail-row" key={room.id} onClick={() => { props.onClose(); props.onOpenWorkspace(room); }}><FileText /><span><strong>{room.name}</strong><small>{room.activeMission}</small></span><ChevronRight /></button>)}</DetailSection><DetailSection title="Identity & authority"><dl className="summary-list"><div><dt>Employee ID</dt><dd>HP-{props.person.id.toUpperCase()}-2048</dd></div><div><dt>Human proof</dt><dd>Active for eligible actions</dd></div><div><dt>Role scope</dt><dd>{props.person.team}</dd></div></dl></DetailSection></div></Shell>;
}

function AgentPanel(props: DomainProps & { agent: Agent }): React.JSX.Element {
  const assignments = props.workspaces.flatMap((workspace) => workspace.steps.filter((step) => step.agentId === props.agent.id).map((step) => ({ workspace, step })));
  return <Shell eyebrow="Agent passport" title={props.agent.name} onClose={props.onClose} drawer><div className="drawer-body"><div className="agent-detail-hero"><span className="agent-logo" style={{ background: props.agent.color }}><Bot size={28} /></span><div><strong>{props.agent.role}</strong><span>{props.agent.provider} · accountable to {props.agent.owner}</span></div><span className={`status-pill ${props.agent.status === 'needs-attention' ? 'blocked' : props.agent.status}`}><span />{props.agent.status.replace('-', ' ')}</span></div><DetailSection title="Current assignments">{assignments.map(({ workspace, step }) => <button className="detail-row" key={`${workspace.id}-${step.id}`} onClick={() => { props.onClose(); props.onOpenWorkspace(workspace, 'plan'); }}><FileCheck2 /><span><strong>{step.title}</strong><small>{workspace.name} · {step.status}</small></span><ChevronRight /></button>)}</DetailSection><DetailSection title="Authority boundary"><div className="context-preview"><div><Check /><span><strong>Allowed</strong><small>{props.agent.permissions.join(', ')}</small></span></div><div><LockKeyhole /><span><strong>Always withheld</strong><small>Credentials, private notes, unassigned workspaces</small></span></div></div></DetailSection><DetailSection title="Runtime identity"><dl className="summary-list"><div><dt>Passport</dt><dd>agt_{props.agent.id}_hp</dd></div><div><dt>Connection</dt><dd>{props.agent.status === 'offline' ? 'Offline' : 'Observed and ready'}</dd></div><div><dt>Human owner</dt><dd>{props.agent.owner}</dd></div></dl></DetailSection></div></Shell>;
}

function MemoryPanel(props: DomainProps & { record: MemoryRecord; policy: boolean }): React.JSX.Element {
  return <Shell eyebrow={props.policy ? 'Memory access policy' : 'Reviewed memory record'} title={props.record.title} onClose={props.onClose} drawer><div className="drawer-body"><div className="evidence-summary"><BrainCircuit size={24} /><div><strong>{props.record.type}</strong><small>{props.record.owner} · used in {props.record.used}</small></div></div>{props.policy ? <><DetailSection title="Purpose-bound access"><dl className="summary-list"><div><dt>Owner</dt><dd>{props.record.owner}</dd></div><div><dt>Audience</dt><dd>{props.record.access}</dd></div><div><dt>Forwarding</dt><dd>Not allowed outside a new grant</dd></div><div><dt>Agent access</dt><dd>Assignment-specific</dd></div></dl></DetailSection><div className="truth-boundary"><LockKeyhole /><span><strong>Private source context is locked</strong><small>The reusable record cannot reveal the private inputs that produced it.</small></span></div></> : <><DetailSection title="Reviewed content"><p>This record captures the reusable conclusion of a completed mission. It is written for future teams without retaining raw private source material.</p></DetailSection><DetailSection title="Provenance"><dl className="summary-list"><div><dt>Source workspace</dt><dd>{props.record.sourceWorkspace}</dd></div><div><dt>Reviewed by</dt><dd>{props.record.reviewedBy}</dd></div><div><dt>Evidence reference</dt><dd><code>mem_{props.record.id}_receipt</code></dd></div></dl></DetailSection></>}</div></Shell>;
}

function StepPanel(props: DomainProps & { workspace: Workspace; step?: WorkStep }): React.JSX.Element {
  if (!props.step) return <Shell eyebrow="Mission step" title="No step selected" onClose={props.onClose} drawer><div className="drawer-body"><p>No step is available in this workspace.</p></div></Shell>;
  const agent = props.agents.find((item) => item.id === props.step?.agentId);
  return <Shell eyebrow={props.action === 'deliverable' ? 'Governed deliverable' : 'Mission step'} title={props.step.title} onClose={props.onClose} drawer><div className="drawer-body"><div className="agent-detail-hero"><span className="agent-logo" style={{ background: agent?.color }}><Bot size={24} /></span><div><strong>{agent?.name}</strong><span>{agent?.provider} · {props.workspace.name}</span></div><span className={`status-pill ${props.step.status}`}><span />{props.step.status}</span></div><DetailSection title="Outcome"><p>{props.step.summary}</p>{props.step.output ? <div className="deliverable-preview"><FileText /><span><strong>{props.step.output}</strong><small>Attached to this assignment and evidence chain</small></span></div> : null}</DetailSection><DetailSection title="Context boundary"><div className="context-preview"><div><Check /><span><strong>Released</strong><small>{props.step.context.join(', ')}</small></span></div><div><LockKeyhole /><span><strong>Withheld</strong><small>{props.step.withheld.join(', ')}</small></span></div></div></DetailSection><DetailSection title="Trace"><code className="wide-code">evt_{props.workspace.id}_{props.step.id}_receipt</code></DetailSection></div></Shell>;
}

function ExportPanel(props: DomainProps): React.JSX.Element {
  const [includeProof, setIncludeProof] = useState(true);
  function download(): void { const payload = { generatedAt: new Date().toISOString(), organization: 'HP Enterprise', posture: 'Demo dataset', workspaces: props.workspaces, agents: props.agents, reviews: props.reviews, memory: props.memoryRecords, includesPresentationEvidence: includeProof }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'h2a-executive-demo-report.json'; anchor.click(); URL.revokeObjectURL(url); props.onClose(); props.notify('Executive demo report downloaded.'); }
  return <Shell eyebrow="Executive evidence report" title="Prepare a presentation-safe export" onClose={props.onClose}><div className="dialog-body"><div className="report-preview"><ShieldCheck /><div><strong>HP Enterprise · H2A posture</strong><small>{props.workspaces.length} workspaces · {props.agents.length} agents · {props.reviews.filter((review) => review.status === 'pending').length} pending reviews</small></div></div><label className="check-row"><input type="checkbox" defaultChecked /><span>Workspace and mission summary</span></label><label className="check-row"><input type="checkbox" defaultChecked /><span>Agent ownership and readiness</span></label><label className="check-row"><input type="checkbox" checked={includeProof} onChange={(event) => setIncludeProof(event.target.checked)} /><span>Presentation evidence references</span></label><div className="truth-boundary"><LockKeyhole /><span><strong>Secrets and raw private context are excluded</strong><small>The exported JSON is generated from this local demo dataset.</small></span></div></div><footer className="dialog-footer"><button className="secondary-button" onClick={props.onClose}>Cancel</button><button className="primary-button" onClick={download}><Download size={17} />Download report</button></footer></Shell>;
}

function ManagementPanel(props: DomainProps & { workspace: Workspace }): React.JSX.Element {
  const content = {
    organization: { eyebrow: 'Organization', title: 'HP Enterprise', icon: <Users />, body: 'Your employee identity, teams, company agents, and policies live inside this organization.', rows: [['Current environment', 'Security workspace'], ['Visible teams', '6 teams'], ['Company agents', `${props.agents.filter((agent) => agent.provider === 'Company agent').length} published`], ['Trust state', 'Connected and observed']] },
    help: { eyebrow: 'Guided help', title: 'What would you like to do?', icon: <CircleHelp />, body: 'Jump directly to the workflow you need.', rows: [['Start work', 'Create a mission from Home'], ['Build a team', 'Invite people and agents'], ['Review a decision', 'Open Reviews'], ['Inspect evidence', 'Open Admin']] },
    account: { eyebrow: 'Employee identity', title: 'Varun Khatr', icon: <UserRound />, body: 'Security program lead at HP Enterprise.', rows: [['Employee ID', 'HP-VARUN-2048'], ['Human proof', 'Active for eligible actions'], ['Accountable agents', '2'], ['Organization role', 'Administrator']] },
    notifications: { eyebrow: 'Notifications', title: 'What needs attention', icon: <CheckCircle2 />, body: 'Only meaningful state changes and decisions are surfaced.', rows: [['Claude Design Partner', 'Draft completed · 8 min ago'], ['Vendor assessment', 'Approval requested · 18 min remaining'], ['Antigravity QA', 'Permission renewal available']] },
    connections: { eyebrow: 'Organization connections', title: 'Coworkers and trusted peers', icon: <Network />, body: 'Verified organization members are immediately available; external peers require administrator trust.', rows: [['Jordan Brooks', 'Connected · Platform Engineering'], ['Maya Thompson', 'Connected · Corporate Finance'], ['HP Labs node', 'Trusted peer · online'], ['Vendor partner node', 'Offline · no active grants']] },
    policies: { eyebrow: 'Security administration', title: 'Organization policies', icon: <KeyRound />, body: 'These controls apply before work can be assigned or context released.', rows: [['Human accountability', 'Enforced'], ['Least-context sharing', 'Enforced'], ['Independent approval', 'Required for external effects'], ['Remote containment', 'Pinned peer only']] },
    integrations: { eyebrow: 'Connected system', title: props.targetId === 'github' ? 'GitHub Enterprise' : props.targetId === 'research' ? 'Governed research connector' : 'Agent providers', icon: <Bot />, body: 'Capabilities are available only through assignment-specific scope.', rows: [['Connection', 'Healthy'], ['Allowed teams', 'Enterprise Security, Digital Commerce'], ['Last observed', '12 minutes ago'], ['Default access', 'None until assigned']] },
    workspace: { eyebrow: 'Workspace settings', title: props.workspace.name, icon: <FileText />, body: 'A durable collaboration room for many missions, members, decisions, and outputs.', rows: [['Team', props.workspace.team], ['Members', `${props.workspace.memberIds.length} people · ${props.workspace.agentIds.length} agents`], ['Retention', '365 days after mission close'], ['Default context', 'No ambient agent access']] }
  }[props.action as 'organization' | 'help' | 'account' | 'notifications' | 'connections' | 'policies' | 'integrations' | 'workspace'];
  return <Shell eyebrow={content.eyebrow} title={content.title} onClose={props.onClose} drawer><div className="drawer-body"><div className="evidence-summary">{content.icon}<div><strong>{content.title}</strong><small>{content.body}</small></div></div><div className="management-list">{content.rows.map(([label, value]) => <div key={label}><span><strong>{label}</strong><small>{value}</small></span></div>)}</div>{props.action === 'help' ? <div className="drawer-actions"><button className="primary-button" onClick={() => { props.onClose(); props.onNavigate('home'); }}>Go to Home</button><button className="secondary-button" onClick={() => { props.onClose(); props.onNavigate('reviews'); }}>Open Reviews</button></div> : null}{props.action === 'notifications' ? <button className="secondary-button full-button" onClick={() => { props.onClose(); props.notify('Notifications marked as read.'); }}>Mark all as read</button> : null}</div></Shell>;
}

function DetailSection({ title, children }: { title: string; children: React.ReactNode }): React.JSX.Element { return <section className="detail-section"><h3>{title}</h3>{children}</section>; }
