import { useMemo, useState } from 'react';
import { BadgeCheck, Ban, Building2, KeyRound, Plus, RefreshCw, ShieldAlert, ShieldCheck, UserPlus, UsersRound, X } from 'lucide-react';
import type { AuthorityActor, OrganizationAuthorityState } from '@h2a/contracts';
import { StatusBadge } from '@h2a/ui';

type ViewTab = 'employees' | 'roles' | 'credentials' | 'policy';
type Dialog = 'employee' | 'role' | 'credential' | 'transfer' | null;

interface Props {
  state: OrganizationAuthorityState;
  onStateChange(state: OrganizationAuthorityState): void;
  onHumanProofRequired(): void;
}

export function PeopleAuthorityView({ state, onStateChange, onHumanProofRequired }: Props): React.JSX.Element {
  const [tab, setTab] = useState<ViewTab>('employees');
  const [dialog, setDialog] = useState<Dialog>(null);
  const [selectedMembershipId, setSelectedMembershipId] = useState('');
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const actor = useMemo(() => resolveAdministrator(state), [state]);
  const activeOrganization = state.organizations.find((item) => item.status === 'active');
  const activeCredentials = state.credentials.filter((item) => item.status === 'active').length;
  const activeMembers = state.memberships.filter((item) => item.status === 'active').length;

  async function run(label: string, operation: () => Promise<OrganizationAuthorityState>): Promise<void> {
    setBusy(label); setError('');
    try { onStateChange(await operation()); setDialog(null); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'The authority operation failed closed.'); }
    finally { setBusy(''); }
  }

  if (!window.h2a && !activeOrganization) return <div className="authority-page"><Unavailable /></div>;
  if (!activeOrganization) return <Bootstrap state={state} busy={busy} error={error} onProof={onHumanProofRequired} onSubmit={(request) => run('bootstrap', () => window.h2a!.bootstrapOrganization(request))} />;

  return (
    <div className="authority-page">
      <header className="authority-header">
        <div className="authority-title"><span className="authority-title-icon"><Building2 size={21} /></span><div><p className="section-kicker">ORGANIZATION CONTROL PLANE</p><h2>{activeOrganization.name}</h2><span>{activeOrganization.policy_version} / {activeOrganization.organization_id}</span></div></div>
        <div className="authority-metrics" aria-label="Organization authority metrics"><Metric label="Active people" value={activeMembers} /><Metric label="Active credentials" value={activeCredentials} /><Metric label="Roles" value={state.roles.filter((item) => item.status === 'active').length} /><Metric label="Decisions" value={state.decisions.length} /></div>
      </header>

      {!actor && <button data-control-id="organization.proof.request" className="authority-alert authority-alert-button" type="button" onClick={onHumanProofRequired}><ShieldAlert size={18} /><span><strong>Administrator verification required</strong><small>Refresh the administrator Human Proof before changing people, roles, or credentials.</small></span></button>}
      {error && <div className="inline-error authority-error" role="alert">{error}</div>}

      <div className="authority-tabs" role="tablist" aria-label="People and authority views">
        {(['employees', 'roles', 'credentials', 'policy'] as const).map((value) => <button type="button" role="tab" aria-selected={tab === value} className={tab === value ? 'active' : ''} key={value} onClick={() => setTab(value)}>{value === 'employees' ? <UsersRound size={16} /> : value === 'roles' ? <ShieldCheck size={16} /> : value === 'credentials' ? <KeyRound size={16} /> : <BadgeCheck size={16} />}{label(value)}</button>)}
      </div>

      {tab === 'employees' && <EmployeeDirectory state={state} busy={busy} actor={actor} onAdd={() => setDialog('employee')} onTransfer={(id) => { setSelectedMembershipId(id); setDialog('transfer'); }} onLifecycle={(membershipId, action) => actor && run(`${action}-${membershipId}`, () => window.h2a!.updateOrganizationMembership({ actor, membership_id: membershipId, action }))} />}
      {tab === 'roles' && <RoleRegistry state={state} actor={actor} onAdd={() => setDialog('role')} />}
      {tab === 'credentials' && <CredentialRegistry state={state} busy={busy} actor={actor} onIssue={() => setDialog('credential')} onLifecycle={(credentialId, action) => actor && run(`${action}-${credentialId}`, () => window.h2a!.updateHumanAuthorityCredential({ actor, credential_id: credentialId, action }))} />}
      {tab === 'policy' && <PolicyTester state={state} busy={busy} onEvaluate={(request) => run('evaluate', () => window.h2a!.evaluateHumanAuthority(request))} />}

      {dialog === 'employee' && actor && <EmployeeDialog state={state} actor={actor} busy={busy} onClose={() => setDialog(null)} onSubmit={(request) => run('join', () => window.h2a!.joinOrganizationMembership(request))} />}
      {dialog === 'role' && actor && <RoleDialog organizationId={activeOrganization.organization_id} actor={actor} busy={busy} onClose={() => setDialog(null)} onSubmit={(request) => run('create-role', () => window.h2a!.createAuthorityRole(request))} />}
      {dialog === 'credential' && actor && <CredentialDialog state={state} actor={actor} busy={busy} onClose={() => setDialog(null)} onSubmit={(request) => run('issue-credential', () => window.h2a!.issueHumanAuthorityCredential(request))} />}
      {dialog === 'transfer' && actor && <TransferDialog state={state} membershipId={selectedMembershipId} actor={actor} busy={busy} onClose={() => setDialog(null)} onSubmit={(request) => run('transfer', () => window.h2a!.updateOrganizationMembership(request))} />}
    </div>
  );
}

function Bootstrap({ state, busy, error, onProof, onSubmit }: { state: OrganizationAuthorityState; busy: string; error: string; onProof(): void; onSubmit(request: Parameters<NonNullable<typeof window.h2a>['bootstrapOrganization']>[0]): void }): React.JSX.Element {
  const assurance = state.assurance[0];
  const [name, setName] = useState('HP Enterprise Demo');
  const [organizationId, setOrganizationId] = useState('org_hp_demo');
  const [policyVersion, setPolicyVersion] = useState('policy_2026_01');
  const [employeeId, setEmployeeId] = useState('E-100');
  const [department, setDepartment] = useState('Enterprise Security');
  const [expiresAt, setExpiresAt] = useState(localExpiry(30));
  return <div className="authority-bootstrap"><section className="bootstrap-heading"><span className="authority-title-icon"><Building2 size={22} /></span><div><p className="section-kicker">TRUSTED ORGANIZATION SETUP</p><h2>Establish the authority root</h2><p>The first verified employee receives the signed administrator credential used for all later authority changes.</p></div></section>{!assurance && <button className="authority-alert authority-alert-button" type="button" onClick={onProof}><ShieldAlert size={18} /><span><strong>Current Human Proof required</strong><small>Verify an enrolled employee before organization bootstrap.</small></span></button>}<section className="bootstrap-form"><div className="form-grid"><Field label="Organization name"><input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Organization ID"><input value={organizationId} onChange={(event) => setOrganizationId(event.target.value)} /></Field><Field label="Policy version"><input value={policyVersion} onChange={(event) => setPolicyVersion(event.target.value)} /></Field><Field label="Employee ID"><input value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} /></Field><Field label="Department"><input value={department} onChange={(event) => setDepartment(event.target.value)} /></Field><Field label="Administrator credential expiry"><input type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></Field></div><dl className="bootstrap-binding"><Fact term="Human" value={assurance?.human_id ?? 'Verification required'} /><Fact term="Membership" value={assurance?.membership_id ?? 'Verification required'} /><Fact term="Proof" value={assurance?.human_proof_id ?? 'Not available'} /></dl>{error && <div className="inline-error" role="alert">{error}</div>}<button data-control-id="organization.bootstrap" className="primary-button" type="button" disabled={!assurance || busy === 'bootstrap'} onClick={() => assurance && onSubmit({ organization_id: organizationId.trim(), name: name.trim(), policy_version: policyVersion.trim(), human_id: assurance.human_id, membership_id: assurance.membership_id, human_proof_id: assurance.human_proof_id, employee_id: employeeId.trim(), department: department.trim(), credential_expires_at: toIso(expiresAt) })}><ShieldCheck size={17} />{busy === 'bootstrap' ? 'Establishing...' : 'Establish authority root'}</button></section></div>;
}

function EmployeeDirectory({ state, actor, busy, onAdd, onTransfer, onLifecycle }: { state: OrganizationAuthorityState; actor?: AuthorityActor; busy: string; onAdd(): void; onTransfer(id: string): void; onLifecycle(id: string, action: 'suspend' | 'reactivate' | 'terminate'): void }): React.JSX.Element {
  const roles = new Map(state.roles.map((item) => [item.role_id, item.name]));
  return <section className="authority-workbench"><div className="authority-section-head"><div><p className="section-kicker">EMPLOYEE DIRECTORY</p><h3>Membership and reporting lines</h3></div><button className="primary-button" type="button" disabled={!actor} onClick={onAdd}><UserPlus size={16} /> Join employee</button></div><div className="table-scroll"><table className="data-table authority-table"><thead><tr><th>Employee</th><th>Department</th><th>Manager</th><th>Roles</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{state.memberships.map((item) => <tr key={item.membership_id}><td><strong>{item.employee_id}</strong><code>{item.membership_id}</code><small>{item.human_id}</small></td><td>{item.department}</td><td>{item.manager_membership_id ?? 'Organization root'}</td><td>{item.role_ids.map((id) => roles.get(id) ?? id).join(', ') || 'No role'}</td><td><StatusBadge label={item.status} tone={statusTone(item.status)} /></td><td><div className="row-actions">{item.status === 'active' ? <><button data-control-id="organization.membership.lifecycle" title="Transfer employee" aria-label={`Transfer ${item.employee_id}`} disabled={!actor || Boolean(busy)} onClick={() => onTransfer(item.membership_id)}><RefreshCw size={15} /></button><button data-control-id="organization.membership.lifecycle" title="Suspend membership" aria-label={`Suspend ${item.employee_id}`} disabled={!actor || Boolean(busy)} onClick={() => onLifecycle(item.membership_id, 'suspend')}><Ban size={15} /></button></> : ['suspended', 'transferred'].includes(item.status) ? <button data-control-id="organization.membership.lifecycle" title="Reactivate membership" aria-label={`Reactivate ${item.employee_id}`} disabled={!actor || Boolean(busy)} onClick={() => onLifecycle(item.membership_id, 'reactivate')}><RefreshCw size={15} /></button> : null}<button data-control-id="organization.membership.lifecycle" className="danger-icon" title="Terminate membership" aria-label={`Terminate ${item.employee_id}`} disabled={!actor || Boolean(busy) || item.status === 'terminated'} onClick={() => onLifecycle(item.membership_id, 'terminate')}><X size={15} /></button></div></td></tr>)}</tbody></table></div></section>;
}

function RoleRegistry({ state, actor, onAdd }: { state: OrganizationAuthorityState; actor?: AuthorityActor; onAdd(): void }): React.JSX.Element {
  return <section className="authority-workbench"><div className="authority-section-head"><div><p className="section-kicker">ROLE CATALOGUE</p><h3>RBAC with bounded attributes</h3></div><button className="primary-button" type="button" disabled={!actor} onClick={onAdd}><Plus size={16} /> Create role</button></div><div className="role-list">{state.roles.map((role) => <article className="role-row" key={`${role.organization_id}-${role.role_id}`}><span className="role-icon"><ShieldCheck size={17} /></span><div><strong>{role.name}</strong><code>{role.role_id}</code><p>{role.description}</p></div><div className="role-scopes">{role.authority_scopes.map((scope) => <span key={`${scope.resource}-${scope.actions.join()}`}><b>{scope.resource}</b> {scope.actions.join(', ')}{scope.max_amount !== undefined ? ` / $${scope.max_amount}` : ''}{scope.max_records !== undefined ? ` / ${scope.max_records} records` : ''}</span>)}</div><div><StatusBadge label={role.status} tone={role.status === 'active' ? 'verified' : 'neutral'} /><small>{role.approval_powers.length ? role.approval_powers.join(', ') : 'No approval power'}</small></div></article>)}</div></section>;
}

function CredentialRegistry({ state, actor, busy, onIssue, onLifecycle }: { state: OrganizationAuthorityState; actor?: AuthorityActor; busy: string; onIssue(): void; onLifecycle(id: string, action: 'suspend' | 'reactivate' | 'revoke'): void }): React.JSX.Element {
  return <section className="authority-workbench"><div className="authority-section-head"><div><p className="section-kicker">SIGNED CREDENTIALS</p><h3>Human business authority</h3></div><button className="primary-button" type="button" disabled={!actor} onClick={onIssue}><KeyRound size={16} /> Issue credential</button></div><div className="credential-list">{state.credentials.map((item) => <article className="credential-row" key={item.credential_id}><span className="credential-key"><KeyRound size={17} /></span><div><strong>{membershipName(state, item.membership_id)}</strong><code>{item.credential_id}</code><small>{item.role_ids.join(', ')}</small></div><dl><Fact term="Expires" value={formatDate(item.expires_at)} /><Fact term="Signature" value={short(item.organization_signature)} /></dl><StatusBadge label={item.status} tone={statusTone(item.status)} /><div className="row-actions">{item.status === 'active' && <button data-control-id="organization.credential.lifecycle" title="Suspend credential" aria-label={`Suspend ${item.credential_id}`} disabled={!actor || Boolean(busy)} onClick={() => onLifecycle(item.credential_id, 'suspend')}><Ban size={15} /></button>}{item.status === 'suspended' && <button data-control-id="organization.credential.lifecycle" title="Reactivate credential" aria-label={`Reactivate ${item.credential_id}`} disabled={!actor || Boolean(busy)} onClick={() => onLifecycle(item.credential_id, 'reactivate')}><RefreshCw size={15} /></button>}<button data-control-id="organization.credential.lifecycle" className="danger-icon" title="Revoke credential" aria-label={`Revoke ${item.credential_id}`} disabled={!actor || Boolean(busy) || ['revoked', 'expired'].includes(item.status)} onClick={() => onLifecycle(item.credential_id, 'revoke')}><X size={15} /></button></div></article>)}</div></section>;
}

function PolicyTester({ state, busy, onEvaluate }: { state: OrganizationAuthorityState; busy: string; onEvaluate(request: Parameters<NonNullable<typeof window.h2a>['evaluateHumanAuthority']>[0]): void }): React.JSX.Element {
  const candidates = state.memberships.filter((member) => state.assurance.some((proof) => proof.membership_id === member.membership_id) && state.credentials.some((credential) => credential.membership_id === member.membership_id && credential.status === 'active'));
  const [membershipId, setMembershipId] = useState(candidates[0]?.membership_id ?? '');
  const [resource, setResource] = useState('mandate'); const [action, setAction] = useState('issue');
  const [amount, setAmount] = useState(''); const [records, setRecords] = useState(''); const [approvalPower, setApprovalPower] = useState('');
  const assurance = state.assurance.find((item) => item.membership_id === membershipId);
  const credential = state.credentials.find((item) => item.membership_id === membershipId && item.status === 'active');
  const latest = state.decisions[0];
  return <section className="authority-policy"><div className="policy-form"><div><p className="section-kicker">AUTHORITY DECISION POINT</p><h3>Evaluate protected operation</h3></div><Field label="Verified employee"><select value={membershipId} onChange={(event) => setMembershipId(event.target.value)}><option value="">Select employee</option>{candidates.map((item) => <option key={item.membership_id} value={item.membership_id}>{item.employee_id} - {item.department}</option>)}</select></Field><div className="form-grid"><Field label="Resource"><input value={resource} onChange={(event) => setResource(event.target.value)} /></Field><Field label="Action"><input value={action} onChange={(event) => setAction(event.target.value)} /></Field><Field label="Maximum amount"><input type="number" min="0" value={amount} onChange={(event) => setAmount(event.target.value)} /></Field><Field label="Record count"><input type="number" min="1" value={records} onChange={(event) => setRecords(event.target.value)} /></Field><Field label="Required approval power"><input value={approvalPower} onChange={(event) => setApprovalPower(event.target.value)} placeholder="mandate.approve" /></Field></div><button data-control-id="organization.authority.evaluate" className="primary-button" type="button" disabled={!assurance || !credential || busy === 'evaluate'} onClick={() => assurance && credential && onEvaluate({ organization_id: credential.organization_id, membership_id: membershipId, human_proof_id: assurance.human_proof_id, authority_credential_id: credential.credential_id, resource: resource.trim(), action: action.trim(), amount: amount ? Number(amount) : undefined, records: records ? Number(records) : undefined, required_approval_power: approvalPower.trim() || undefined, purpose: `${action.trim()} ${resource.trim()}` })}><BadgeCheck size={16} />{busy === 'evaluate' ? 'Evaluating...' : 'Evaluate authority'}</button></div><div className={`policy-result ${latest?.decision === 'ALLOW' ? 'allowed' : latest ? 'denied' : ''}`}>{latest ? <><span>{latest.decision === 'ALLOW' ? <ShieldCheck size={22} /> : <ShieldAlert size={22} />}</span><p className="section-kicker">LATEST DECISION</p><h3>{latest.decision}</h3><strong>{latest.reason_code}</strong><dl><Fact term="Employee" value={membershipName(state, latest.membership_id)} /><Fact term="Operation" value={`${latest.resource} / ${latest.action}`} /><Fact term="Matched roles" value={latest.matched_role_ids.join(', ') || 'None'} /><Fact term="Trace" value={latest.trace_id} /></dl></> : <><span><BadgeCheck size={22} /></span><h3>No decision yet</h3><p>Select a verified employee and evaluate a protected operation.</p></>}</div></section>;
}

function EmployeeDialog({ state, actor, busy, onClose, onSubmit }: { state: OrganizationAuthorityState; actor: AuthorityActor; busy: string; onClose(): void; onSubmit(request: Parameters<NonNullable<typeof window.h2a>['joinOrganizationMembership']>[0]): void }): React.JSX.Element {
  const org = state.organizations[0]; const [humanId, setHumanId] = useState(''); const [membershipId, setMembershipId] = useState(''); const [employeeId, setEmployeeId] = useState(''); const [department, setDepartment] = useState(''); const [manager, setManager] = useState(''); const [roleIds, setRoleIds] = useState<string[]>([]);
  return <Modal title="Join employee" subtitle="Bind an enrolled human identity to organization authority." onClose={onClose} footer={<button data-control-id="organization.membership.join" className="primary-button" disabled={!humanId || !membershipId || !employeeId || !department || busy === 'join'} onClick={() => onSubmit({ actor, organization_id: org.organization_id, human_id: humanId.trim(), membership_id: membershipId.trim(), employee_id: employeeId.trim(), department: department.trim(), manager_membership_id: manager || undefined, role_ids: roleIds })}><UserPlus size={16} /> Join</button>}><div className="form-grid"><Field label="Human ID"><input value={humanId} onChange={(event) => setHumanId(event.target.value)} /></Field><Field label="Membership ID"><input value={membershipId} onChange={(event) => setMembershipId(event.target.value)} /></Field><Field label="Employee ID"><input value={employeeId} onChange={(event) => setEmployeeId(event.target.value)} /></Field><Field label="Department"><input value={department} onChange={(event) => setDepartment(event.target.value)} /></Field><Field label="Manager"><select value={manager} onChange={(event) => setManager(event.target.value)}><option value="">Organization root</option>{state.memberships.filter((item) => item.status === 'active').map((item) => <option key={item.membership_id} value={item.membership_id}>{item.employee_id} - {item.department}</option>)}</select></Field></div><Checkboxes label="Assigned roles" options={state.roles.filter((item) => item.status === 'active').map((item) => ({ id: item.role_id, label: item.name }))} values={roleIds} onChange={setRoleIds} /></Modal>;
}

function RoleDialog({ organizationId, actor, busy, onClose, onSubmit }: { organizationId: string; actor: AuthorityActor; busy: string; onClose(): void; onSubmit(request: Parameters<NonNullable<typeof window.h2a>['createAuthorityRole']>[0]): void }): React.JSX.Element {
  const [roleId, setRoleId] = useState(''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [resource, setResource] = useState(''); const [actions, setActions] = useState(''); const [maxAmount, setMaxAmount] = useState(''); const [maxRecords, setMaxRecords] = useState(''); const [powers, setPowers] = useState('');
  return <Modal title="Create authority role" subtitle="Define business authority independently from biometric assurance." onClose={onClose} footer={<button data-control-id="organization.role.create" className="primary-button" disabled={!roleId || !name || !description || !resource || !actions || busy === 'create-role'} onClick={() => onSubmit({ actor, organization_id: organizationId, role_id: roleId.trim(), name: name.trim(), description: description.trim(), authority_scopes: [{ resource: resource.trim(), actions: csv(actions), max_amount: maxAmount ? Number(maxAmount) : undefined, max_records: maxRecords ? Number(maxRecords) : undefined }], approval_powers: csv(powers) })}><Plus size={16} /> Create role</button>}><div className="form-grid"><Field label="Role ID"><input value={roleId} onChange={(event) => setRoleId(event.target.value)} placeholder="role_security_reviewer" /></Field><Field label="Name"><input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Description" wide><textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></Field><Field label="Resource"><input value={resource} onChange={(event) => setResource(event.target.value)} placeholder="mandate" /></Field><Field label="Actions"><input value={actions} onChange={(event) => setActions(event.target.value)} placeholder="issue, approve" /></Field><Field label="Maximum amount"><input type="number" min="0" value={maxAmount} onChange={(event) => setMaxAmount(event.target.value)} /></Field><Field label="Maximum records"><input type="number" min="1" value={maxRecords} onChange={(event) => setMaxRecords(event.target.value)} /></Field><Field label="Approval powers" wide><input value={powers} onChange={(event) => setPowers(event.target.value)} placeholder="mandate.approve" /></Field></div></Modal>;
}

function CredentialDialog({ state, actor, busy, onClose, onSubmit }: { state: OrganizationAuthorityState; actor: AuthorityActor; busy: string; onClose(): void; onSubmit(request: Parameters<NonNullable<typeof window.h2a>['issueHumanAuthorityCredential']>[0]): void }): React.JSX.Element {
  const candidates = state.memberships.filter((item) => item.status === 'active'); const [membershipId, setMembershipId] = useState(candidates[0]?.membership_id ?? ''); const member = candidates.find((item) => item.membership_id === membershipId); const [roleIds, setRoleIds] = useState<string[]>([]); const [resources, setResources] = useState(''); const [actions, setActions] = useState(''); const [expiresAt, setExpiresAt] = useState(localExpiry(30));
  const availableRoles = state.roles.filter((role) => member?.role_ids.includes(role.role_id) && role.status === 'active');
  return <Modal title="Issue authority credential" subtitle="Sign the employee's current role assignment and optional constraints." onClose={onClose} footer={<button data-control-id="organization.credential.issue" className="primary-button" disabled={!membershipId || !roleIds.length || busy === 'issue-credential'} onClick={() => onSubmit({ actor, organization_id: state.organizations[0].organization_id, membership_id: membershipId, role_ids: roleIds, resource_constraints: csv(resources), action_constraints: csv(actions), approval_policy_ids: [], expires_at: toIso(expiresAt) })}><KeyRound size={16} /> Issue</button>}><Field label="Employee"><select value={membershipId} onChange={(event) => { setMembershipId(event.target.value); setRoleIds([]); }}><option value="">Select employee</option>{candidates.map((item) => <option key={item.membership_id} value={item.membership_id}>{item.employee_id} - {item.department}</option>)}</select></Field><Checkboxes label="Credential roles" options={availableRoles.map((item) => ({ id: item.role_id, label: item.name }))} values={roleIds} onChange={setRoleIds} /><div className="form-grid"><Field label="Resource constraints"><input value={resources} onChange={(event) => setResources(event.target.value)} placeholder="Empty uses role scopes" /></Field><Field label="Action constraints"><input value={actions} onChange={(event) => setActions(event.target.value)} placeholder="Empty uses role actions" /></Field><Field label="Expires"><input type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></Field></div></Modal>;
}

function TransferDialog({ state, membershipId, actor, busy, onClose, onSubmit }: { state: OrganizationAuthorityState; membershipId: string; actor: AuthorityActor; busy: string; onClose(): void; onSubmit(request: Parameters<NonNullable<typeof window.h2a>['updateOrganizationMembership']>[0]): void }): React.JSX.Element {
  const member = state.memberships.find((item) => item.membership_id === membershipId)!; const [department, setDepartment] = useState(member.department); const [manager, setManager] = useState(member.manager_membership_id ?? ''); const [roleIds, setRoleIds] = useState(member.role_ids);
  return <Modal title="Transfer employee" subtitle="Transfer revokes existing credentials; reactivate and issue fresh authority after review." onClose={onClose} footer={<button data-control-id="organization.membership.lifecycle" className="primary-button" disabled={!department || busy === 'transfer'} onClick={() => onSubmit({ actor, membership_id: membershipId, action: 'transfer', department: department.trim(), manager_membership_id: manager || undefined, role_ids: roleIds })}><RefreshCw size={16} /> Transfer</button>}><div className="form-grid"><Field label="Department"><input value={department} onChange={(event) => setDepartment(event.target.value)} /></Field><Field label="Manager"><select value={manager} onChange={(event) => setManager(event.target.value)}><option value="">Organization root</option>{state.memberships.filter((item) => item.status === 'active' && item.membership_id !== membershipId).map((item) => <option key={item.membership_id} value={item.membership_id}>{item.employee_id} - {item.department}</option>)}</select></Field></div><Checkboxes label="Roles after transfer" options={state.roles.filter((item) => item.status === 'active').map((item) => ({ id: item.role_id, label: item.name }))} values={roleIds} onChange={setRoleIds} /></Modal>;
}

function Modal({ title, subtitle, onClose, footer, children }: { title: string; subtitle: string; onClose(): void; footer: React.ReactNode; children: React.ReactNode }): React.JSX.Element { return <div className="modal-scrim" role="presentation"><div className="authority-dialog" role="dialog" aria-modal="true" aria-labelledby="authority-dialog-title"><header><div><h2 id="authority-dialog-title">{title}</h2><p>{subtitle}</p></div><button className="icon-button" type="button" aria-label="Close" title="Close" onClick={onClose}><X size={18} /></button></header><div className="authority-dialog-body">{children}</div><footer><button className="secondary-button" type="button" onClick={onClose}>Cancel</button>{footer}</footer></div></div>; }
function Checkboxes({ label: heading, options, values, onChange }: { label: string; options: Array<{ id: string; label: string }>; values: string[]; onChange(values: string[]): void }): React.JSX.Element { return <fieldset className="authority-checkboxes"><legend>{heading}</legend>{options.length ? options.map((item) => <label key={item.id}><input type="checkbox" checked={values.includes(item.id)} onChange={(event) => onChange(event.target.checked ? [...values, item.id] : values.filter((value) => value !== item.id))} /><span><strong>{item.label}</strong><code>{item.id}</code></span></label>) : <p>No eligible roles.</p>}</fieldset>; }
function Field({ label: heading, wide = false, children }: { label: string; wide?: boolean; children: React.ReactNode }): React.JSX.Element { return <label className={`field ${wide ? 'form-field-wide' : ''}`}><span>{heading}</span>{children}</label>; }
function Fact({ term, value }: { term: string; value: string }): React.JSX.Element { return <div><dt>{term}</dt><dd>{value}</dd></div>; }
function Metric({ label: heading, value }: { label: string; value: number }): React.JSX.Element { return <div><span>{heading}</span><strong>{value}</strong></div>; }
function Unavailable(): React.JSX.Element { return <section className="authority-workbench"><ShieldAlert size={24} /><h2>Trusted runtime required</h2><p>Organization authority is available in the local Electron application.</p></section>; }
function resolveAdministrator(state: OrganizationAuthorityState): AuthorityActor | undefined { for (const proof of state.assurance) { const credential = state.credentials.find((item) => item.membership_id === proof.membership_id && item.status === 'active' && item.role_ids.includes('role_authority_admin')); if (credential) return { membership_id: proof.membership_id, human_proof_id: proof.human_proof_id, authority_credential_id: credential.credential_id }; } return undefined; }
function membershipName(state: OrganizationAuthorityState, id: string): string { const item = state.memberships.find((member) => member.membership_id === id); return item ? `${item.employee_id} / ${item.department}` : id; }
function statusTone(status: string): 'neutral' | 'verified' | 'approval' | 'danger' { return status === 'active' ? 'verified' : status === 'suspended' || status === 'transferred' ? 'approval' : status === 'revoked' || status === 'terminated' ? 'danger' : 'neutral'; }
function label(value: string): string { return value.charAt(0).toUpperCase() + value.slice(1); }
function csv(value: string): string[] { return [...new Set(value.split(',').map((item) => item.trim()).filter(Boolean))]; }
function short(value: string): string { return value.length > 24 ? `${value.slice(0, 18)}...${value.slice(-5)}` : value; }
function formatDate(value: string): string { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function localExpiry(days: number): string { const date = new Date(Date.now() + days * 86_400_000); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function toIso(value: string): string { return new Date(value).toISOString(); }
