import { useEffect, useId, useMemo, useRef, useState, type KeyboardEvent } from 'react';
import { ArrowLeft, ArrowRight, Bot, Check, ChevronRight, CircleHelp, ClipboardCheck, Fingerprint, Laptop, LockKeyhole, Monitor, Search, Server, ShieldCheck, ShieldQuestion, Users } from 'lucide-react';
import { ProductMark } from '../ProductMark';
import { ToolMark } from './ToolMark';
import { agentProof, buildEstate } from './estate-model';
import { personName, type Department, type Playback, type Scenario } from './model';
import './agent-estate-explorer.css';

type Inspection = { kind:'agent'|'human'|'discovery'|'task'; id:string };
type Props = { scenario:Scenario; playback:Playback; department:Department|'All'; query:string; onInspect:(selection:Inspection)=>void; onInteract?:()=>void };
type Tab = 'Agents'|'Devices'|'People'|'Discovered software'|'Tool access';
type AgentProof = NonNullable<ReturnType<typeof agentProof>>;
type Device = ReturnType<typeof buildEstate>['devices'][number];
type Observation = ReturnType<typeof buildEstate>['observations'][number];
const tabs:Array<[Tab,typeof Bot]> = [['Agents',Bot],['Devices',Laptop],['People',Users],['Discovered software',Search],['Tool access',LockKeyhole]];
const statuses=['Approved','Waiting for approval','Blocked','Unverified'] as const;
const initials=(name:string)=>name.split(' ').map(part=>part[0]).slice(0,2).join('');
const runtimeNames={claude:'Claude Code',codex:'Codex',gemini:'Gemini',antigravity:'Antigravity'};
const date=(value:string)=>new Date(value).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const statusClass=(status:string)=>status==='Approved'?'ae-ok':status==='Blocked'?'ae-blocked':status==='Waiting for approval'?'ae-waiting':'ae-unknown';

export function AgentEstateExplorer({scenario,playback,department,query,onInspect,onInteract}:Props) {
  const [tab,setTab]=useState<Tab>('Agents');
  const [kind,setKind]=useState('All');
  const [ownership,setOwnership]=useState('All');
  const [softwareStatus,setSoftwareStatus]=useState('All');
  const [selectedDevice,setSelectedDevice]=useState<string|null>(null);
  const [selectedTool,setSelectedTool]=useState<string|null>(null);
  const [limit,setLimit]=useState(12);
  const explorerRef=useRef<HTMLDivElement>(null);
  const groupId=useId().replace(/:/g,'');
  const estate=useMemo(()=>buildEstate(scenario,playback),[scenario,playback]);
  const proofs=useMemo(()=>scenario.agents.map(agent=>agentProof(scenario,playback,agent.id)).filter((proof):proof is AgentProof=>Boolean(proof)),[scenario,playback]);
  const normalized=query.toLocaleLowerCase().trim();
  const match=(team:string,text:string)=>(department==='All'||team===department)&&(!normalized||text.toLocaleLowerCase().includes(normalized));
  const agentSet=proofs.filter(proof=>match(proof.agent.department,`${proof.agent.id} ${proof.agent.name} ${proof.agent.department} ${proof.agent.kind} ${proof.owner.name} ${proof.device.name} ${proof.device.ownership} ${runtimeNames[proof.agent.runtime]}`));
  const deviceSet=estate.devices.filter(device=>match(device.department,`${device.name} ${device.id} ${device.department} ${device.os} ${device.ownership} ${device.kind} ${personName(scenario,device.custodianId)} ${proofs.filter(proof=>proof.device.id===device.id).map(proof=>proof.agent.name).join(' ')}`));
  const peopleSet=scenario.people.filter(person=>match(person.department,`${person.name} ${person.role} ${person.department} ${person.level} ${scenario.agents.filter(agent=>agent.owner===person.id).map(agent=>agent.name).join(' ')}`));
  const observationSet=estate.observations.filter(observation=>{const device=estate.devices.find(device=>device.id===observation.deviceId);return match(observation.department,`${observation.name} ${observation.department} ${observation.status} ${observation.source} ${observation.reason} ${device?.name} ${device?personName(scenario,device.custodianId):''}`);});
  const toolSet=estate.tools.filter(tool=>match(tool.department,`${tool.name} ${tool.department} ${tool.permission} ${proofs.filter(proof=>proof.agent.department===tool.department).map(proof=>`${proof.agent.name} ${proof.owner.name}`).join(' ')}`));
  const agents=agentSet.filter(proof=>kind==='All'||proof.agent.kind===kind);
  const devices=deviceSet.filter(device=>ownership==='All'||device.ownership===ownership);
  const observations=observationSet.filter(observation=>softwareStatus==='All'||observation.status===softwareStatus);
  const totals:Record<Tab,number>={Agents:agents.length,Devices:devices.length,People:peopleSet.length,'Discovered software':observations.length,'Tool access':toolSet.length};
  const unfilteredTotals:Record<Tab,number>={Agents:agentSet.length,Devices:deviceSet.length,People:peopleSet.length,'Discovered software':observationSet.length,'Tool access':toolSet.length};
  const teamAgents=agentSet.filter(proof=>proof.agent.kind==='Team').length;
  const personalAgents=agentSet.length-teamAgents;
  const companyDevices=deviceSet.filter(device=>device.ownership==='Company-owned').length;
  const byod=deviceSet.length-companyDevices;
  const deviceDetail=devices.find(device=>device.id===selectedDevice);
  const toolDetail=toolSet.find(tool=>tool.id===selectedTool);
  const inspect=(selection:Inspection)=>{onInteract?.();onInspect(selection);};
  const changeTab=(next:Tab)=>{onInteract?.();setTab(next);setLimit(12);};
  const filterKind=(next:string)=>{changeTab('Agents');setKind(next);};
  const filterOwnership=(next:string)=>{changeTab('Devices');setOwnership(next);setSelectedDevice(null);};
  const filterSoftware=(next:string)=>{changeTab('Discovered software');setSoftwareStatus(next);};
  const openDevice=(id:string)=>{changeTab('Devices');setOwnership('All');setSelectedDevice(id);};
  const openTool=(id:string)=>{changeTab('Tool access');setSelectedTool(id);};
  useEffect(()=>{setLimit(12);setSelectedDevice(null);setSelectedTool(null);},[department,query]);
  useEffect(()=>{
    const target=selectedDevice&&tab==='Devices'?'estate-device-detail':selectedTool&&tab==='Tool access'?'estate-tool-detail':null;
    if(!target)return;
    const panel=explorerRef.current?.querySelector(`[data-testid="${target}"]`);
    panel?.scrollIntoView({block:'nearest',behavior:'instant'});
  },[selectedDevice,selectedTool,tab]);
  const tabKeys=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{
    let next=index;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;
    event.preventDefault();changeTab(tabs[next][0]);(event.currentTarget.parentElement?.querySelector(`[data-estate-tab="${tabs[next][0]}"]`) as HTMLButtonElement|null)?.focus();
  };

  return <div ref={explorerRef} className="agent-estate-explorer" data-testid="agent-estate-explorer">
    <div className="ae-summary-grid">
      <section className="ae-summary ae-agent-summary"><header><span className="ae-eyebrow">REGISTERED IDENTITIES</span><button className="ae-link" onClick={()=>filterKind('All')} aria-label="Show all registered agents">Explore<ArrowRight/></button></header><div className="ae-composition"><button className="ae-donut-button" onClick={()=>filterKind('All')} aria-label={`${agentSet.length} registered agents: ${teamAgents} shared and ${personalAgents} personal`}><Donut shared={teamAgents} personal={personalAgents}/><span><strong>{agentSet.length}</strong><small>bound agents</small></span></button><div className="ae-chart-key"><button onClick={()=>filterKind('Team')}><i className="ae-key-shared"/><span>Shared team agents<small>Mandate owned by a team lead</small></span><b>{teamAgents}</b></button><button onClick={()=>filterKind('Personal')}><i className="ae-key-personal"/><span>Personal agents<small>One accountable individual</small></span><b>{personalAgents}</b></button><span className="ae-summary-assurance"><ShieldCheck/>{agentSet.filter(proof=>proof.deployment.status==='Approved').length} approved identities · {agentSet.length-agentSet.filter(proof=>proof.deployment.status==='Approved').length} unapproved</span></div></div></section>
      <section className="ae-summary"><header><span className="ae-eyebrow">DEVICES & OWNERSHIP</span><button className="ae-link" onClick={()=>filterOwnership('All')} aria-label="Show all devices">Explore<ArrowRight/></button></header><div className="ae-device-summary"><span className="ae-large-icon"><Laptop/></span><div><strong>{deviceSet.length}</strong><span>registered devices</span><small>{deviceSet.filter(device=>device.kind==='Laptop').length} laptops · {deviceSet.filter(device=>device.kind==='Shared runtime host').length} runtime hosts</small></div></div><div className="ae-ownership-strip" aria-label={`${companyDevices} company-owned devices and ${byod} BYOD devices`}><button style={{flex:companyDevices||1}} onClick={()=>filterOwnership('Company-owned')} aria-label={`Show ${companyDevices} company-owned devices`}><span>Company-owned</span><strong>{companyDevices}</strong></button><button className="ae-byod" style={{flex:byod||1}} onClick={()=>filterOwnership('BYOD')} aria-label={`Show ${byod} BYOD devices`}><span>BYOD</span><strong>{byod}</strong></button></div><p className="ae-summary-note">A device is a host—not another agent identity.</p></section>
      <section className="ae-summary"><header><span className="ae-eyebrow">DISCOVERED SOFTWARE</span><button className="ae-link" onClick={()=>filterSoftware('All')} aria-label="Show all discovered software">Inspect<ArrowRight/></button></header><div className="ae-software-heading"><strong>{observationSet.length}</strong><span>software observations<small>Separate from {agentSet.length} registered agent identities</small></span></div><div className="ae-status-segments">{statuses.map(status=><button className={statusClass(status)} key={status} onClick={()=>filterSoftware(status)} aria-label={`Show ${status.toLowerCase()} software`}><b>{observationSet.filter(observation=>observation.status===status).length}</b><span>{status}</span></button>)}</div><p className="ae-summary-note">An installation does not prove an agent ran or accessed data.</p></section>
    </div>
    <div className="ae-definition-note"><CircleHelp/><p><strong>Different counts, different questions.</strong> Registered agents identify who may act. Devices show where. Software observations require classification. Blocked task attempts do not mean the agent itself is blocked.</p></div>
    <div className="ae-workspace">
      <div className="ae-tabs" role="tablist" aria-label="AI estate views">{tabs.map(([name,Icon],index)=><button key={name} id={`${groupId}-${index}`} role="tab" aria-selected={tab===name} tabIndex={tab===name?0:-1} aria-controls={`${groupId}-panel`} data-estate-tab={name} onKeyDown={event=>tabKeys(event,index)} onClick={()=>changeTab(name)}><Icon/>{name}<span title={totals[name]===unfilteredTotals[name]?`${totals[name]} records`:`${totals[name]} matching the retained filter, out of ${unfilteredTotals[name]} in this scope`}>{totals[name]===unfilteredTotals[name]?totals[name]:`${totals[name]}/${unfilteredTotals[name]}`}</span></button>)}</div>
      <div className="ae-toolbar"><div><h2>{tab==='Agents'?`${agents.length} accountable agent identities`:tab==='Devices'?`${devices.length} devices in view`:tab==='People'?`${peopleSet.length} named people`:tab==='Discovered software'?`${observations.length} software observations`:`${toolSet.length} company tools`}</h2><p>{department==='All'?'All six teams':department} · {query?`Matching “${query}”`:'Current workspace records'}{tab==='Agents'?' · Ownership, runtime and authority in one card':''}</p></div>{tab==='Agents'&&<label>Agent type<select aria-label="Agent type" value={kind} onChange={event=>{onInteract?.();setKind(event.target.value);}}><option>All</option><option>Team</option><option>Personal</option></select></label>}{tab==='Devices'&&<label>Device ownership<select aria-label="Device ownership" value={ownership} onChange={event=>filterOwnership(event.target.value)}><option>All</option><option>Company-owned</option><option>BYOD</option></select></label>}{tab==='Discovered software'&&<label>Authorization<select aria-label="Software authorization" value={softwareStatus} onChange={event=>filterSoftware(event.target.value)}><option>All</option>{statuses.map(status=><option key={status}>{status}</option>)}</select></label>}</div>
      <div role="tabpanel" id={`${groupId}-panel`} aria-labelledby={`${groupId}-${tabs.findIndex(([name])=>name===tab)}`} tabIndex={0} className="ae-content">
        {tab==='Agents'&&<div className="ae-agent-grid">{agents.slice(0,limit).map(proof=><AgentCard key={proof.agent.id} proof={proof} onInspect={inspect} openDevice={openDevice} openTool={openTool}/>)}</div>}
        {tab==='Devices'&&<>{deviceDetail&&<DeviceDetail device={deviceDetail} estate={estate} scenario={scenario} proofs={proofs} onInspect={inspect} close={()=>{onInteract?.();setSelectedDevice(null);}}/>}<div className="ae-device-grid">{devices.slice(0,limit).map(device=><DeviceCard key={device.id} device={device} scenario={scenario} observations={estate.observations.filter(observation=>observation.deviceId===device.id)} onSelect={()=>{onInteract?.();setSelectedDevice(device.id);}} onInspect={inspect}/>)}</div></>}
        {tab==='People'&&<div className="ae-people-grid">{peopleSet.slice(0,limit).map(person=>{const owned=scenario.agents.filter(agent=>agent.owner===person.id);const devices=estate.devices.filter(device=>device.custodianId===person.id);const exactApprovals=[...scenario.events,...playback.events].filter(event=>event.actor===person.id&&event.operation==='Human approved exact action');return <button className="ae-person-card" key={person.id} onClick={()=>inspect({kind:'human',id:person.id})} data-person-id={person.id}><span className="ae-person-top"><span className="ae-avatar">{initials(person.name)}</span><span className="ae-small-tag">{person.level}</span></span><strong>{person.name}</strong><span className="ae-person-role">{person.role}</span><span className="ae-person-team">{person.department}</span><span className="ae-person-stats"><span><Bot/><b>{owned.length}</b>owned agents</span><span><Laptop/><b>{devices.length}</b>devices</span><span><ClipboardCheck/><b>{exactApprovals.length}</b>exact approvals</span></span><span className="ae-person-foot">Inspect identity & delegated authority<ArrowRight/></span></button>;})}</div>}
        {tab==='Discovered software'&&<><div className="ae-software-boundary"><ShieldQuestion/><span>These observations are evidence of software presence or activity. Their authorization state is separate from the registered agent roster and does not establish device-wide containment.</span></div><div className="ae-observation-grid">{observations.slice(0,limit).map(observation=>{const device=estate.devices.find(device=>device.id===observation.deviceId);return <article className={`ae-observation-card ${statusClass(observation.status)}`} key={observation.id} data-observation-id={observation.id}><header><ProductMark product={observation.product}/><span className={`ae-state ${statusClass(observation.status)}`}>{observation.status}</span></header><h3>{observation.name}</h3><p>{observation.reason}</p><div className="ae-observation-context"><span><Monitor/><strong>{device?.name||observation.deviceId}</strong></span><span><Users/>{device?personName(scenario,device.custodianId):'Custodian not assigned'}</span><span><Search/>{observation.source}</span></div><div className="ae-evidence-boundary"><LockKeyhole/><span>{observation.boundary}</span></div><footer><small>{observation.installationOnly?'Installation evidence only':'Activity / inventory evidence'}</small><button className="ae-link" onClick={()=>inspect({kind:'discovery',id:observation.id})}>Inspect evidence<ArrowRight/></button></footer></article>;})}</div></>}
        {tab==='Tool access'&&<>{toolDetail&&<ToolDetail tool={toolDetail} proofs={proofs.filter(proof=>match(proof.agent.department,`${proof.agent.name} ${proof.agent.department} ${proof.owner.name} ${toolDetail.name}`))} onInspect={inspect} close={()=>{onInteract?.();setSelectedTool(null);}}/>}<div className="ae-tool-grid">{toolSet.map(tool=>{const access=proofs.flatMap(proof=>proof.access.filter(access=>access.toolId===tool.id).map(access=>({access,agent:proof.agent})));const allowed=access.filter(row=>row.access.entitlement==='Mandate-scoped');const observed=allowed.filter(row=>row.access.observedOperations>0);return <article className="ae-tool-card" key={tool.id}><header><ToolMark tool={tool.name}/><span><h3>{tool.name}</h3><small>{tool.department}</small></span><ShieldCheck/></header><span className="ae-permission"><LockKeyhole/>{tool.permission}</span><div className="ae-access-compare"><button onClick={()=>openTool(tool.id)}><span>Allowed by mandate</span><strong>{allowed.length}<small>agents</small></strong><i><b style={{width:`${allowed.length?100:0}%`}}/></i></button><button onClick={()=>openTool(tool.id)}><span>Agents with recorded use</span><strong>{observed.length}<small>agents</small></strong><i className="ae-observed-bar"><b style={{width:`${allowed.length?observed.length/allowed.length*100:0}%`}}/></i></button></div><p>{allowed.reduce((total,row)=>total+row.access.observedOperations,0)} operation records across {observed.length} of {allowed.length} entitled agents. Permission alone is not evidence of execution.</p><div className="ae-denied-line"><LockKeyhole/><span>{tool.denied.join(' · ')}</span></div><button className="ae-tool-foot" onClick={()=>openTool(tool.id)}>Compare mandate with observed use<ArrowRight/></button></article>;})}</div></>}
        {totals[tab]===0&&<div className="ae-empty"><Search/><h3>No matching {tab.toLocaleLowerCase()}</h3><p>Change the department or search above{tab==='Agents'?' and check the agent type filter':tab==='Devices'?' and check device ownership':tab==='Discovered software'?' and check authorization':''}.</p></div>}
        {tab!=='Tool access'&&totals[tab]>0&&<footer className="ae-pagination"><span>Showing {Math.min(limit,totals[tab])} of {totals[tab]} {tab.toLocaleLowerCase()}</span>{totals[tab]>limit&&<button onClick={()=>{onInteract?.();setLimit(value=>value+12);}}>Show 12 more<ChevronRight/></button>}</footer>}
      </div>
    </div>
  </div>;
}

function Donut({shared,personal}:{shared:number;personal:number}){const total=shared+personal;const circumference=2*Math.PI*48;const length=total?shared/total*circumference:0;return <svg className="ae-donut" viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="48" fill="none" stroke="#edf2f9" strokeWidth="11"/>{total>0&&<><circle cx="60" cy="60" r="48" fill="none" stroke="#89b7f2" strokeWidth="11"/><circle cx="60" cy="60" r="48" fill="none" stroke="#1764d8" strokeWidth="11" strokeDasharray={`${length} ${circumference-length}`} transform="rotate(-90 60 60)"/></>}</svg>;}

function AgentCard({proof,onInspect,openDevice,openTool}:{proof:AgentProof;onInspect:(selection:Inspection)=>void;openDevice:(id:string)=>void;openTool:(id:string)=>void}) {
  const access=proof.access.find(access=>access.entitlement==='Mandate-scoped');
  return <article className="ae-agent-card" data-agent-id={proof.agent.id}><header><span className={`ae-agent-symbol ${proof.agent.kind==='Personal'?'ae-personal-symbol':''}`}><Bot/></span><div><span className="ae-small-tag">{proof.agent.kind==='Team'?'Shared team':'Personal'} agent</span><span className="ae-state ae-ok"><Check/>Approved identity</span></div><button className="ae-icon-button" aria-label={`Inspect ${proof.agent.name}`} onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><ArrowRight/></button></header><button className="ae-card-title" onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><h3>{proof.agent.name}</h3><small>{proof.agent.department} · {proof.agent.id}</small></button><div className="ae-runtime"><ProductMark product={proof.agent.runtime} size="small"/><span>{runtimeNames[proof.agent.runtime]}<small>Configured runtime</small></span><span className="ae-hardware-tag">{proof.device.ownership}</span></div><div className="ae-binding"><button onClick={()=>onInspect({kind:'human',id:proof.owner.id})}><span className="ae-avatar">{initials(proof.owner.name)}</span><span><small>Accountable human</small><strong>{proof.owner.name}</strong></span><ChevronRight/></button><button onClick={()=>openDevice(proof.device.id)}><span className="ae-device-icon">{proof.device.kind==='Laptop'?<Laptop/>:<Server/>}</span><span><small>{proof.device.kind}</small><strong>{proof.device.name}</strong></span><ChevronRight/></button></div><div className="ae-agent-stat-row"><button onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><strong>{proof.counts.completedTasks}</strong><span>completed tasks</span></button><button onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><strong>{proof.counts.humanApprovals}</strong><span>human approvals</span></button><button onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><strong>{proof.counts.peerReviews}</strong><span>A2A reviews</span></button></div>{access&&<button className="ae-agent-access" onClick={()=>openTool(access.toolId)}><ToolMark tool={access.toolName}/><span><strong>{access.toolName}</strong><small>{access.permission} · mandate scoped</small></span><ChevronRight/></button>}<footer><span><Fingerprint/>Passport bound</span><button className="ae-link" onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}>Inspect authority<ArrowRight/></button></footer></article>;
}

function DeviceCard({device,scenario,observations,onSelect,onInspect}:{device:Device;scenario:Scenario;observations:Observation[];onSelect:()=>void;onInspect:(selection:Inspection)=>void}){
  return <article className={`ae-device-card ${device.ownership==='BYOD'?'ae-byod-card':''}`} data-device-id={device.id}><header><span className="ae-device-emblem">{device.kind==='Laptop'?<Laptop/>:<Server/>}</span><span className="ae-hardware-tag">{device.ownership}</span></header><button className="ae-card-title" onClick={onSelect}><h3>{device.name}</h3><small>{device.kind} · {device.os}</small></button><button className="ae-device-custodian" onClick={()=>onInspect({kind:'human',id:device.custodianId})}><span className="ae-avatar">{initials(personName(scenario,device.custodianId))}</span><span><small>Device custodian</small><strong>{personName(scenario,device.custodianId)}</strong></span><ChevronRight/></button><div className="ae-device-facts"><span><Bot/><b>{device.agentIds.length}</b>deployed agents</span><span><Search/><b>{observations.length}</b>software observations</span></div><div className="ae-management"><ShieldCheck/><span>{device.management}</span></div><footer><small>{device.department}<span className="ae-device-last-seen">Observed {date(device.lastSeen)}</span></small><button className="ae-link" onClick={onSelect}>Inspect device<ArrowRight/></button></footer></article>;
}

function DeviceDetail({device,estate,scenario,proofs,onInspect,close}:{device:Device;estate:ReturnType<typeof buildEstate>;scenario:Scenario;proofs:AgentProof[];onInspect:(selection:Inspection)=>void;close:()=>void}){
  const agentProofs=proofs.filter(proof=>proof.device.id===device.id);const observations=estate.observations.filter(observation=>observation.deviceId===device.id);
  return <section className="ae-inline-detail" data-testid="estate-device-detail"><header><button className="ae-link" onClick={close}><ArrowLeft/>Back to all devices</button><span className="ae-hardware-tag">{device.ownership}</span></header><div className="ae-detail-identity"><span className="ae-device-emblem">{device.kind==='Laptop'?<Laptop/>:<Server/>}</span><div><h3>{device.name}</h3><p>{device.kind} · {device.os} · {device.department}</p></div></div><div className="ae-device-detail-grid"><div><h4>Human accountability</h4><button className="ae-detail-person" onClick={()=>onInspect({kind:'human',id:device.custodianId})}><span className="ae-avatar">{initials(personName(scenario,device.custodianId))}</span><span><strong>{personName(scenario,device.custodianId)}</strong><small>Device custodian</small></span><ArrowRight/></button><dl><dt>Legal hardware owner</dt><dd>{device.ownerName}</dd><dt>Ownership model</dt><dd>{device.ownership}</dd><dt>Management</dt><dd>{device.management}</dd><dt>Last inventory observation</dt><dd>{date(device.lastSeen)}</dd></dl></div><div><h4>{agentProofs.length} agents deployed here</h4><div className="ae-detail-chips">{agentProofs.map(proof=><button key={proof.agent.id} onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><Bot/><span>{proof.agent.name}<small>{proof.agent.kind} · owner {proof.owner.name}</small></span><ChevronRight/></button>)}</div>{!agentProofs.length&&<p>No registered agent is deployed on this device.</p>}</div><div><h4>Visibility boundary</h4><ul>{device.limits.map(limit=><li key={limit}>{limit}</li>)}</ul>{observations.length>0&&<div className="ae-detail-chips">{observations.map(observation=><button key={observation.id} onClick={()=>onInspect({kind:'discovery',id:observation.id})}><ProductMark product={observation.product} size="small"/><span>{observation.name}<small>{observation.status}</small></span><ChevronRight/></button>)}</div>}</div></div></section>;
}

function ToolDetail({tool,proofs,onInspect,close}:{tool:ReturnType<typeof buildEstate>['tools'][number];proofs:AgentProof[];onInspect:(selection:Inspection)=>void;close:()=>void}){
  const rows=proofs.map(proof=>({proof,access:proof.access.find(access=>access.toolId===tool.id)!})).filter(row=>row.access&&row.access.entitlement==='Mandate-scoped');
  return <section className="ae-inline-detail" data-testid="estate-tool-detail"><header><button className="ae-link" onClick={close}><ArrowLeft/>Back to tool access</button><span className="ae-small-tag">Declared scope ≠ observed activity</span></header><div className="ae-detail-identity"><ToolMark tool={tool.name}/><div><h3>{tool.name}: authority and evidence</h3><p>{tool.permission} · {tool.department}</p></div></div><div className="ae-access-matrix">{rows.map(({proof,access})=><article key={proof.agent.id}><button className="ae-matrix-agent" onClick={()=>onInspect({kind:'agent',id:proof.agent.id})}><Bot/><span><strong>{proof.agent.name}</strong><small>{proof.owner.name}</small></span><ChevronRight/></button><div><span className="ae-eyebrow">ALLOWED</span><strong>{access.permission}</strong><small>{access.scope}</small></div><div><span className="ae-eyebrow">OBSERVED</span><strong>{access.observedOperations} operation records</strong><small>{access.modeledCalls} modeled calls · {access.lastObserved?date(access.lastObserved):'No execution recorded'}</small></div><div><span className="ae-eyebrow">EVIDENCE</span>{access.taskIds.length?<button className="ae-link" onClick={()=>onInspect({kind:'task',id:access.taskIds.at(-1)!})}>Open latest task<ArrowRight/></button>:<small>No task evidence yet</small>}</div></article>)}</div><p className="ae-detail-footnote">A peer review does not grant access to the peer team’s tool. Only this team’s mandate-scoped entries are shown. Operation records, modeled calls and approvals are different measurements.</p></section>;
}
