import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Activity, ArrowLeft, ArrowRight, Bot, Brain, Building2, Check, ChevronRight, ClipboardCheck, Download, Fingerprint, GitBranch, Layers, Menu, Network, Pause, Play, RotateCcw, Search, ShieldCheck, SkipForward, Users, Workflow, X } from 'lucide-react';
import { ProductMark } from '../ProductMark';
import { DEPARTMENTS, DISCOVERIES, STAGES, SIM_VERSION, classifyObservation, advance, allMemories, allTasks, dailySeries, decide, initialPlayback, isTerminal, makeScenario, metrics, personName, toolFor, type Department, type Playback, type Scenario, type SimAgent, type SimEvent, type SimMemory, type SimTask } from './model';
import './simulation.css';
import { CollaborationExplorer } from './CollaborationExplorer';
import { CompanyBrainExplorer } from './CompanyBrainExplorer';
import { HospitalOverviewMetrics, HospitalWorkFlow } from './HospitalOverview';
import { completedTaskOutput } from './outputs';
import { OutputBody } from './OutputBody';
import { AgentEstateExplorer } from './AgentEstateExplorer';
import { OrganizationSummary, TaskStageFlow, DecisionSummary, EvidencePulse } from './CisoVisuals';
import { AgentSecurityDetails, PersonDeviceDetails, DiscoveryDeviceDetails, DiscoveryOverview } from './EstateDetails';
import { buildEstate } from './estate-model';
import { ORGANIZATION_NAME, ORG_CISO_NAME } from './model';
import { SecurityEntry, SecurityPosture } from '../security-posture/SecurityPosture';
import { scenarioPosture } from '../security-posture/model';

const STORAGE='byosync.enterprise-simulation.v2';
type Page='Overview'|'Security posture'|'Organization'|'AI estate'|'Discovery'|'Task pipeline'|'Rooms'|'Company brain'|'Decisions'|'Evidence';
type Selection={kind:'task'|'agent'|'human'|'memory'|'discovery';id:string};
const pages:Array<[Page,typeof Network]>=[['Overview',Activity],['Security posture',ShieldCheck],['Organization',Building2],['AI estate',Bot],['Discovery',Search],['Task pipeline',Layers],['Rooms',Workflow],['Company brain',Brain],['Decisions',ClipboardCheck],['Evidence',GitBranch]];
const number=(n:number)=>n.toLocaleString();
const timestamp=(value:string)=>new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'null');if(raw?.version===SIM_VERSION&&/^\d{4}-\d{2}-\d{2}$/.test(raw.anchor)&&Number.isInteger(raw.tick)&&raw.tick>=0&&Array.isArray(raw.queue)&&raw.queue.length===20&&Array.isArray(raw.events)&&Array.isArray(raw.memories)&&Array.isArray(raw.completed)&&raw.discovery)return raw as Playback;}catch{/* Recover to an isolated fresh scenario. */}return initialPlayback(makeScenario());}
function Badge({value}:{value:string}){return <span className={`sim-badge ${/Blocked|Rejected|High|Restricted/.test(value)?'danger':/approval|review|Unreviewed|Unverified|Sensitive|Proposed/.test(value)?'attention':/Completed|Published|Authorized|Approved|Bound|Active/.test(value)?'good':'neutral'}`}>{value}</span>;}
function Panel({title,sub,action,children,className=''}:{title:string;sub?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`sim-panel ${className}`}><header><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</header>{children}</section>;}
function Metric({label,value,note,icon:Icon=Activity}:{label:string;value:string|number;note:string;icon?:typeof Activity}){return <article className="sim-metric"><span><Icon />{label}</span><strong>{typeof value==='number'?number(value):value}</strong><small>{note}</small></article>;}
function Empty({children}:{children:ReactNode}){return <p className="sim-empty">{children}</p>;}
function download(data:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function EnterpriseSimulation({onExit}:{onExit:()=>void}) {
  const [playback,setPlayback]=useState<Playback>(load);
  const scenario=useMemo(()=>makeScenario(playback.anchor),[playback.anchor]);
  const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState(1200);const [auto,setAuto]=useState(true);
  const [page,setPage]=useState<Page>(()=>new URLSearchParams(window.location.search).get('view')==='security'?'Security posture':'Overview');const [department,setDepartment]=useState<Department|'All'>('All');const [query,setQuery]=useState('');const [selection,setSelection]=useState<Selection|null>(null);const [menu,setMenu]=useState(false);const [notice,setNotice]=useState('');const [reset,setReset]=useState(false);
  const tasks=useMemo(()=>allTasks(scenario,playback),[scenario,playback]);const memories=useMemo(()=>allMemories(scenario,playback),[scenario,playback]);const events=useMemo(()=>[...scenario.events,...playback.events].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)||b.id.localeCompare(a.id)),[scenario,playback]);const totals=metrics(scenario,playback);
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(!document.hidden)setPlayback(p=>advance(scenario,p,auto));},speed);return()=>clearInterval(timer);},[playing,speed,auto,scenario]);
  useEffect(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(playback));}catch{setNotice('Browser storage is full or disabled. Playback works, but this session may not survive reload. Export evidence before leaving.');}},[playback]);
  useEffect(()=>{const pause=()=>{if(document.hidden)setPlaying(false);};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause);},[]);
  const go=(next:Page)=>{setPage(next);setMenu(false);setQuery('');window.scrollTo(0,0);};
  const inspect=(next:Selection)=>{setPlaying(false);setSelection(next);};
  const visible=(value:{department:Department},text:string)=> (department==='All'||value.department===department)&&text.toLowerCase().includes(query.toLowerCase());
  const review=(task:SimTask,approve:boolean)=>{setPlaying(false);setPlayback(p=>decide(scenario,p,task.id,approve));setNotice(approve?'Scenario decision recorded. Continue playback to advance the next stage.':'Scenario rejection recorded. No live system was changed.');};
  const exportEvidence=()=>download({classification:'SYNTHETIC ENTERPRISE SIMULATION — NOT REAL TELEMETRY',company_population:scenario.people.length,detailed_members:scenario.people.filter(p=>p.level==='Member').length,scenario,playback,metrics:totals},'ByoSync-SYNTHETIC-enterprise-evidence.json');
  return <div className="sim-app">
    <a className="skip-link" href="#sim-content">Skip to enterprise workspace</a>
    <aside className={`sim-sidebar ${menu?'open':''}`}>
      <button className="sim-brand" onClick={()=>go('Overview')}><Network/><strong>ByoSync</strong></button><div className="sim-company"><Building2/><span>{ORGANIZATION_NAME}<small>{DEPARTMENTS.length} teams · {scenario.people.length} people · {scenario.agents.length} agents</small></span></div>
      <nav aria-label="Simulation navigation">{pages.map(([name,Icon])=><button key={name} aria-label={name} aria-current={page===name?'page':undefined} onClick={()=>go(name)}><Icon/><span>{name}</span>{name==='Decisions'&&totals.pending>0?<b>{totals.pending}</b>:null}</button>)}</nav>
      <div className="sim-player"><span className="sim-eyebrow">ACTIVITY PLAYBACK</span><button className={`sim-play ${playing?'playing':''}`} onClick={()=>{setPlaying(!playing);setSelection(null);}}>{playing?<Pause/>:<Play/>}{playing?'Pause activity':'Play activity'}</button><div className="sim-player-tools"><button onClick={()=>setPlayback(p=>advance(scenario,p,auto))} disabled={playing} title="Advance one scenario event"><SkipForward/>Step</button><label>Speed<select aria-label="Playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={2400}>0.5×</option><option value={1200}>1×</option><option value={400}>3×</option></select></label></div><label className="sim-auto"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Scripted human decisions</label><small>{auto?'Scenario reviewers approve at their scheduled step.':'Manual mode: held requests require your decision.'}</small><div className="sim-progress"><span>Batch {playback.cycle} · {playback.queue.filter(t=>isTerminal(t.stage)).length}/20 finished</span><progress max={20} value={playback.queue.filter(t=>isTerminal(t.stage)).length}/></div><button className="sim-link" onClick={()=>{setPlaying(false);setReset(true);}}><RotateCcw/>Reset scenario</button></div>
      <div className="hospital-scope-note">Hospital operations · 30-day activity</div>
    </aside>
    <main className="sim-main"><header className="sim-topbar"><button className="sim-menu" aria-label="Open simulation navigation" onClick={()=>setMenu(!menu)}><Menu/></button><div><span className="sim-eyebrow">COMPANY CONTROL CENTER</span><strong>{ORG_CISO_NAME} <small>· Chief information security officer</small></strong></div>{!['Overview','Rooms','Company brain','Security posture'].includes(page)&&<><label className="sim-search"><Search/><input aria-label="Search simulation" placeholder="Search this view…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="sim-team-filter">Department<select aria-label="Department filter" value={department} onChange={e=>setDepartment(e.target.value as Department|'All')}><option>All</option>{DEPARTMENTS.map(d=><option key={d}>{d}</option>)}</select></label></>}<button className="sim-export" onClick={exportEvidence}><Download/>Export</button></header>
      <div className="sim-disclosure compact"><span><b>Simulation environment</b> · {ORGANIZATION_NAME}</span><strong><span className={playing?'sim-live-dot':'sim-paused-dot'}/>{playing?'Playing':'Paused'} · event {playback.tick}</strong></div>
      {notice&&<div className="sim-notice" role="status">{notice}<button aria-label="Dismiss simulation notice" onClick={()=>setNotice('')}><X/></button></div>}
      <div id="sim-content" className="sim-content">{page!=='Security posture'&&<div className="sim-page-title"><div><span className="sim-eyebrow">{page==='Overview'?'30 DAYS OF CONNECTED AI WORK':`ENTERPRISE / ${page.toUpperCase()}`}</span><h1>{({Overview:'Your hospital. Connected and accountable.',Organization:'People give AI its authority.','AI estate':'A workforce of accountable agents.',Discovery:'See what belongs. Investigate what doesn’t.','Task pipeline':'Work moving across the company.',Rooms:'Where teams and agents work together.','Company brain':'Knowledge grows. Repeated work shrinks.',Decisions:'Human judgment at the point of consequence.',Evidence:'One continuous identity and action story.'})[page]}</h1><p>{['Overview','Rooms','Company brain'].includes(page)||department==='All'?'All six departments':department} · 30-day view · Select a team, room or record to investigate.</p></div><Badge value={playing?'Activity playing':'Paused for inspection'}/></div>}
      {page==='Security posture'&&<SecurityPosture data={scenarioPosture(scenario,playback)} open={target=>{setPlaying(false);if(target.kind&&target.id&&['task','agent','memory','discovery'].includes(target.kind))inspect({kind:target.kind as Selection['kind'],id:target.id});else if(target.page)go(({estate:'Organization',discovery:'Discovery',decisions:'Decisions',operations:'Rooms',assurance:'Evidence',trace:'Evidence',administration:'Organization'} as const)[target.page]);}}/>}
      {page==='Overview'&&<>
        <HospitalOverviewMetrics scenario={scenario} playback={playback} go={go} inspect={inspect}/>
        <CollaborationExplorer scenario={scenario} playback={playback} onInspect={inspect} onInteract={()=>setPlaying(false)}/>
        <HospitalWorkFlow scenario={scenario} playback={playback} go={go} inspect={inspect}/>
        <TrendPanels scenario={scenario}/>
        <div className="sim-overview-footer"><SecurityEntry onOpen={()=>go('Security posture')}/></div>
      </>}
      {page==='Organization'&&<Organization scenario={scenario} department={department} query={query} inspect={inspect}/>}
      {page==='AI estate'&&<AgentEstateExplorer scenario={scenario} playback={playback} department={department} query={query} onInspect={inspect} onInteract={()=>setPlaying(false)}/>}
      {page==='Discovery'&&<DiscoveryOverview scenario={scenario} playback={playback} department={department} query={query} onInspect={inspect}/>}
      {page==='Task pipeline'&&<TaskPipeline tasks={tasks} queue={playback.queue} scenario={scenario} visible={visible} inspect={inspect}/>}
      {page==='Rooms'&&<><CollaborationExplorer scenario={scenario} playback={playback} onInspect={inspect} onInteract={()=>setPlaying(false)}/><details className="sim-chart-data"><summary>Browse room work and activity</summary><Rooms tasks={tasks} events={events} memories={memories} scenario={scenario} visible={visible} inspect={inspect}/></details></>}
      {page==='Company brain'&&<CompanyBrainExplorer scenario={scenario} playback={playback} onInspect={inspect} onInteract={()=>setPlaying(false)}/>}
      {page==='Decisions'&&<><DecisionSummary scenario={scenario} playback={playback} inspect={inspect}/><Panel title="Exact-action and memory decisions" sub="Inspect a request, then approve or reject. Approval is not a reusable privilege grant."><div className="sim-decision-grid">{playback.queue.filter(t=>['Awaiting approval','Memory review'].includes(t.stage)&&visible(t,t.title)).map(t=><article key={t.id}><Badge value={t.stage}/><h3>{t.title}</h3><p>{t.department} → {t.peer}</p><p>Accountable: {personName(scenario,t.owner)}</p><button className="sim-primary" onClick={()=>inspect({kind:'task',id:t.id})}>Review exact request<ArrowRight/></button></article>)}</div>{!playback.queue.some(t=>['Awaiting approval','Memory review'].includes(t.stage)&&visible(t,t.title))&&<Empty>No waiting decisions match. Advance the simulation to create the next review.</Empty>}</Panel></>}
      {page==='Evidence'&&<Evidence events={events.filter(e=>visible(e,`${e.operation} ${e.actor} ${e.task} ${e.detail}`))} scenario={scenario} inspect={inspect} exportEvidence={exportEvidence}/>}
      </div>
    </main>
    {selection&&<Inspector selection={selection} scenario={scenario} playback={playback} tasks={tasks} memories={memories} events={events} inspect={inspect} close={()=>setSelection(null)} review={review} classify={(id,status)=>{setPlayback(p=>classifyObservation(scenario,p,id,status));setNotice(`Scenario observation ${status.toLowerCase()}. No endpoint or external account was changed.`);}}/>}
    {reset&&<div className="sim-modal-backdrop"><section className="sim-reset" role="dialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Reset only the enterprise simulation?</h2><p>This replaces playback progress and presenter decisions with the original fictional 30-day scenario. Your real workspace is untouched. Export first if you want to keep this session.</p><button onClick={exportEvidence}><Download/>Export session</button><div><button autoFocus onClick={()=>setReset(false)}>Cancel</button><button className="sim-primary" onClick={()=>{setPlayback(initialPlayback(makeScenario()));setSelection(null);setReset(false);setNotice('Enterprise scenario reset. Real workspace data was not changed.');}}>Reset simulation</button></div></section></div>}
  </div>;
}

function TrendPanels({scenario}:{scenario:Scenario}){const days=dailySeries(scenario);return <><div className="sim-trends"><Panel title="Reviewed memory growth" sub={`${days.at(-1)?.memory} published records across 30 days`}><LineChart values={days.map(d=>d.memory)} label="Published memory" unit="records"/></Panel><Panel title="Tool calls per completed task" sub="Modeled reuse: 8 baseline calls, up to 5 avoided"><LineChart values={days.map(d=>d.baseline?d.calls/(d.baseline/8):0)} label="Tool calls per completed task" unit="calls" color="#0a8176"/></Panel><Panel title="Daily work volume" sub="30-day workload · 10–20 tasks each day"><div className="sim-bars" role="img" aria-label={days.map(d=>`${d.date}: ${d.tasks} tasks`).join('; ')}>{days.map(d=><span key={d.date} title={`${d.date}: ${d.tasks} tasks`} style={{height:`${d.tasks*5}px`}}/>)}</div><div className="sim-axis"><span>Day 1</span><span>0–20 tasks / day</span><span>Day 30</span></div></Panel></div><details className="sim-chart-data"><summary>Chart data and simulation assumptions</summary><p>Calls avoided are a scenario assumption, not measured savings or proof of causality. A completed task has an 8-call baseline; each eligible published memory record avoids one modeled call, up to five. Tasks still make fresh checks. Memory never grants authority.</p><div className="sim-table-scroll"><table><thead><tr><th>Date</th><th>Tasks</th><th>Baseline calls</th><th>Modeled calls</th><th>Published memory</th></tr></thead><tbody>{days.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.tasks}</td><td>{d.baseline}</td><td>{d.calls}</td><td>{d.memory}</td></tr>)}</tbody></table></div></details></>;}
function DepartmentRows({scenario,tasks,memories,department,select}:{scenario:Scenario;tasks:SimTask[];memories:SimMemory[];department:Department|'All';select:(d:Department)=>void}){return <div className="sim-department-rows">{DEPARTMENTS.filter(d=>department==='All'||department===d).map(d=><button key={d} onClick={()=>select(d)}><span className="sim-symbol"><Building2/></span><span><strong>{d}</strong><small>{number(scenario.population[DEPARTMENTS.indexOf(d)])} represented people · 3 detailed members</small></span><span><b>{tasks.filter(t=>t.department===d).length}</b><small>tasks</small></span><span><b>{memories.filter(m=>m.department===d&&m.status==='Published').length}</b><small>memories</small></span><ChevronRight/></button>)}</div>;}
function EventList({events,scenario,inspect}:{events:SimEvent[];scenario:Scenario;inspect:(s:Selection)=>void}){return <ol className="sim-event-list">{events.map(e=><li key={e.id}><span className="sim-event-point"/><button onClick={()=>inspect({kind:e.task.startsWith('DISC-')?'discovery':'task',id:e.task})}><strong>{e.operation}</strong><small>{personName(scenario,e.actor)} · {e.department}</small><time>{timestamp(e.timestamp)} · {e.origin}</time></button><Badge value={e.outcome}/></li>)}</ol>;}

function Organization({scenario,department,query,inspect}:{scenario:Scenario;department:Department|'All';query:string;inspect:(s:Selection)=>void}){return <><OrganizationSummary scenario={scenario} inspect={inspect}/><Panel title="Accountability starts with a person" sub="Select any person to see reporting lines, owned agents, tasks and identity bindings."><div className="sim-executives">{scenario.people.filter(p=>p.level==='C-level').map(p=><button key={p.id} onClick={()=>inspect({kind:'human',id:p.id})}><span className="sim-avatar">{p.name.split(' ').map(n=>n[0]).join('')}</span><strong>{p.name}</strong><small>{p.role}</small><Badge value={'Department executive'}/></button>)}</div><div className="sim-org-grid">{DEPARTMENTS.filter(d=>department==='All'||department===d).map(d=><section className="sim-org-team" key={d}><header><Building2/><h3>{d}</h3><small>{number(scenario.population[DEPARTMENTS.indexOf(d)])} people · 8 agents</small></header>{scenario.people.filter(p=>p.department===d&&`${p.name} ${p.role}`.toLowerCase().includes(query.toLowerCase())).map(p=><button key={p.id} className={`sim-org-person ${p.level==='Member'?'member':''}`} onClick={()=>inspect({kind:'human',id:p.id})}><span className="sim-avatar">{p.name.split(' ').map(n=>n[0]).join('')}</span><span><strong>{p.name}</strong><small>{p.role}</small></span><span className="sim-owned">{scenario.agents.filter(a=>a.owner===p.id).length||'—'}<Bot/></span></button>)}</section>)}</div></Panel></>;}
type Visible=(value:{department:Department},text:string)=>boolean;

function TaskPipeline({tasks,queue,scenario,visible,inspect}:{tasks:SimTask[];queue:SimTask[];scenario:Scenario;visible:Visible;inspect:(s:Selection)=>void}){const [history,setHistory]=useState(false);const [status,setStatus]=useState('All');const [limit,setLimit]=useState(20);const filtered=tasks.filter(t=>visible(t,`${t.title} ${t.id} ${t.stage}`)&&(status==='All'||t.stage===status)).reverse();const columns:Array<[string,string[]]>=[['Ready',['Queued','Identity bound','Mandate checked','Context retrieved']],['Collaborating',['Collaborating']],['Human decisions',['Awaiting approval','Memory review']],['Executing',['Executing']],['Finished',['Completed','Blocked','Rejected']]];return <><TaskStageFlow tasks={queue.filter(t=>visible(t,t.title))} select={stage=>{setStatus(stage);setHistory(true);}}/><div className="sim-view-actions"><button aria-pressed={!history} onClick={()=>setHistory(false)}>Live batch · 20 tasks</button><button aria-pressed={history} onClick={()=>setHistory(true)}>30-day task history</button></div>{!history?<div className="sim-kanban">{columns.map(([name,stages])=><section key={name}><h2>{name}<span>{queue.filter(t=>stages.includes(t.stage)&&visible(t,t.title)).length}</span></h2>{queue.filter(t=>stages.includes(t.stage)&&visible(t,t.title)).map(t=><button className="sim-task-card" key={t.id} onClick={()=>inspect({kind:'task',id:t.id})}><small>{t.id} · {t.department}</small><strong>{t.title}</strong><p>{personName(scenario,t.agent)}</p><Badge value={t.stage}/><div><GitBranch/>{t.department} → {t.peer}</div><span className="sim-card-foot">{t.reused} context reuses · {t.calls} calls</span></button>)}</section>)}</div>:<Panel title="Every task has a trace" sub={`${filtered.length} records match; historical tasks retain their actual scenario dates.`} action={<label>Stage<select aria-label="Task stage" value={status} onChange={e=>{setStatus(e.target.value);setLimit(20);}}><option>All</option>{[...STAGES,'Blocked','Rejected'].map(s=><option key={s}>{s}</option>)}</select></label>}><TaskTable tasks={filtered.slice(0,limit)} scenario={scenario} inspect={inspect}/>{filtered.length>limit&&<button className="sim-more" onClick={()=>setLimit(n=>n+30)}>Show 30 more</button>}</Panel>}</>;}
function TaskTable({tasks,scenario,inspect}:{tasks:SimTask[];scenario:Scenario;inspect:(s:Selection)=>void}){return <div className="sim-table-scroll"><table><thead><tr><th>Task / created</th><th>Agent / team</th><th>State</th><th>Calls / reuse</th><th/></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><button className="sim-link" onClick={()=>inspect({kind:'task',id:t.id})}>{t.title}</button><small>{t.id} · {timestamp(t.created)}</small></td><td>{personName(scenario,t.agent)}<small>{t.department} → {t.peer}</small></td><td><Badge value={t.stage}/></td><td>{t.calls} calls · {t.reused} reused</td><td><button aria-label={`Inspect task ${t.id}`} onClick={()=>inspect({kind:'task',id:t.id})}><ChevronRight/></button></td></tr>)}</tbody></table>{!tasks.length&&<Empty>No tasks match this filter.</Empty>}</div>;}

function Rooms({tasks,events,memories,scenario,visible,inspect}:{tasks:SimTask[];events:SimEvent[];memories:SimMemory[];scenario:Scenario;visible:Visible;inspect:(s:Selection)=>void}){const matching=tasks.filter(t=>visible(t,`${t.department} ${t.peer} ${t.title} ${t.room}`));const roomIds=[...new Set(matching.map(t=>t.room))];const [selected,setSelected]=useState('');const id=roomIds.includes(selected)?selected:roomIds[0];const roomTasks=tasks.filter(t=>t.room===id);const sample=roomTasks[0];const people=[...new Set(roomTasks.flatMap(t=>[t.owner,scenario.agents.find(a=>a.id===t.collaborator)!.owner]))];const agents=[...new Set(roomTasks.flatMap(t=>[t.agent,t.collaborator]))];return <div className="sim-room-layout"><Panel title={`${roomIds.length} collaboration rooms`} sub="Bounded context, explicit participants"><div className="sim-room-list">{roomIds.map(r=>{const t=matching.find(t=>t.room===r)!;return <button aria-pressed={r===id} key={r} onClick={()=>setSelected(r)}><Workflow/><span><strong>{t.department} × {t.peer}</strong><small>{tasks.filter(t=>t.room===r).length} tasks · {memories.filter(m=>m.room===r&&m.status==='Published').length} reviewed records</small></span><ChevronRight/></button>;})}</div></Panel>{sample?<div className="sim-room-detail"><Panel title={`${sample.department} × ${sample.peer}`} sub={`Room ${id} · Restricted to the named teams · Child mandates cannot increase parent authority`}><div className="sim-room-flow"><span><Users/>Human request</span><ArrowRight/><span><Bot/>Bound agents</span><ArrowRight/><span><ShieldCheck/>Scoped handoff</span><ArrowRight/><span><Brain/>Reviewed output</span></div><div className="sim-participants">{people.map(id=><button key={id} onClick={()=>inspect({kind:'human',id})}><span className="sim-avatar">{personName(scenario,id).split(' ').map(w=>w[0]).slice(0,2).join('')}</span><small>{personName(scenario,id)}</small></button>)}{agents.slice(0,8).map(id=><button key={id} onClick={()=>inspect({kind:'agent',id})}><Bot/><small>{personName(scenario,id)}</small></button>)}</div><TaskTable tasks={roomTasks.slice(-5).reverse()} scenario={scenario} inspect={inspect}/></Panel><Panel title="Room activity" sub="A2A handoff, tools, approvals and memory lineage"><EventList events={events.filter(e=>roomTasks.some(t=>t.id===e.task)).slice(0,12)} scenario={scenario} inspect={inspect}/></Panel><Panel title="Reviewed knowledge from this room"><div className="sim-memory-list">{memories.filter(m=>m.room===id&&m.status==='Published').slice(-3).reverse().map(m=><button key={m.id} onClick={()=>inspect({kind:'memory',id:m.id})}><Brain/><span><strong>{m.title}</strong><small>Reviewed by {personName(scenario,m.reviewer)} · v{m.version}</small></span><ChevronRight/></button>)}</div></Panel></div>:<Empty>No rooms match the current filters.</Empty>}</div>;}

function Evidence({events,scenario,inspect,exportEvidence}:{events:SimEvent[];scenario:Scenario;inspect:(s:Selection)=>void;exportEvidence:()=>void}){const [kind,setKind]=useState('All');const [limit,setLimit]=useState(40);const kinds=['All','Identity','Authority','A2A','Human','Memory','Tool','Blocked'];const filtered=events.filter(e=>kind==='All'||(kind==='Identity'?e.operation.includes('binding'):e.operation.toLowerCase().includes(kind.toLowerCase())));return <><EvidencePulse events={events} select={value=>{setKind(value);setLimit(40);}}/><Panel title="Company event ledger" sub={`${number(filtered.length)} matching synthetic records · inspect the task to follow the entire identity path`} action={<button onClick={exportEvidence}><Download/>Export scenario evidence</button>}><div className="sim-view-actions">{kinds.map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setLimit(40);}}>{k}</button>)}</div><div className="sim-table-scroll"><table><thead><tr><th>Time / provenance</th><th>Actor</th><th>Operation</th><th>Authority / scope</th><th>Outcome</th></tr></thead><tbody>{filtered.slice(0,limit).map(e=><tr key={e.id}><td>{timestamp(e.timestamp)}<small>{e.origin}</small></td><td>{personName(scenario,e.actor)}<small>{e.department}</small></td><td><button className="sim-link" onClick={()=>inspect({kind:e.task.startsWith('DISC-')?'discovery':'task',id:e.task})}>{e.operation}</button><small>{e.task}</small></td><td>{e.authority}<small>{e.target}</small></td><td><Badge value={e.outcome}/></td></tr>)}</tbody></table></div>{filtered.length>limit&&<button className="sim-more" onClick={()=>setLimit(n=>n+40)}>Show 40 more events</button>}</Panel></>;}

function Inspector({selection,scenario,playback,tasks,memories,events,inspect,close,review,classify}:{selection:Selection;scenario:Scenario;playback:Playback;tasks:SimTask[];memories:SimMemory[];events:SimEvent[];inspect:(s:Selection)=>void;close:()=>void;review:(t:SimTask,a:boolean)=>void;classify:(id:string,status:'Authorized'|'Contained')=>void}) {
  const ref=useRef<HTMLDivElement>(null);const [confirmed,setConfirmed]=useState(false);
  useEffect(()=>{setConfirmed(false);const before=document.activeElement as HTMLElement;ref.current?.focus();return()=>before?.focus?.();},[selection.id]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, [tabindex="0"], summary');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[close]);
  const task=selection.kind==='task'?tasks.find(t=>t.id===selection.id):undefined;
  const agent=selection.kind==='agent'?scenario.agents.find(a=>a.id===selection.id):task?scenario.agents.find(a=>a.id===task.agent):undefined;
  const human=selection.kind==='human'?scenario.people.find(p=>p.id===selection.id):undefined;
  const memory=selection.kind==='memory'?memories.find(m=>m.id===selection.id):undefined;
  const discovery=selection.kind==='discovery'?DISCOVERIES.find(d=>d.id===selection.id):undefined;
  const observation=discovery?buildEstate(scenario,playback).observations.find(o=>o.id===discovery.id):undefined;
  return <div className="sim-inspector-backdrop" onClick={close}><div className="sim-inspector" ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="sim-inspector-title" onClick={e=>e.stopPropagation()}><header><div><span className="sim-eyebrow">RECORD DETAILS · PLAYBACK PAUSED</span><h2 id="sim-inspector-title">{task?.title||agent?.name||human?.name||memory?.title||discovery?.name||'Record outside retained session window'}</h2><small>{selection.id}</small></div><button aria-label="Close simulation inspector" onClick={close}><X/></button></header><div className="sim-inspector-body">
    {task&&agent&&<><div className="sim-detail-tags"><Badge value={task.stage}/><Badge value={task.risk}/><span>{task.department} → {task.peer}</span></div><Panel title="Identity travels with the work" sub="The originating human remains accountable across the A2A boundary."><div className="sim-identity-path">{[{label:'Human',value:personName(scenario,task.owner),icon:Users,click:()=>inspect({kind:'human',id:task.owner})},{label:'Agent',value:agent.name,icon:Bot,click:()=>inspect({kind:'agent',id:agent.id})},{label:'Passport',value:agent.passport,icon:Fingerprint},{label:'Mandate',value:agent.mandate,icon:ShieldCheck},{label:'A2A receiver',value:personName(scenario,task.collaborator),icon:GitBranch,click:()=>inspect({kind:'agent',id:task.collaborator})}].map((n,i)=><div key={n.label}>{i>0&&<ArrowRight/>}<button disabled={!n.click} onClick={n.click}><n.icon/><small>{n.label}</small><strong>{n.value}</strong></button></div>)}</div><p className="sim-rule">Child authority: review a scoped draft only. No permission escalation or onward delegation. Receiver keeps its own identity and accountable owner.</p></Panel><div className="sim-detail-grid"><Fact label="Room" value={task.room}/><Fact label="Accountable owner" value={personName(scenario,task.owner)}/><Fact label="Tool boundary" value={toolFor(task.department)}/><Fact label="Memory eligibility" value="Published + allowed team only"/><Fact label="Modeled tool calls" value={`${task.calls} calls / ${task.baseline} baseline`}/><Fact label="Reviewed context reused" value={`${task.reused} records`}/></div>
      {['Awaiting approval','Memory review'].includes(task.stage)&&!task.historical&&<Panel title={task.stage==='Memory review'?'Review proposed company memory':'Decide this exact action'} sub={`Reviewer: ${personName(scenario,task.stage==='Memory review'?(memories.find(m=>m.task===task.id)?.reviewer||task.owner):task.owner)}. Decisions are recorded against this exact request.`}><p>{task.stage==='Memory review'?memories.find(m=>m.task===task.id)?.content:`Authorize ${task.title} using ${toolFor(task.department)} in ${task.room}; no external export or production mutation.`}</p><label className="sim-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this scenario request, scope and accountable owner.</label><div className="sim-review-actions"><button className="sim-primary" disabled={!confirmed} onClick={()=>{review(task,true);setConfirmed(false);}}><Check/>{task.stage==='Memory review'?'Publish reviewed memory':'Approve exact action'}</button><button onClick={()=>review(task,false)}><X/>Reject</button></div></Panel>}
      {task.result&&<Panel title="Outcome / proposed deliverable"><p>{task.result}</p><small>Operational sample · traceable to this task.</small><button className="sim-link" onClick={()=>download({synthetic:true,task,evidence:events.filter(e=>e.task===task.id)},`${task.id}-SIMULATED-result.json`)}><Download/>Download task and evidence</button></Panel>}
      {task.stage==='Completed'&&<CompletedOutput scenario={scenario} task={task}/>}
      <Panel title="Task timeline" sub="Chronological events; inspect the full detail behind each step."><ol className="sim-task-timeline">{events.filter(e=>e.task===task.id).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).map(e=><li key={e.id}><span/><div><strong>{e.operation}</strong><small>{timestamp(e.timestamp)} · {personName(scenario,e.actor)} · {e.origin}</small><p>{e.detail}</p><code>{e.id}</code></div></li>)}</ol></Panel>
      <Panel title="Context and resulting knowledge"><div className="sim-memory-list">{memories.filter(m=>task.memoryIds.includes(m.id)||m.task===task.id).map(m=><button key={m.id} onClick={()=>inspect({kind:'memory',id:m.id})}><Brain/><span><strong>{m.title}</strong><small>{m.task===task.id?'Produced by this task':'Reused context'} · {m.status}</small></span><ChevronRight/></button>)}</div></Panel></>}
    {selection.kind==='agent'&&agent&&<><AgentSecurityDetails scenario={scenario} playback={playback} id={agent.id} onInspect={inspect}/><Panel title="Agent task history" sub="Originated work and scoped cross-team collaboration"><TaskTable tasks={tasks.filter(t=>t.agent===agent.id||t.collaborator===agent.id).slice(-12).reverse()} scenario={scenario} inspect={inspect}/></Panel></>}
    {human&&<><PersonDeviceDetails scenario={scenario} playback={playback} id={human.id} onInspect={inspect}/><div className="sim-detail-grid"><Fact label="Role" value={human.role}/><Fact label="Reports to" value={human.manager?personName(scenario,human.manager):'Board / executive sponsor'}/><Fact label="Department" value={human.department}/><Fact label="Identity assurance" value="Fictional scenario identity — not authenticated"/></div>{human.manager&&<button className="sim-link" onClick={()=>inspect({kind:'human',id:human.manager!})}>View reporting manager<ArrowRight/></button>}<Panel title="Agents bound to this person"><div className="sim-memory-list">{scenario.agents.filter(a=>a.owner===human.id).map(a=><button key={a.id} onClick={()=>inspect({kind:'agent',id:a.id})}><Bot/><span><strong>{a.name}</strong><small>{a.kind} · {a.passport} · {a.mandate}</small></span><ChevronRight/></button>)}</div>{!scenario.agents.some(a=>a.owner===human.id)&&<Empty>This leadership identity oversees people; it does not own a task agent in this cohort.</Empty>}</Panel><Panel title="Direct reports"><div className="sim-memory-list">{scenario.people.filter(p=>p.manager===human.id).map(p=><button key={p.id} onClick={()=>inspect({kind:'human',id:p.id})}><Users/><span><strong>{p.name}</strong><small>{p.role}</small></span><ChevronRight/></button>)}</div></Panel><Panel title="Accountable work"><TaskTable tasks={tasks.filter(t=>t.owner===human.id).slice(-10).reverse()} scenario={scenario} inspect={inspect}/></Panel></>}
    {memory&&<><Badge value={memory.status}/><Panel title="Reusable knowledge"><p>{memory.content}</p></Panel><div className="sim-detail-grid"><Fact label="Allowed teams" value={memory.allowedTeams.join(' + ')}/><Fact label="Reviewer" value={personName(scenario,memory.reviewer)}/><Fact label="Version" value={`v${memory.version}`}/><Fact label="Created" value={timestamp(memory.created)}/><Fact label="Source room" value={memory.room}/><Fact label="Context eligibility" value={memory.status==='Published'?'Eligible only within allowed teams':'Excluded from future context'}/></div><button className="sim-primary" onClick={()=>inspect({kind:'task',id:memory.task})}>Inspect source task and review<ArrowRight/></button><Panel title="Where this knowledge was reused"><TaskTable tasks={tasks.filter(t=>t.memoryIds.includes(memory.id)).slice(-12).reverse()} scenario={scenario} inspect={inspect}/></Panel></>}
    {discovery&&<><DiscoveryDeviceDetails scenario={scenario} playback={playback} id={discovery.id} onInspect={inspect}/><div className="sim-agent-heading"><ProductMark product={discovery.product}/><Badge value={observation?.status||'Unverified'}/><Badge value={discovery.risk}/></div><div className="sim-detail-grid"><Fact label="Department" value={discovery.department}/><Fact label="Evidence source" value={discovery.source}/><Fact label="Observation" value={discovery.reason}/><Fact label="Provenance" value="Fictional discovery fixture"/></div><Panel title="What the CISO can decide"><p>Review the device, accountable owner and data boundary before approving use or setting a policy restriction. A blocked-use record is not proof that a process was terminated.</p><p>Responsible owner: {personName(scenario,`H-${DEPARTMENTS.indexOf(discovery.department)}-2`)}</p><div className="sim-review-actions"><button className="sim-primary" onClick={()=>classify(discovery.id,'Authorized')}>Authorize in scenario</button><button onClick={()=>classify(discovery.id,'Contained')}>Contain in scenario</button></div></Panel><p className="sim-rule">An installed tool is not proof of active AI use. An unknown tool is not automatically malicious. Missing heartbeat means visibility is incomplete.</p></>}
    {!task&&!agent&&!human&&!memory&&!discovery&&<Empty>Historical fixtures remain available. Older live batches are retained only within the bounded session window; use exported evidence for a longer presentation archive.</Empty>}
  </div></div></div>;
}
function Fact({label,value}:{label:string;value:string}){return <div className="sim-fact"><small>{label}</small><strong>{value}</strong></div>;}

function LineChart({values,label,unit,color='#176ad7'}:{values:number[];label:string;unit:string;color?:string}){
  const max=Math.max(1,...values);const points=values.map((v,i)=>`${15+i*330/Math.max(1,values.length-1)},${115-v/max*92}`).join(' ');
  return <div className="hospital-line-chart"><svg viewBox="0 0 360 138" role="img" aria-label={`${label}: ${values[0]?.toFixed(1)} to ${values.at(-1)?.toFixed(1)} ${unit} over 30 days`}><line x1="15" y1="115" x2="345" y2="115" stroke="#dfe8f2"/><line x1="15" y1="69" x2="345" y2="69" stroke="#edf2f7"/><polyline points={points} fill="none" stroke={color} strokeWidth="2.5"/>{values.map((v,i)=><circle key={i} cx={15+i*330/Math.max(1,values.length-1)} cy={115-v/max*92} r="3" fill={color}><title>Day {i+1}: {v.toFixed(1)} {unit}</title></circle>)}<text x="15" y="134" fontSize="10" fill="#536b84">Day 1</text><text x="345" y="134" textAnchor="end" fontSize="10" fill="#536b84">Day 30</text><text x="15" y="12" fontSize="11" fill="#536b84">0–{max.toFixed(1)} {unit}</text></svg></div>;
}


function CompletedOutput({scenario,task}:{scenario:Scenario;task:SimTask}) {
  const output=completedTaskOutput(scenario,task);if(!output)return null;
  const save=()=>{const url=URL.createObjectURL(new Blob([output.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=output.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <Panel title="Completed task deliverable" sub="Operational sample output · no patient data" action={<button onClick={save}><Download/>Download deliverable</button>}><div className="hospital-output"><h3>{output.title}</h3>{output.sections.map(section=><section key={section.heading}><h4>{section.heading}</h4><OutputBody body={section.body}/></section>)}</div></Panel>;
}
