import { ArrowRight, Bot, Brain, Building2, CircleAlert, ClipboardCheck, ShieldCheck, Users, Workflow } from 'lucide-react';
import { DEPARTMENTS, allTasks, allMemories, isTerminal, type Scenario, type Playback, type SimTask } from './model';
import './hospital-overview.css';
import { PrivateText } from '../privacy/Privacy';

type Props={scenario:Scenario;playback:Playback;go:(page:'Organization'|'AI estate'|'Decisions'|'Task pipeline'|'Company brain'|'Security posture'|'Rooms')=>void;inspect:(value:{kind:'task';id:string})=>void};
export function HospitalOverviewMetrics({scenario,playback,go}:Props){
  const rooms=new Set(allTasks(scenario,playback).map(t=>t.room));const waiting=playback.queue.filter(t=>['Awaiting approval','Memory review'].includes(t.stage));
  const items=[{label:'Hospital workforce',value:scenario.people.length,detail:'6 teams · 7 people per team',Icon:Users,to:'Organization' as const,tone:'blue'},{label:'Accountable agents',value:scenario.agents.length,detail:'30 team agents + 18 personal',Icon:Bot,to:'AI estate' as const,tone:'blue'},{label:'Collaboration rooms',value:rooms.size,detail:'Shared work with named owners',Icon:Workflow,to:'Rooms' as const,tone:'blue'},{label:'Waiting for a human',value:waiting.length,detail:'Action and memory approvals',Icon:CircleAlert,to:'Decisions' as const,tone:'amber'},{label:'Reviewed knowledge',value:allMemories(scenario,playback).filter(m=>m.status==='Published').length,detail:'Attributed, team-scoped records',Icon:Brain,to:'Company brain' as const,tone:'green'},{label:'Restricted attempts',value:allTasks(scenario,playback).filter(t=>t.stage==='Blocked').length,detail:'Policy blocks · retained history',Icon:ShieldCheck,to:'Task pipeline' as const,tone:'red'}];
  return <div className="hospital-kpis" aria-label="Hospital overview metrics">{items.map(m=><button key={m.label} className={`hospital-kpi ${m.tone}`} onClick={()=>go(m.to)}><span><m.Icon size={17}/>{m.label}</span><strong>{m.value.toLocaleString('en-IN')}</strong><small>{m.detail}</small></button>)}</div>;
}
export function HospitalWorkFlow({scenario,playback,go,inspect}:Props){
  const tasks=allTasks(scenario,playback);const stages=[{name:'Completed',tone:'green',items:tasks.filter(t=>t.stage==='Completed')},{name:'In progress',tone:'blue',items:tasks.filter(t=>!isTerminal(t.stage)&&!['Awaiting approval','Memory review'].includes(t.stage))},{name:'Awaiting review',tone:'amber',items:tasks.filter(t=>['Awaiting approval','Memory review'].includes(t.stage))},{name:'Blocked / rejected',tone:'red',items:tasks.filter(t=>['Blocked','Rejected'].includes(t.stage))}];
  const latest=tasks.filter(t=>t.stage==='Completed').sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,3);
  return <div className="hospital-work-grid"><section className="hospital-work-panel"><header><div><span className="hospital-eyebrow">WORK & AUTHORITY</span><h2>From a request to a reviewed outcome</h2></div><button onClick={()=>go('Task pipeline')}>All work<ArrowRight size={15}/></button></header><div className="hospital-flow"><div className="hospital-flow-teams">{DEPARTMENTS.map(d=><div key={d}><Building2 size={16}/><span>{d}</span><b>{tasks.filter(t=>t.department===d).length}</b></div>)}</div><div className="hospital-flow-control"><ShieldCheck/><strong>Identity + mandate</strong><small>Policy & human decision</small><span>{tasks.length} task records</span></div><div className="hospital-flow-outcomes">{stages.map(s=><button key={s.name} className={s.tone} onClick={()=>go(s.name==='Awaiting review'?'Decisions':'Task pipeline')}><span>{s.name}</span><b>{s.items.length}</b><div style={{width:`${Math.max(2,s.items.length/Math.max(tasks.length,1)*100)}%`}}/></button>)}</div></div><footer>30-day history + retained playback. Every task appears in exactly one outcome group.</footer></section><section className="hospital-work-panel"><header><div><span className="hospital-eyebrow">DELIVERED WORK</span><h2>Inspect the finished output</h2></div><ClipboardCheck size={19}/></header><div className="hospital-deliverables">{latest.map(t=><button key={t.id} onClick={()=>inspect({kind:'task',id:t.id})}><span className="hospital-file"><ClipboardCheck size={19}/></span><span><strong><PrivateText value={t.title}/></strong><small>{t.department} → {t.peer}</small><em>Completed · Open deliverable</em></span><ArrowRight size={16}/></button>)}</div><footer>Operational sample outputs, linked to their source task and review trail.</footer></section></div>;
}
