import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { createServer } from 'node:net';
import { join } from 'node:path';
import { buildByoSync } from '../scripts/build-byosync.mjs';
import { root, h2a, census, pythonRuntime, waitFor, stopChild } from '../scripts/runtime.mjs';
import { censusTestSources } from './helpers/census-test-sources.mjs';

async function freePort() {
  const server = createServer();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const port = server.address().port;
  await new Promise(resolve => server.close(resolve));
  return port;
}

test('complete ByoSync lifecycle across real HTTP, both repositories, and process restarts', { timeout: 180000 }, async t => {
  await buildByoSync();
  const data = join(root, '.test-artifacts', `lifecycle-${randomUUID()}`);
  await mkdir(data, { recursive: true });
  const port = await freePort(), bridgePort = await freePort();
  const token = randomBytes(32).toString('hex');
  const url = `http://127.0.0.1:${port}`;
  const python = pythonRuntime();
  const peers = await censusTestSources();
  const env = { ...python.env, ...peers.env, BYOSYNC_ENDPOINT_DISCOVERY: '0', PORT: String(port), GOVERNANCE_BRIDGE_TOKEN: token, CENSUS_API_TOKEN: token, CENSUS_API_URL: `http://127.0.0.1:${bridgePort}`, BYOSYNC_DATA_DIR: join(data, 'byosync') };
  let api, bridge, logs = '';
  const launch = (command, args, cwd) => {
    const child = spawn(command, args, { cwd, env, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
    child.stdout.on('data', x => logs += x); child.stderr.on('data', x => logs += x);
    return child;
  };
  async function start() {
    bridge = launch(python.command, ['scripts/governance_bridge.py', '--port', String(bridgePort), '--data-dir', join(data, 'census')], census);
    await waitFor(`http://127.0.0.1:${bridgePort}/health`, bridge);
    api = launch(process.execPath, [join(h2a, '.governance-dist/server.mjs')], h2a);
    try { await waitFor(`${url}/api/state`, api); } catch (error) { throw new Error(`${error.message}\n${logs}`); }
  }
  async function stop() { await Promise.all([stopChild(api), stopChild(bridge)]); }
  async function request(path, body, expected = 200) {
    const response = await fetch(url + path, body === undefined ? {} : { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    const value = await response.json();
    assert.equal(response.status, expected, `${path}: ${JSON.stringify(value)}`);
    return value;
  }
  async function bad(path, body) {
    const response = await fetch(url + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    assert.ok(response.status >= 400 && response.status < 500, `${path} unexpectedly returned ${response.status}`);
  }
  t.after(async () => { await stop(); await peers.close(); await writeFile(join(data, 'service.log'), logs); });
  await start();
  let state = await request('/api/state');
  assert.equal(state.humans.find(h => h.human_id === 'HUM-LOCAL-OPERATOR').name, 'Local security operator');
  assert.equal(state.agents.length, 0, 'Census evidence must not auto-import into H2A');
  await peers.ingest(`http://127.0.0.1:${bridgePort}`, token);
  const hitsBefore = peers.requests.length;
  const scan = await request('/api/discovery/scan', {});
  assert.ok(peers.requests.length > hitsBefore, 'SCAN must contact configured sources');
  const discovered = scan.agents.find(a => a.name === 'Marketing Research Agent');
  assert.ok(discovered, 'real Census scan must return the test peer');
  assert.equal(discovered.classification.is_agent, true); assert.equal(discovered.shadow, true);
  assert.ok(scan.errors.some(e => e.source === 'a2a'), 'partial source failure must remain visible');
  assert.ok(scan.agents.some(a => a.classification.entity_type === 'mcp_server'));
  assert.ok(scan.agents.some(a => !a.classification.is_agent));
  assert.equal((await request('/api/state')).agents.length, 0);
  const censusId = discovered.agent_id;
  const nonAgent = scan.agents.find(a => !a.classification.is_agent);
  await bad('/api/discovery/import', { census_agent_id: nonAgent.agent_id, scan_id: scan.scan_id });
  state = await request('/api/discovery/import', { census_agent_id: censusId, scan_id: scan.scan_id });
  const agent = state.agents.find(a => a.census_agent_id === censusId);
  const id = agent.agent_id;
  assert.match(id, /^H2A-AGENT-/); assert.notEqual(id, censusId);
  assert.deepEqual(agent.discovery_snapshot, discovered, 'full Census evidence must be preserved losslessly');
  const agentPath = `/api/agents/${id}`;
  const getAgent = () => state.agents.find(a => a.agent_id === id);
  assert.equal(agent.framework, 'CrewAI');
  assert.equal(agent.discovery_status, 'discovered');
  assert.equal(agent.status, 'Registered');
  assert.equal(agent.owner, null); assert.equal(agent.passport, null); assert.equal(agent.mandate, null);
  const discoveredCount = state.agents.length;
  state = await request('/api/discovery/import', { census_agent_id: censusId, scan_id: scan.scan_id });
  assert.equal(state.agents.length, discoveredCount, 'repeated import must not allocate another H2A identity');
  await bad('/api/agents/AGT-missing/passport', {});
  await bad(agentPath + '/passport', {});
  await bad(agentPath + '/bind', { human_id: 'HUM-missing' });
  state = await request(agentPath + '/bind', { human_id: 'HUM-LOCAL-OPERATOR' });
  const binding = state.bindings.find(b => b.agent_id === id);
  assert.equal(binding.human_id, 'HUM-LOCAL-OPERATOR'); assert.equal(binding.relationship, 'owner'); assert.equal(binding.status, 'active');
  await stop(); await start(); state = await request('/api/state');
  assert.equal(getAgent().binding.binding_id, binding.binding_id);
  assert.equal(getAgent().owner.name, 'Local security operator');
  state = await request(agentPath + '/passport', {});
  const passport = getAgent().passport;
  assert.equal(passport.agent_id, id); assert.equal(passport.binding_id, binding.binding_id); assert.equal(passport.owner_human_id, 'HUM-LOCAL-OPERATOR');
  assert.ok(passport.passport_signature.startsWith('ed25519:')); assert.equal(getAgent().status, 'Managed');
  assert.deepEqual(await request(agentPath + '/passport'), passport, 'standalone passport API must retrieve the persisted credential');
  await stop(); await start(); state = await request('/api/state');
  assert.equal(getAgent().passport.passport_id, passport.passport_id); assert.equal(getAgent().status, 'Managed');
  state = await request(agentPath + '/mandate', {});
  const mandate = getAgent().mandate;
  assert.equal(mandate.agent_id, id); assert.deepEqual(mandate.approval_required_actions, ['evidence_export']);
  await stop(); await start(); state = await request('/api/state');
  assert.equal(getAgent().mandate.mandate_id, mandate.mandate_id);
  state = await request('/api/rooms', { agent_id: id, name: 'Security governance room' });
  const room = state.rooms.find(r => r.name === 'Security governance room');
  assert.ok(room.human_ids.includes('HUM-LOCAL-OPERATOR')); assert.ok(room.agent_ids.includes(id));
  assert.equal(room.agent_ids.length, 1, 'Rooms must not invent or auto-import a supporting agent');
  await stop(); await start(); state = await request('/api/state');
  assert.deepEqual(state.rooms.find(r => r.room_id === room.room_id), room);
  state = await request(`/api/rooms/${room.room_id}/work`, { agent_id: id, title: 'Review AI access boundary', objective: 'Inspect the active authority and produce an evidence-backed recommendation.', risk: 'sensitive', priority: 3 });
  const work = state.collaboration.assignments.find(item => item.room_id === room.room_id);
  assert.ok(work); assert.equal(work.assigneeId, id); assert.equal(work.mandateId, mandate.mandate_id); assert.equal(work.status, 'queued');
  state = await request(`/api/work/${work.id}/status`, { status: 'active' });
  assert.equal(state.collaboration.assignments.find(item => item.id === work.id).status, 'active');
  state = await request(`/api/work/${work.id}/response`, { agent_id: id, body: 'Authority reviewed under the assigned Passport and mandate.' });
  assert.equal(state.collaboration.assignments.find(item => item.id === work.id).responseCount, 1);
  await stop(); await start(); state = await request('/api/state');
  assert.equal(state.collaboration.assignments.find(item => item.id === work.id).room_id, room.room_id, 'Room-linked collaboration must survive restart');
  const actionsPath = `/api/rooms/${room.room_id}/actions`;
  state = await request(actionsPath, { agent_id: id, action: 'inventory_report', idempotency_key: 'report-once' });
  const research = state.actions.find(a => a.agent_id === id && a.action === 'inventory_report');
  assert.equal(research.decision, 'ALLOWED'); assert.equal(research.status, 'executed'); assert.equal(research.execution_count, 1); assert.equal(research.result.details.registered_agents, 1);
  const replay = await fetch(url + actionsPath, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agent_id: id, action: 'inventory_report', idempotency_key: 'report-once' }) });
  assert.ok([200, 409].includes(replay.status));
  state = await request('/api/state');
  assert.equal(state.actions.filter(a => a.action === 'inventory_report').reduce((sum, a) => sum + a.execution_count, 0), 1);
  state = await request(actionsPath, { agent_id: id, action: 'crm_write' });
  assert.equal(state.actions.find(a => a.action === 'crm_write').decision, 'DENIED');
  assert.equal(state.actions.find(a => a.action === 'crm_write').execution_count, 0);
  state = await request(actionsPath, { agent_id: id, action: 'purchase' });
  assert.equal(state.actions.find(a => a.action === 'purchase').status, 'denied');
  await bad(actionsPath, { agent_id: id, action: 'invented_unsafe_action' });
  state = await request(actionsPath, { agent_id: id, action: 'evidence_export' });
  let approval = state.approvals.find(a => a.status === 'pending');
  assert.ok(approval);
  assert.equal(state.actions.find(a => a.action_id === approval.action_id).execution_count, 0);
  await stop(); await start(); state = await request('/api/state');
  assert.equal(state.approvals.find(a => a.approval_id === approval.approval_id).status, 'pending');
  state = await request(`/api/approvals/${approval.approval_id}/decision`, { decision: 'reject' });
  assert.equal(state.approvals.find(a => a.approval_id === approval.approval_id).status, 'rejected');
  assert.equal(state.actions.find(a => a.action_id === approval.action_id).execution_count, 0);
  await bad(`/api/approvals/${approval.approval_id}/decision`, { decision: 'approve' });
  state = await request(actionsPath, { agent_id: id, action: 'evidence_export' });
  approval = state.approvals.find(a => a.status === 'pending');
  state = await request(`/api/approvals/${approval.approval_id}/decision`, { decision: 'approve' });
  assert.equal(state.approvals.find(a => a.approval_id === approval.approval_id).status, 'approved');
  const share = state.actions.find(a => a.action_id === approval.action_id);
  assert.equal(share.status, 'executed'); assert.equal(share.execution_count, 1); assert.ok(share.result.artifact);
  state = await request(`/api/approvals/${approval.approval_id}/decision`, { decision: 'approve' });
  assert.equal(state.actions.find(a => a.action_id === share.action_id).execution_count, 1, 'Approval retry must not execute twice');
  state = await request(actionsPath, { agent_id: id, action: 'evidence_export' });
  assert.equal(state.approvals.filter(a => a.status === 'pending').length, 1, 'Approve Once must not amend policy');
  await stop(); await start(); state = await request('/api/state');
  assert.equal(state.actions.find(a => a.action_id === share.action_id).execution_count, 1);
  const memoryPath = `/api/rooms/${room.room_id}/memories`;
  state = await request(memoryPath, { agent_id: id, title: 'AI estate governance record' });
  const memory = state.memories.at(-1);
  assert.equal(memory.status, 'proposed'); assert.equal(memory.reviewed_by, undefined);
  assert.equal(memory.source_action_id, share.action_id, 'Memory must cite the latest completed governed action'); assert.ok(memory.sources.length > 0);
  await stop(); await start(); state = await request('/api/state');
  assert.equal(state.memories.find(m => m.memory_id === memory.memory_id).status, 'proposed');
  state = await request(`/api/memories/${memory.memory_id}/review`, { decision: 'approve', content: 'Reviewed: the current AI estate report is accepted.', note: 'Evidence checked by the security operator.' });
  const published = state.memories.find(m => m.memory_id === memory.memory_id);
  assert.equal(published.status, 'published'); assert.equal(published.reviewed_by, 'HUM-LOCAL-OPERATOR'); assert.ok(published.reviewed_at);
  assert.equal(published.content, 'Reviewed: the current AI estate report is accepted.'); assert.notEqual(published.content_hash, memory.content_hash);
  assert.equal(published.created_by_agent, id); assert.equal(published.passport_id, passport.passport_id); assert.equal(published.mandate_id, mandate.mandate_id); assert.equal(published.room_id, room.room_id);
  await bad(`/api/memories/${memory.memory_id}/review`, { decision: 'approve' });
  state = await request(memoryPath, { agent_id: id, title: 'Rejected governance proposal' });
  const rejectedMemory = state.memories.at(-1);
  state = await request(`/api/memories/${rejectedMemory.memory_id}/review`, { decision: 'reject' });
  assert.equal(state.memories.find(m => m.memory_id === rejectedMemory.memory_id).status, 'rejected');
  await stop(); await start(); state = await request('/api/state');
  assert.deepEqual(state.memories.find(m => m.memory_id === memory.memory_id), published);
  const trace = await request(agentPath + '/trace');
  assert.ok(trace.length >= 14); assert.ok(trace.every(e => e.agent_id === id));
  const types = new Set(trace.map(e => e.event_type));
  for (const group of [['AGENT_REGISTERED_IN_H2A'], ['HUMAN_BOUND', 'AGENT_HUMAN_BOUND', 'AGENT_BOUND'], ['PASSPORT_ISSUED', 'AGENT_PASSPORT_ISSUED'], ['MANDATE_ASSIGNED', 'MANDATE_CREATED'], ['ROOM_JOINED', 'AGENT_JOINED_ROOM'], ['ACTION_EXECUTED'], ['HUMAN_APPROVAL_REQUIRED', 'APPROVAL_REQUESTED'], ['HUMAN_APPROVED', 'APPROVAL_GRANTED'], ['MEMORY_PROPOSED'], ['MEMORY_REVIEWED'], ['MEMORY_PUBLISHED']]) assert.ok(group.some(type => types.has(type)), `Missing event: ${group.join(' or ')}`);
  assert.equal(state.integrity.status, 'verified');
  const censusResponse = await fetch(`http://127.0.0.1:${bridgePort}/agents`, { headers: { Authorization: `Bearer ${token}` } });
  assert.equal(censusResponse.status, 200);
  const censusAgent = (await censusResponse.json()).find(a => a.agent_id === censusId);
  assert.ok(censusAgent); assert.equal(censusAgent.registered, false); assert.equal(censusAgent.shadow, true, 'H2A governance must not rewrite Census classification');
  assert.deepEqual(getAgent().discovery_snapshot, discovered, 'governance must not modify the imported discovery evidence');
  const laterScan = await request('/api/discovery/scan', {});
  const stale = laterScan.agents.find(a => a.agent_id === censusId);
  assert.equal(stale.activity_status, 'stale', 'stale agents must remain in a fresh scan result');
  state = await request('/api/discovery/import', { census_agent_id: censusId, scan_id: laterScan.scan_id });
  assert.equal(state.agents.filter(a => a.census_agent_id === censusId).length, 1);
  assert.equal(getAgent().agent_id, id);
  for (const object of [binding, passport, mandate, research, share, approval, published]) assert.equal(object.agent_id, id);
  assert.equal(state.collaboration.assignments.find(item => item.id === work.id).assigneeId, id);
  assert.ok(trace.every(e => e.event_id && e.timestamp && e.actor_type && e.actor_id && e.event_hash));
  assert.ok(trace.some(e => e.room_id === room.room_id && e.approval_id === approval.approval_id));
  await request('/api/telemetry/ingest', { trace_id: 'TRACE-RUNTIME-001', source: 'claw-orchestrator', kind: 'tool_call', agent_id: id, system: 'evidence-service', operation: 'read-governance-bundle', outcome: 'succeeded', risk: 'low', evidence: { tool: 'evidence.read', duration_ms: 18 } });
  await request('/api/adapters/claw-hunter', { mdm_metadata: { hostname: 'ciso-demo-laptop', serial_number: 'TEST', timestamp: new Date().toISOString(), script_version: '3.0' }, security_summary: { risk_level: 'warning', critical_issues: 1, warnings: 1, info_items: 2 }, platform: 'windows', cli_installed: true, cli_version: '1.2.3', gateway_running: true, gateway_token_set: false, gateway_bind_to_all: false, risk_shell_access_enabled: true, risk_filesystem_write_enabled: false, secrets_found: false, secrets_count: 0, agents_configured: 1, integrations_count: 1 });
  let platformStatus = await request('/api/platform/status');
  assert.equal(platformStatus.authority.integrity, 'verified');
  assert.equal(platformStatus.intake.telemetry_events, 1);
  assert.equal(platformStatus.intake.source_reports, 1);
  let identityTrace = await request(agentPath + '/identity-trace');
  assert.ok(identityTrace.some(item => item.lane === 'runtime' && item.record.trace_id === 'TRACE-RUNTIME-001'));
  assert.ok(identityTrace.some(item => item.lane === 'authority' && item.record.event_type === 'PASSPORT_ISSUED'));
  await stop(); await start();
  platformStatus = await request('/api/platform/status');
  assert.equal(platformStatus.intake.telemetry_events, 1, 'telemetry must survive a process restart');
  identityTrace = await request(agentPath + '/identity-trace');
  assert.ok(identityTrace.some(item => item.lane === 'runtime'), 'joined runtime evidence must survive a process restart');
  const html = await fetch(url); assert.equal(html.status, 200); assert.match(await html.text(), /<div id="root">/);
  const malicious = await fetch(url + '/api/discover', { method: 'POST', headers: { Origin: 'https://untrusted.example', 'Content-Type': 'application/json' }, body: '{}' });
  assert.equal(malicious.status, 403, 'cross-origin browser mutation must be blocked');
  await writeFile(join(data, 'final-state.json'), JSON.stringify(state, null, 2));
  t.diagnostic(`Persisted evidence retained in ${data}`);
});
