import { useState } from 'react';
import { ArrowRight, ChevronRight, Download, Eye, Fingerprint, Info, ShieldAlert, ShieldCheck } from 'lucide-react';
import { BUYER_GATES, type Destination, type Posture } from './model';
import './security-posture.css';
import { PrivateField, PrivateText, PrivateBlock, usePrivacy, redactExport } from '../privacy/Privacy';

const controls=[
  ['Human → agent authority','ByoSync-scoped','Owner binding, signed Passport, active mandate and execution checks.','Does not prove an external process is using that identity.'],
  ['Stop or restrict work','ByoSync-scoped','Suspend/revoke governed authority; cancel a managed room run.','Does not kill arbitrary Claude, Codex, browser or cloud sessions.'],
  ['Human approval','ByoSync-scoped','Exact-action review; named-user independent review for room runs and memory.','Local-operator mode is not independent human identity assurance.'],
  ['Company memory','ByoSync-scoped','Published, reviewed room memory is eligible for governed context.','Human review is not automated PII detection or proof against poisoning.'],
  ['External AI discovery','Observe only','Installed tools, collectors and configured-source observations.','Installation ≠ activity. Shadow ≠ malicious. No signal ≠ safe.'],
  ['External data loss / prompt attacks','Not verified','No independently validated enterprise protection feed in this UI.','Do not claim universal DLP, injection prevention or complete model visibility.'],
];
export function SecurityPosture({data,open}:{data:Posture;open:(target:Destination)=>void}) {
  const {hideAll}=usePrivacy();
  const [filter,setFilter]=useState('All');const [selected,setSelected]=useState<string|null>(null);
  const sorted=[...data.concerns].sort((a,b)=>['High','Attention','Unknown'].indexOf(a.severity)-['High','Attention','Unknown'].indexOf(b.severity));
  const items=sorted.filter(c=>filter==='All'||c.severity===filter);const current=items.find(c=>c.id===selected)||items[0];
  const synthetic=data.mode==='Synthetic scenario';
  const exportBrief=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({classification:data.mode,generated_at:data.evaluated,scope:data.scope,posture:synthetic?redactExport(data):data,buyer_gates:BUYER_GATES,notice:'Decision-support assessment, not certification, an independent audit or evidence of complete coverage.'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`ByoSync-${synthetic?'SYNTHETIC':'workspace'}-security-brief.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <section className="security-posture" aria-label="CISO security posture">
    <header className="sp-heading"><div><span className="sp-eyebrow">SECURITY POSTURE / CISO DECISION VIEW</span><h1>Know the exposure. Know the limits. Decide.</h1><p>{data.scope}</p></div><button onClick={exportBrief}><Download size={16}/>{synthetic?'Export redacted brief':'Export security brief'}</button></header>
    <div className="sp-verdict"><ShieldAlert/><div><strong>Controlled pilot candidate · enterprise rollout not established</strong><p>{synthetic?'This view uses fictional scenario records. It does not improve the actual deployment’s security assurance.':'This view uses workspace records. A functioning workflow is not evidence that the whole enterprise is protected.'}</p></div><span className="sp-tag">{data.mode}</span></div>
    <div className="sp-metrics">
      <article><Eye/><small>What can we see?</small><strong>{data.observed} {data.observedLabel || 'observations'}</strong><span>Fleet coverage: unknown</span></article>
      <article><Fingerprint/><small>Who is accountable?</small><strong>{data.owned} / {data.registered} owned</strong><span>{data.authority} with {synthetic?'scenario':'status/date-valid'} authority</span></article>
      <article><ShieldAlert/><small>What needs a person?</small><strong>{data.waiting} decisions</strong><span>{data.proposed} memory proposals awaiting review</span></article>
      <article><ShieldCheck/><small>Can we trust the record?</small><strong>{data.integrity}</strong><span>{synthetic?'No cryptographic attestation':'Local verification ≠ independent attestation'}</span></article>
    </div>
    <div className="sp-investigation">
      <section className="sp-panel"><header><h2>Investigate before you authorize</h2><span>{items.length} concerns</span></header><div className="sp-filters" aria-label="Concern priority">{['All','High','Attention','Unknown'].map(v=><button key={v} aria-pressed={v===filter} onClick={()=>{hideAll();setFilter(v);setSelected(null);}}>{v}</button>)}</div><div className="sp-concerns">{items.map(c=><button key={c.id} className={current?.id===c.id?'selected':''} aria-pressed={current?.id===c.id} onClick={()=>{hideAll();setSelected(c.id);}}><span className={`sp-priority ${c.severity.toLowerCase()}`}>{c.severity}</span><span><strong>{synthetic?<PrivateText value={c.title}/>:c.title}</strong><small>{synthetic?<PrivateText value={c.owner}/>:c.owner}</small></span><ChevronRight size={17}/></button>)}{!items.length&&<p className="sp-empty">No concerns in this category. Unknown or missing evidence is not a clean bill of health.</p>}</div></section>
      <section className="sp-panel sp-detail" aria-live="polite"><header><h2>{current?'Decision context':'Nothing selected'}</h2><span>Evidence before action</span></header>{current?<><span className={`sp-priority ${current.severity.toLowerCase()}`}>{current.severity}</span><h3>{synthetic?<PrivateField value={current.title} label="Concern title"/>:current.title}</h3><dl><dt>Why it matters</dt><dd>{synthetic?<PrivateBlock label="Concern context">{current.impact}</PrivateBlock>:current.impact}</dd><dt>Responsible person / function</dt><dd>{synthetic?<PrivateField value={current.owner} label="Concern owner"/>:current.owner}</dd><dt>Evidence available</dt><dd>{synthetic?<PrivateBlock label="Concern evidence">{current.evidence}</PrivateBlock>:current.evidence}</dd><dt>Control boundary</dt><dd>{current.boundary}</dd></dl><button className="sp-primary" onClick={()=>open(current.target)}>{current.action}<ArrowRight size={16}/></button></>:<p className="sp-empty">Select a concern to see scope, ownership and the next action.</p>}</section>
    </div>
    <section className="sp-panel"><header><div><h2>What can this product actually stop?</h2><p>{synthetic?'Implementation boundaries below describe the product, not protection delivered by this simulation.':'Controls apply at the integration boundary, not everywhere an AI product is installed.'}</p></div></header><div className="sp-table"><table><thead><tr><th>Security question</th><th>Control level</th><th>Available capability</th><th>Important limit</th></tr></thead><tbody>{controls.map(([name,level,available,limit])=><tr key={name}><th scope="row">{name}</th><td><span className={`sp-tag ${level==='Not verified'?'unknown':''}`}>{level}</span></td><td>{available}</td><td>{limit}</td></tr>)}</tbody></table></div></section>
    <div className="sp-bottom"><section className="sp-panel"><header><h2>Blind spots & source health</h2><span>No silent green states</span></header>{data.sources.map((source,i)=><div className="sp-source" key={`${source.name}-${i}`}><div><strong>{source.name}</strong><span className="sp-tag">{source.status}</span></div><p>{source.detail}</p></div>)}<p className="sp-note"><Info size={16}/>Freshness review threshold: 24 hours. “Connected” describes configuration, not fleet coverage or current detection success.</p></section><section className="sp-panel"><header><h2>Before a production purchase</h2><span>6 acceptance gates</span></header>{BUYER_GATES.map(g=><details className="sp-gate" key={g.name}><summary><strong>{g.name}</strong><span className="sp-tag">{g.status}</span></summary><p>{g.current}</p><p><b>Ask for proof:</b> {g.proof}</p></details>)}<p className="sp-note">These are code-review findings and outstanding acceptance criteria—not compliance certification. No aggregate “safe” score hides the gaps.</p></section></div>
    <footer className="sp-footnote">Evaluated {new Date(data.evaluated).toLocaleString()} · {data.memory} published memory records in visible scope · Export preserves this assessment and its limitations.</footer>
  </section>;
}

export function SecurityEntry({onOpen}:{onOpen:()=>void}) {return <button className="sp-entry" onClick={onOpen}><ShieldAlert/><span><strong>What would stop a production purchase?</strong><small>Coverage gaps, control boundaries, human decisions and evidence confidence.</small></span><span>Security posture <ArrowRight size={16}/></span></button>;}
