import { contextBridge, ipcRenderer } from 'electron';
import type { EmployeeWorkspaceApi } from '../../../packages/contracts/src/employeeWorkspace';

const employeeWorkspaceApi: EmployeeWorkspaceApi = {
  setupStatus: () => ipcRenderer.invoke('employee-workspace:setup-status'),
  setupIdentity: () => ipcRenderer.invoke('employee-workspace:setup-identity'),
  setupEnroll: request => ipcRenderer.invoke('employee-workspace:setup-enroll', request),
  setupVerify: request => ipcRenderer.invoke('employee-workspace:setup-verify', request),
  setupCommit: request => ipcRenderer.invoke('employee-workspace:setup-commit', request),
  begin: humanId => ipcRenderer.invoke('employee-workspace:begin', humanId),
  identity: () => ipcRenderer.invoke('employee-workspace:identity'),
  verify: request => ipcRenderer.invoke('employee-workspace:verify', request),
  login: async proofId => {
    const result = await ipcRenderer.invoke('employee-workspace:login', proofId);
    window.dispatchEvent(new Event('h2a:employee-session-changed'));
    return result;
  },
  hasSession: () => ipcRenderer.invoke('employee-workspace:has-session'),
  snapshot: () => ipcRenderer.invoke('employee-workspace:snapshot'),
  lookupMember: employeeId => ipcRenderer.invoke('employee-workspace:lookup-member', employeeId),
  challenge: purpose => ipcRenderer.invoke('employee-workspace:challenge', purpose),
  mutate: request => ipcRenderer.invoke('employee-workspace:mutate', request),
  renewAdministrator: proofId => ipcRenderer.invoke('employee-workspace:renew-administrator', proofId),
  logout: async () => {
    await ipcRenderer.invoke('employee-workspace:logout');
    window.dispatchEvent(new Event('h2a:employee-session-changed'));
  }
};
contextBridge.exposeInMainWorld('h2aEmployee', employeeWorkspaceApi);
import type {
  BiometricEnrollmentRequest,
  BiometricEnrollmentLifecycleRequest,
  BiometricVerificationRequest,
  BootstrapOrganizationRequest,
  CreateAuthorityRoleRequest,
  JoinMembershipRequest,
  MembershipLifecycleRequest,
  IssueAuthorityCredentialRequest,
  RecoverAdministratorCredentialRequest,
  AuthorityCredentialLifecycleRequest,
  AuthorityApprovalState,
  ConsumeApprovalResumeRequest,
  CreateApprovalPolicyRequest,
  RequestAuthorityEscalation,
  SubmitApprovalDecisionRequest,
  WithdrawApprovalRequest,
  EvaluateHumanAuthorityRequest,
  OrganizationAuthorityState,
  AgentIdentityState,
  AgentPassportV2MigrationResult,
  AttestAgentRuntimeRequest,
  AuthorizeActionRequest,
  CollaborationState,
  ConnectorImportRequest,
  ConnectorProtocolState,
  ContextBrokerState,
  ContextGrantLifecycleRequest,
  CreateContextArtifactRequest,
  IssueContextGrantRequest,
  AcceptFederationInvitationRequest,
  ActivateFederationAcceptanceRequest,
  ApproveFederationRegistrationRequest,
  ConfigureFederationNodeRequest,
  CreateFederationInvitationRequest,
  FederationState,
  FederationOperatorState,
  FederationPairingState,
  RefreshNodeDiscoveryRequest,
  CreateFederationPairingRequest,
  AcceptFederationPairingRequest,
  ConfirmFederationPairingRequest,
  CancelFederationPairingRequest,
  StartFederationListenerRequest,
  StopFederationListenerRequest,
  SendFederationTaskRequest,
  SendFederationAcknowledgementRequest,
  SendFederationOperatorHeartbeatRequest,
  ProveFederationReplayRequest,
  ProveFederationRevocationRequest,
  EnterpriseOverviewState,
  FinalAcceptanceExportReceipt,
  FinalAcceptanceState,
  FinalAcceptanceVerificationReceipt,
  VerifyFinalAcceptancePackageRequest,
  DemonstrationConductor,
  DemonstrationConductorCommand,
  Phase44SessionReceipt,
  SecurityValidationState,
  RunSecurityAttackRequest,
  RunContainmentControlRequest,
  RevokeFederationPeerRequest,
  FrameworkConnectorState,
  FrameworkProbeRequest,
  ExecuteFrameworkRequest,
  RealCollaborationState,
  PrepareRealCollaborationRequest,
  ReplaceRealCollaborationAuthorityRequest,
  RunRealCollaborationLaneRequest,
  CancelRealCollaborationLaneRequest,
  LeastContextState,
  PrepareLeastContextRequest,
  RenewLeastContextGrantRequest,
  RunLeastContextLaneRequest,
  ProveLeastContextRevocationRequest,
  ConfigureHumanEscalationRequest,
  HumanEscalationState,
  StartHumanEscalationRequest,
  StartHumanEscalationRejectionRequest,
  CancelDeliveryRequest,
  CancelLiveRunRequest,
  LiveRuntimeProbeRequest,
  LiveRuntimeState,
  StartLiveRunRequest,
  AttachTerminalRequest,
  RuntimeAttachmentState,
  StartTerminalSessionRequest,
  TerminalAttachmentLease,
  TerminalCancelRequest,
  TerminalInputRequest,
  TerminalLeaseRequest,
  TerminalReplayRequest,
  TerminalReplayResponse,
  TerminalResizeRequest,
  CreateAssignmentRequest,
  CreateAgentRequest,
  CreateMandateRequest,
  DelegateMandateRequest,
  EvidenceExplorerState,
  EvidenceExportReceipt,
  EvidenceQuery,
  EnrollHumanV2Request,
  ExportEvidenceBundleRequest,
  H2ADesktopApi,
  ControlPlaneAttachRequest,
  ControlPlaneAttachResponse,
  ControlPlaneCommandRequest,
  ControlPlaneEventEnvelope,
  ControlPlaneLeaseRequest,
  ControlPlaneReplayRequest,
  ControlPlaneReplayResponse,
  ControlPlaneSnapshot,
  HumanProofFailureRequest,
  HumanProofState,
  HumanIdentityV2State,
  HumanIdentityV2MigrationRequest,
  HumanIdentityV2MigrationResult,
  MandateLifecycleRequest,
  MandateState,
  MigrateAgentPassportsV1Request,
  PassportLifecycleRequest,
  RecordAssignmentResponseRequest,
  ResumeScenarioRequest,
  RuntimeLifecycleRequest,
  ResolveApprovalRequest,
  SendCollaborationMessageRequest,
  StartScenarioRequest,
  ScenarioState,
  SystemStatus,
  UpdateAssignmentRequest,
  VerifyHumanV2Request,
  WorkplaceSnapshot
} from '@h2a/contracts';
import type { CreateProjectAssignmentRequest, CreateProjectGoalRequest, FetchResearchSourceRequest, IntegrateProjectRequest, ProjectDeliveryState, RegisterProjectRequest, RunProjectValidationRequest } from '@h2a/contracts';
import type { CancelProjectRunRequest, RequestProjectIntegrationApproval, RunProjectAssignmentRequest } from '@h2a/contracts';
import type { ApproveWorkGraphRequest, ComposeCollaborativeGoalRequest, EditWorkGraphRequest, GoalWorkGraphState, ProposeWorkGraphRequest, ReassignWorkGraphNodeRequest, RenewWorkGraphNodeRequest, RunWorkGraphRequest, WorkGraphNodeCommandRequest } from '@h2a/contracts';
import type { CeremonyState, CreateCeremonySessionRequest, RunCeremonyStepRequest } from '@h2a/contracts';
import type { GuidedBootstrapState, PrepareGuidedBootstrapRequest, RunGuidedBootstrapStepRequest } from '@h2a/contracts';

const api: H2ADesktopApi = {
  attachControlPlane: (request: ControlPlaneAttachRequest) => ipcRenderer.invoke('control-plane:attach', request) as Promise<ControlPlaneAttachResponse>,
  detachControlPlane: (request: ControlPlaneLeaseRequest) => ipcRenderer.invoke('control-plane:detach', request) as Promise<void>,
  getControlPlaneSnapshot: (request: ControlPlaneLeaseRequest) => ipcRenderer.invoke('control-plane:get-snapshot', request) as Promise<ControlPlaneSnapshot>,
  getControlPlaneEvents: (request: ControlPlaneReplayRequest) => ipcRenderer.invoke('control-plane:get-events', request) as Promise<ControlPlaneReplayResponse>,
  executeOfficeCommand: (request: ControlPlaneCommandRequest) => ipcRenderer.invoke('control-plane:execute', request) as Promise<ControlPlaneSnapshot>,
  subscribeControlPlaneEvents: (listener: (event: ControlPlaneEventEnvelope) => void) => {
    const handler = (_event: Electron.IpcRendererEvent, envelope: ControlPlaneEventEnvelope): void => listener(envelope);
    ipcRenderer.on('control-plane:event', handler);
    return () => ipcRenderer.removeListener('control-plane:event', handler);
  },
  getSecurityValidationState: () => ipcRenderer.invoke('security-validation:get-state') as Promise<SecurityValidationState>,
  runSecurityAttack: (request: RunSecurityAttackRequest) => ipcRenderer.invoke('security-validation:run-attack', request) as Promise<SecurityValidationState>,
  runContainmentControl: (request: RunContainmentControlRequest) => ipcRenderer.invoke('security-validation:run-containment', request) as Promise<SecurityValidationState>,
  getGuidedBootstrapState: () => ipcRenderer.invoke('guided-bootstrap:get-state') as Promise<GuidedBootstrapState>,
  prepareGuidedBootstrap: (request: PrepareGuidedBootstrapRequest) => ipcRenderer.invoke('guided-bootstrap:prepare', request) as Promise<GuidedBootstrapState>,
  runGuidedBootstrapStep: (request: RunGuidedBootstrapStepRequest) => ipcRenderer.invoke('guided-bootstrap:run-step', request) as Promise<GuidedBootstrapState>,
  getCeremonyState: () => ipcRenderer.invoke('ceremony:get-state') as Promise<CeremonyState>,
  createCeremonySession: (request: CreateCeremonySessionRequest) => ipcRenderer.invoke('ceremony:create-session', request) as Promise<CeremonyState>,
  runCeremonyStep: (request: RunCeremonyStepRequest) => ipcRenderer.invoke('ceremony:run-step', request) as Promise<CeremonyState>,
  getSystemStatus: () => ipcRenderer.invoke('system:get-status') as Promise<SystemStatus>,
  writeClipboardText: (value: string) => ipcRenderer.invoke('system:write-clipboard', value) as Promise<void>,
  getWorkplaceSnapshot: () =>
    ipcRenderer.invoke('workplace:get-snapshot') as Promise<WorkplaceSnapshot>,
  getHumanProofState: () => ipcRenderer.invoke('human-proof:get-state') as Promise<HumanProofState>,
  enrollHuman: (request: BiometricEnrollmentRequest) =>
    ipcRenderer.invoke('human-proof:enroll', request) as Promise<HumanProofState>,
  verifyHuman: (request: BiometricVerificationRequest) =>
    ipcRenderer.invoke('human-proof:verify', request) as Promise<HumanProofState>,
  recordHumanProofFailure: (request: HumanProofFailureRequest) =>
    ipcRenderer.invoke('human-proof:record-failure', request) as Promise<HumanProofState>,
  getHumanIdentityV2State: (humanId?: string) =>
    ipcRenderer.invoke('human-identity-v2:get-state', humanId) as Promise<HumanIdentityV2State>,
  enrollHumanV2: (request: EnrollHumanV2Request) =>
    ipcRenderer.invoke('human-identity-v2:enroll', request) as Promise<HumanIdentityV2State>,
  verifyHumanV2: (request: VerifyHumanV2Request) =>
    ipcRenderer.invoke('human-identity-v2:verify', request) as Promise<HumanIdentityV2State>,
  updateBiometricEnrollmentV2: (request: BiometricEnrollmentLifecycleRequest) =>
    ipcRenderer.invoke('human-identity-v2:update-enrollment', request) as Promise<HumanIdentityV2State>,
  migrateHumanIdentityV1ToV2: (request: HumanIdentityV2MigrationRequest) =>
    ipcRenderer.invoke('human-identity-v2:migrate-v1', request) as Promise<HumanIdentityV2MigrationResult>,
  getOrganizationAuthorityState: () => ipcRenderer.invoke('organization:get-state') as Promise<OrganizationAuthorityState>,
  bootstrapOrganization: (request: BootstrapOrganizationRequest) => ipcRenderer.invoke('organization:bootstrap', request) as Promise<OrganizationAuthorityState>,
  createAuthorityRole: (request: CreateAuthorityRoleRequest) => ipcRenderer.invoke('organization:create-role', request) as Promise<OrganizationAuthorityState>,
  joinOrganizationMembership: (request: JoinMembershipRequest) => ipcRenderer.invoke('organization:join-membership', request) as Promise<OrganizationAuthorityState>,
  updateOrganizationMembership: (request: MembershipLifecycleRequest) => ipcRenderer.invoke('organization:update-membership', request) as Promise<OrganizationAuthorityState>,
  issueHumanAuthorityCredential: (request: IssueAuthorityCredentialRequest) => ipcRenderer.invoke('organization:issue-credential', request) as Promise<OrganizationAuthorityState>,
  recoverAdministratorCredential: (request: RecoverAdministratorCredentialRequest) => ipcRenderer.invoke('organization:recover-administrator-credential', request) as Promise<OrganizationAuthorityState>,
  updateHumanAuthorityCredential: (request: AuthorityCredentialLifecycleRequest) => ipcRenderer.invoke('organization:update-credential', request) as Promise<OrganizationAuthorityState>,
  evaluateHumanAuthority: (request: EvaluateHumanAuthorityRequest) => ipcRenderer.invoke('organization:evaluate-authority', request) as Promise<OrganizationAuthorityState>,
  getAuthorityApprovalState: () => ipcRenderer.invoke('authority-approvals:get-state') as Promise<AuthorityApprovalState>,
  createApprovalPolicy: (request: CreateApprovalPolicyRequest) => ipcRenderer.invoke('authority-approvals:create-policy', request) as Promise<AuthorityApprovalState>,
  requestAuthorityEscalation: (request: RequestAuthorityEscalation) => ipcRenderer.invoke('authority-approvals:request', request) as Promise<AuthorityApprovalState>,
  submitApprovalDecision: (request: SubmitApprovalDecisionRequest) => ipcRenderer.invoke('authority-approvals:decide', request) as Promise<AuthorityApprovalState>,
  consumeApprovalResume: (request: ConsumeApprovalResumeRequest) => ipcRenderer.invoke('authority-approvals:resume', request) as Promise<AuthorityApprovalState>,
  withdrawApprovalRequest: (request: WithdrawApprovalRequest) => ipcRenderer.invoke('authority-approvals:withdraw', request) as Promise<AuthorityApprovalState>,
  getContextBrokerState: () => ipcRenderer.invoke('context-broker:get-state') as Promise<ContextBrokerState>,
  createContextArtifact: (request: CreateContextArtifactRequest) => ipcRenderer.invoke('context-broker:create-artifact', request) as Promise<ContextBrokerState>,
  issueContextGrant: (request: IssueContextGrantRequest) => ipcRenderer.invoke('context-broker:issue-grant', request) as Promise<ContextBrokerState>,
  updateContextGrant: (request: ContextGrantLifecycleRequest) => ipcRenderer.invoke('context-broker:update-grant', request) as Promise<ContextBrokerState>,
  getFederationState: () => ipcRenderer.invoke('federation:get-state') as Promise<FederationState>,
  getFederationPairingState: (request?: RefreshNodeDiscoveryRequest) => ipcRenderer.invoke('federation-pairing:get-state', request ?? {}) as Promise<FederationPairingState>,
  createFederationPairing: (request: CreateFederationPairingRequest) => ipcRenderer.invoke('federation-pairing:create', request) as Promise<FederationPairingState>,
  acceptFederationPairing: (request: AcceptFederationPairingRequest) => ipcRenderer.invoke('federation-pairing:accept', request) as Promise<FederationPairingState>,
  confirmFederationPairing: (request: ConfirmFederationPairingRequest) => ipcRenderer.invoke('federation-pairing:confirm', request) as Promise<FederationPairingState>,
  cancelFederationPairing: (request: CancelFederationPairingRequest) => ipcRenderer.invoke('federation-pairing:cancel', request) as Promise<FederationPairingState>,
  getEnterpriseOverview: () => ipcRenderer.invoke('enterprise:get-overview') as Promise<EnterpriseOverviewState>,
  getFinalAcceptanceState: () => ipcRenderer.invoke('final-acceptance:get-state') as Promise<FinalAcceptanceState>,
  exportFinalAcceptancePackage: () => ipcRenderer.invoke('final-acceptance:export-package') as Promise<FinalAcceptanceExportReceipt>,
  verifyFinalAcceptancePackage: (request: VerifyFinalAcceptancePackageRequest) => ipcRenderer.invoke('final-acceptance:verify-package', request) as Promise<FinalAcceptanceVerificationReceipt>,
  preparePhase44Session: () => ipcRenderer.invoke('final-acceptance:prepare-phase44') as Promise<Phase44SessionReceipt>,
  enableRequiredLiveness: () => ipcRenderer.invoke('final-acceptance:require-liveness') as Promise<SystemStatus>,
  getDemonstrationConductor: () => ipcRenderer.invoke('demonstration-conductor:get-state') as Promise<DemonstrationConductor | null>,
  executeDemonstrationConductor: (request: DemonstrationConductorCommand) => ipcRenderer.invoke('demonstration-conductor:execute', request) as Promise<DemonstrationConductor>,
  configureFederationNode: (request: ConfigureFederationNodeRequest) => ipcRenderer.invoke('federation:configure-node', request) as Promise<FederationState>,
  createFederationInvitation: (request: CreateFederationInvitationRequest) => ipcRenderer.invoke('federation:create-invitation', request) as Promise<FederationState>,
  acceptFederationInvitation: (request: AcceptFederationInvitationRequest) => ipcRenderer.invoke('federation:accept-invitation', request) as Promise<FederationState>,
  approveFederationRegistration: (request: ApproveFederationRegistrationRequest) => ipcRenderer.invoke('federation:approve-registration', request) as Promise<FederationState>,
  activateFederationAcceptance: (request: ActivateFederationAcceptanceRequest) => ipcRenderer.invoke('federation:activate-acceptance', request) as Promise<FederationState>,
  revokeFederationPeer: (request: RevokeFederationPeerRequest) => ipcRenderer.invoke('federation:revoke-peer', request) as Promise<FederationState>,
  getFederationOperatorState: () => ipcRenderer.invoke('federation-operator:get-state') as Promise<FederationOperatorState>,
  startFederationListener: (request: StartFederationListenerRequest) => ipcRenderer.invoke('federation-operator:start-listener', request) as Promise<FederationOperatorState>,
  stopFederationListener: (request: StopFederationListenerRequest) => ipcRenderer.invoke('federation-operator:stop-listener', request) as Promise<FederationOperatorState>,
  sendFederationTask: (request: SendFederationTaskRequest) => ipcRenderer.invoke('federation-operator:send-task', request) as Promise<FederationOperatorState>,
  sendFederationAcknowledgement: (request: SendFederationAcknowledgementRequest) => ipcRenderer.invoke('federation-operator:send-ack', request) as Promise<FederationOperatorState>,
  sendFederationHeartbeat: (request: SendFederationOperatorHeartbeatRequest) => ipcRenderer.invoke('federation-operator:send-heartbeat', request) as Promise<FederationOperatorState>,
  proveFederationReplay: (request: ProveFederationReplayRequest) => ipcRenderer.invoke('federation-operator:prove-replay', request) as Promise<FederationOperatorState>,
  proveFederationRevocation: (request: ProveFederationRevocationRequest) => ipcRenderer.invoke('federation-operator:prove-revocation', request) as Promise<FederationOperatorState>,
  getAgentIdentityState: () => ipcRenderer.invoke('agents:get-identity-state') as Promise<AgentIdentityState>,
  createAgent: (request: CreateAgentRequest) => ipcRenderer.invoke('agents:create', request) as Promise<AgentIdentityState>,
  updateAgentPassport: (request: PassportLifecycleRequest) => ipcRenderer.invoke('agents:update-passport', request) as Promise<AgentIdentityState>,
  updateAgentRuntime: (request: RuntimeLifecycleRequest) => ipcRenderer.invoke('agents:update-runtime', request) as Promise<AgentIdentityState>,
  attestAgentRuntime: (request: AttestAgentRuntimeRequest) => ipcRenderer.invoke('agents:attest-runtime', request) as Promise<AgentIdentityState>,
  migrateAgentPassportsV1ToV2: (request: MigrateAgentPassportsV1Request) => ipcRenderer.invoke('agents:migrate-v1', request) as Promise<AgentPassportV2MigrationResult>,
  getCollaborationState: () => ipcRenderer.invoke('collaboration:get-state') as Promise<CollaborationState>,
  createAssignment: (request: CreateAssignmentRequest) => ipcRenderer.invoke('collaboration:create-assignment', request) as Promise<CollaborationState>,
  updateAssignment: (request: UpdateAssignmentRequest) => ipcRenderer.invoke('collaboration:update-assignment', request) as Promise<CollaborationState>,
  recordAssignmentResponse: (request: RecordAssignmentResponseRequest) => ipcRenderer.invoke('collaboration:record-response', request) as Promise<CollaborationState>,
  sendCollaborationMessage: (request: SendCollaborationMessageRequest) => ipcRenderer.invoke('collaboration:send-message', request) as Promise<CollaborationState>,
  getConnectorProtocolState: () => ipcRenderer.invoke('connectors:get-state') as Promise<ConnectorProtocolState>,
  importConnector: (request: ConnectorImportRequest) => ipcRenderer.invoke('connectors:import', request) as Promise<ConnectorProtocolState>,
  cancelConnectorDelivery: (request: CancelDeliveryRequest) => ipcRenderer.invoke('connectors:cancel-delivery', request) as Promise<ConnectorProtocolState>,
  getFrameworkConnectorState: () => ipcRenderer.invoke('framework-connectors:get-state') as Promise<FrameworkConnectorState>,
  probeFrameworkConnectors: (request: FrameworkProbeRequest) => ipcRenderer.invoke('framework-connectors:probe', request) as Promise<FrameworkConnectorState>,
  executeFramework: (request: ExecuteFrameworkRequest) => ipcRenderer.invoke('framework-connectors:execute', request) as Promise<FrameworkConnectorState>,
  getRealCollaborationState: () => ipcRenderer.invoke('real-collaboration:get-state') as Promise<RealCollaborationState>,
  prepareRealCollaboration: (request: PrepareRealCollaborationRequest) => ipcRenderer.invoke('real-collaboration:prepare', request) as Promise<RealCollaborationState>,
  replaceRealCollaborationAuthority: (request: ReplaceRealCollaborationAuthorityRequest) => ipcRenderer.invoke('real-collaboration:replace-authority', request) as Promise<RealCollaborationState>,
  runRealCollaborationLane: (request: RunRealCollaborationLaneRequest) => ipcRenderer.invoke('real-collaboration:run-lane', request) as Promise<RealCollaborationState>,
  cancelRealCollaborationLane: (request: CancelRealCollaborationLaneRequest) => ipcRenderer.invoke('real-collaboration:cancel-lane', request) as Promise<RealCollaborationState>,
  getLeastContextState: () => ipcRenderer.invoke('least-context:get-state') as Promise<LeastContextState>,
  prepareLeastContext: (request: PrepareLeastContextRequest) => ipcRenderer.invoke('least-context:prepare', request) as Promise<LeastContextState>,
  renewLeastContextGrant: (request: RenewLeastContextGrantRequest) => ipcRenderer.invoke('least-context:renew-grant', request) as Promise<LeastContextState>,
  runLeastContextLane: (request: RunLeastContextLaneRequest) => ipcRenderer.invoke('least-context:run-lane', request) as Promise<LeastContextState>,
  proveLeastContextRevocation: (request: ProveLeastContextRevocationRequest) => ipcRenderer.invoke('least-context:prove-revocation', request) as Promise<LeastContextState>,
  getHumanEscalationState: () => ipcRenderer.invoke('human-escalation:get-state') as Promise<HumanEscalationState>,
  configureHumanEscalation: (request: ConfigureHumanEscalationRequest) => ipcRenderer.invoke('human-escalation:configure', request) as Promise<HumanEscalationState>,
  startHumanEscalation: (request: StartHumanEscalationRequest) => ipcRenderer.invoke('human-escalation:start', request) as Promise<HumanEscalationState>,
  startHumanEscalationRejection: (request: StartHumanEscalationRejectionRequest) => ipcRenderer.invoke('human-escalation:start-rejection', request) as Promise<HumanEscalationState>,
  getLiveRuntimeState: () => ipcRenderer.invoke('live-runtime:get-state') as Promise<LiveRuntimeState>,
  probeLiveProviders: (request: LiveRuntimeProbeRequest) => ipcRenderer.invoke('live-runtime:probe', request) as Promise<LiveRuntimeState>,
  startLiveRun: (request: StartLiveRunRequest) => ipcRenderer.invoke('live-runtime:start', request) as Promise<LiveRuntimeState>,
  cancelLiveRun: (request: CancelLiveRunRequest) => ipcRenderer.invoke('live-runtime:cancel', request) as Promise<LiveRuntimeState>,
  getRuntimeAttachmentState: () => ipcRenderer.invoke('runtime-attachment:get-state') as Promise<RuntimeAttachmentState>,
  startTerminalSession: (request: StartTerminalSessionRequest) => ipcRenderer.invoke('runtime-attachment:start', request) as Promise<RuntimeAttachmentState>,
  attachTerminal: (request: AttachTerminalRequest) => ipcRenderer.invoke('runtime-attachment:attach', request) as Promise<TerminalAttachmentLease>,
  detachTerminal: (request: TerminalLeaseRequest) => ipcRenderer.invoke('runtime-attachment:detach', request) as Promise<void>,
  getTerminalReplay: (request: TerminalReplayRequest) => ipcRenderer.invoke('runtime-attachment:replay', request) as Promise<TerminalReplayResponse>,
  writeTerminal: (request: TerminalInputRequest) => ipcRenderer.invoke('runtime-attachment:write', request) as Promise<void>,
  resizeTerminal: (request: TerminalResizeRequest) => ipcRenderer.invoke('runtime-attachment:resize', request) as Promise<void>,
  cancelTerminal: (request: TerminalCancelRequest) => ipcRenderer.invoke('runtime-attachment:cancel', request) as Promise<RuntimeAttachmentState>,
  getProjectDeliveryState: () => ipcRenderer.invoke('project-delivery:get-state') as Promise<ProjectDeliveryState>,
  registerProject: (request: RegisterProjectRequest) => ipcRenderer.invoke('project-delivery:register', request) as Promise<ProjectDeliveryState>,
  createProjectGoal: (request: CreateProjectGoalRequest) => ipcRenderer.invoke('project-delivery:create-goal', request) as Promise<ProjectDeliveryState>,
  createProjectAssignment: (request: CreateProjectAssignmentRequest) => ipcRenderer.invoke('project-delivery:create-assignment', request) as Promise<ProjectDeliveryState>,
  createProjectWorktree: (assignmentId: string) => ipcRenderer.invoke('project-delivery:create-worktree', assignmentId) as Promise<ProjectDeliveryState>,
  refreshProjectWorktree: (assignmentId: string) => ipcRenderer.invoke('project-delivery:refresh-worktree', assignmentId) as Promise<ProjectDeliveryState>,
  fetchProjectResearch: (request: FetchResearchSourceRequest) => ipcRenderer.invoke('project-delivery:fetch-research', request) as Promise<ProjectDeliveryState>,
  runProjectValidation: (request: RunProjectValidationRequest) => ipcRenderer.invoke('project-delivery:validate', request) as Promise<ProjectDeliveryState>,
  runProjectAssignment: (request: RunProjectAssignmentRequest) => ipcRenderer.invoke('project-delivery:run-assignment', request) as Promise<ProjectDeliveryState>,
  cancelProjectRun: (request: CancelProjectRunRequest) => ipcRenderer.invoke('project-delivery:cancel-run', request) as Promise<ProjectDeliveryState>,
  getProjectIntegrationEffectHash: (goalId: string, assignmentIds: string[]) => ipcRenderer.invoke('project-delivery:effect-hash', goalId, assignmentIds) as Promise<string>,
  requestProjectIntegrationApproval: (request: RequestProjectIntegrationApproval) => ipcRenderer.invoke('project-delivery:request-integration-approval', request) as Promise<AuthorityApprovalState>,
  integrateProject: (request: IntegrateProjectRequest) => ipcRenderer.invoke('project-delivery:integrate', request) as Promise<ProjectDeliveryState>,
  cleanupProjectWorktree: (assignmentId: string) => ipcRenderer.invoke('project-delivery:cleanup-worktree', assignmentId) as Promise<ProjectDeliveryState>,
  getGoalWorkGraphState: () => ipcRenderer.invoke('goal-work-graph:get-state') as Promise<GoalWorkGraphState>,
  composeCollaborativeGoal: (request: ComposeCollaborativeGoalRequest) => ipcRenderer.invoke('goal-work-graph:compose', request) as Promise<GoalWorkGraphState>,
  proposeWorkGraph: (request: ProposeWorkGraphRequest) => ipcRenderer.invoke('goal-work-graph:propose', request) as Promise<GoalWorkGraphState>,
  editWorkGraph: (request: EditWorkGraphRequest) => ipcRenderer.invoke('goal-work-graph:edit', request) as Promise<GoalWorkGraphState>,
  approveWorkGraph: (request: ApproveWorkGraphRequest) => ipcRenderer.invoke('goal-work-graph:approve', request) as Promise<GoalWorkGraphState>,
  runWorkGraph: (request: RunWorkGraphRequest) => ipcRenderer.invoke('goal-work-graph:run', request) as Promise<GoalWorkGraphState>,
  runWorkGraphNode: (request: WorkGraphNodeCommandRequest) => ipcRenderer.invoke('goal-work-graph:run-node', request) as Promise<GoalWorkGraphState>,
  renewWorkGraphNode: (request: RenewWorkGraphNodeRequest) => ipcRenderer.invoke('goal-work-graph:renew-node', request) as Promise<GoalWorkGraphState>,
  cancelWorkGraphNode: (request: WorkGraphNodeCommandRequest) => ipcRenderer.invoke('goal-work-graph:cancel-node', request) as Promise<GoalWorkGraphState>,
  revokeWorkGraphNode: (request: WorkGraphNodeCommandRequest) => ipcRenderer.invoke('goal-work-graph:revoke-node', request) as Promise<GoalWorkGraphState>,
  reassignWorkGraphNode: (request: ReassignWorkGraphNodeRequest) => ipcRenderer.invoke('goal-work-graph:reassign-node', request) as Promise<GoalWorkGraphState>,
  getMandateState: () => ipcRenderer.invoke('mandates:get-state') as Promise<MandateState>,
  createMandate: (request: CreateMandateRequest) => ipcRenderer.invoke('mandates:create', request) as Promise<MandateState>,
  delegateMandate: (request: DelegateMandateRequest) => ipcRenderer.invoke('mandates:delegate', request) as Promise<MandateState>,
  updateMandate: (request: MandateLifecycleRequest) => ipcRenderer.invoke('mandates:update', request) as Promise<MandateState>,
  authorizeAction: (request: AuthorizeActionRequest) => ipcRenderer.invoke('mandates:authorize', request) as Promise<MandateState>,
  resolveApproval: (request: ResolveApprovalRequest) => ipcRenderer.invoke('mandates:resolve-approval', request) as Promise<MandateState>,
  getScenarioState: () => ipcRenderer.invoke('scenarios:get-state') as Promise<ScenarioState>,
  startScenario: (request: StartScenarioRequest) => ipcRenderer.invoke('scenarios:start', request) as Promise<ScenarioState>,
  resumeScenario: (request: ResumeScenarioRequest) => ipcRenderer.invoke('scenarios:resume', request) as Promise<ScenarioState>,
  getEvidenceExplorerState: (query: EvidenceQuery) => ipcRenderer.invoke('evidence:get-explorer-state', query) as Promise<EvidenceExplorerState>,
  exportEvidenceBundle: (request: ExportEvidenceBundleRequest) => ipcRenderer.invoke('evidence:export-bundle', request) as Promise<EvidenceExportReceipt>
};

contextBridge.exposeInMainWorld('h2a', api);
