import { useState } from 'react';
import { Ban, Braces, EyeOff, FileKey2, Filter, LockKeyhole, Plus, ShieldCheck, X } from 'lucide-react';
import type { AgentIdentityState, CeremonyState, CollaborationState, ContextBrokerState, ContextClassification, ContextTransformation, OrganizationAuthorityState } from '@h2a/contracts';
import { StatusBadge } from '@h2a/ui';
import { LeastContextConsole } from './LeastContextConsole';

interface Props {
  state: ContextBrokerState;
  organization: OrganizationAuthorityState;
  identity: AgentIdentityState;
  collaboration: CollaborationState;
  ceremony: CeremonyState;
  onStateChange(state: ContextBrokerState): void;
  onHumanProofRequired(): void;
}

export function ContextBrokerView({ state, organization, identity, collaboration, ceremony, onStateChange, onHumanProofRequired }: Props): React.JSX.Element {
  const [tab, setTab] = useState<'grants' | 'disclosures' | 'artifacts' | 'messages'>('grants');
  const [showArtifact, setShowArtifact] = useState(false);
  const [showGrant, setShowGrant] = useState(false);
  const [message, setMessage] = useState('');
  const activeGrants = state.grants.filter((item) => item.status === 'active');
  const hasActiveArtifact = state.artifacts.some((item) => item.status === 'active');
  const issueGrantPrerequisite = 'Add an active protected artifact before issuing a Context Grant.';

  async function revoke(grantId: string): Promise<void> {
    const actor = currentActor(organization);
    if (!window.h2a || !actor) { onHumanProofRequired(); return; }
    try { onStateChange(await window.h2a.updateContextGrant({ actor, context_grant_id: grantId, action: 'revoke' })); setMessage('Context Grant revoked. Future disclosure now fails closed.'); }
    catch (error) { setMessage(errorMessage(error)); }
  }

  return <div className="context-page">
    <LeastContextConsole ceremony={ceremony} onProofRequired={onHumanProofRequired} onContextRefresh={() => { if (window.h2a) void window.h2a.getContextBrokerState().then(onStateChange); }} />
    <header className="context-heading"><div className="context-title"><span><LockKeyhole size={22} /></span><div><p className="section-kicker">LEAST-CONTEXT CONTROL PLANE</p><h2>Context Broker</h2><p>Classified artifacts become recipient-bound, purpose-limited disclosures.</p></div></div><div className="context-actions"><button className="secondary-button" type="button" onClick={() => setShowArtifact(true)}><Plus size={16} /> Add artifact</button><button className="primary-button" type="button" disabled={!hasActiveArtifact} title={hasActiveArtifact ? 'Issue a purpose-bound Context Grant.' : issueGrantPrerequisite} aria-label={hasActiveArtifact ? 'Issue grant' : `Issue grant unavailable. ${issueGrantPrerequisite}`} onClick={() => setShowGrant(true)}><FileKey2 size={16} /> Issue grant</button></div></header>
    <section className="context-metrics" aria-label="Context Broker metrics"><Metric label="Protected artifacts" value={state.artifacts.length} icon={LockKeyhole} /><Metric label="Active grants" value={activeGrants.length} icon={FileKey2} /><Metric label="Disclosures" value={state.disclosures.length} icon={Filter} /><Metric label="Withheld fields" value={state.disclosures.reduce((sum, item) => sum + item.withheld_fields.length, 0)} icon={EyeOff} /></section>
    <div className="context-tabs" role="tablist" aria-label="Context Broker views">{(['grants', 'disclosures', 'artifacts', 'messages'] as const).map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>
    <section className="context-workbench">
      {tab === 'grants' && <GrantTable state={state} onRevoke={(id) => void revoke(id)} />}
      {tab === 'disclosures' && <DisclosureTable state={state} />}
      {tab === 'artifacts' && <ArtifactTable state={state} />}
      {tab === 'messages' && <MessageTable state={state} />}
    </section>
    {message && <div className="approval-toast" role="status">{message}</div>}
    {showArtifact && <ArtifactDialog organization={organization} onProofRequired={onHumanProofRequired} onClose={() => setShowArtifact(false)} onSubmit={(next) => { onStateChange(next); setShowArtifact(false); setMessage('Artifact values sealed; only classifications and hashes are public.'); }} />}
    {showGrant && <GrantDialog state={state} organization={organization} identity={identity} collaboration={collaboration} onProofRequired={onHumanProofRequired} onClose={() => setShowGrant(false)} onSubmit={(next) => { onStateChange(next); setShowGrant(false); setMessage('Purpose-bound Context Grant issued.'); }} />}
  </div>;
}

function GrantTable({ state, onRevoke }: { state: ContextBrokerState; onRevoke(id: string): void }): React.JSX.Element {
  if (!state.grants.length) return <Empty icon={FileKey2} title="No Context Grants" detail="Issue a recipient-bound grant from a protected artifact." />;
  return <div className="context-table-scroll"><table className="context-table"><thead><tr><th>Grant</th><th>Recipient</th><th>Purpose</th><th>Fields</th><th>Usage</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{[...state.grants].reverse().map((item) => <tr key={item.grant.context_grant_id}><td><strong>{item.grant.context_grant_id}</strong><code>{item.grant.task_id}</code></td><td><strong>{item.grant.recipient_agent_id}</strong><code>{item.grant.recipient_passport_id}</code></td><td>{item.grant.purpose}</td><td><div className="context-tags">{item.field_rules.map((rule) => <span key={rule.field}>{rule.field}<b>{rule.transformation}</b></span>)}</div></td><td>{item.use_count}/{item.maximum_uses}<small>{item.grant.token_budget} tokens</small></td><td><StatusBadge label={item.status} tone={item.status === 'active' ? 'verified' : item.status === 'revoked' ? 'danger' : 'neutral'} /></td><td>{item.status === 'active' && <button data-control-id="context.grant.revoke" className="icon-button" type="button" title="Revoke Context Grant" aria-label="Revoke Context Grant" onClick={() => onRevoke(item.grant.context_grant_id)}><Ban size={16} /></button>}</td></tr>)}</tbody></table></div>;
}
function DisclosureTable({ state }: { state: ContextBrokerState }): React.JSX.Element {
  if (!state.disclosures.length) return <Empty icon={Filter} title="No disclosures" detail="Authorized and denied field releases appear after an agent requests context." />;
  return <div className="context-table-scroll"><table className="context-table"><thead><tr><th>Disclosure</th><th>Recipient</th><th>Granted</th><th>Withheld</th><th>Projection</th><th>Decision</th></tr></thead><tbody>{state.disclosures.map((item) => <tr key={item.disclosure_id}><td><strong>{item.disclosure_id}</strong><code>{item.task_id}</code><small>{formatTime(item.disclosed_at)}</small></td><td><strong>{item.recipient_agent_id}</strong><code>{item.recipient_passport_id}</code></td><td><div className="context-tags good">{item.granted_fields.map((field) => <span key={field}>{field}<b>{item.transformation_by_field[field]}</b></span>)}</div></td><td><div className="context-tags danger">{item.withheld_fields.map((field) => <span key={field}>{field}</span>)}</div></td><td><code>{shortHash(item.projection_hash)}</code><small>values excluded</small></td><td><StatusBadge label={item.reason_code} tone={item.status === 'authorized' ? 'verified' : 'danger'} /></td></tr>)}</tbody></table></div>;
}
function ArtifactTable({ state }: { state: ContextBrokerState }): React.JSX.Element {
  if (!state.artifacts.length) return <Empty icon={LockKeyhole} title="No protected artifacts" detail="Create an artifact to classify and seal local context values." />;
  return <div className="artifact-grid">{state.artifacts.map((item) => <article key={item.artifact_id}><header><span><Braces size={17} /></span><div><strong>{item.name}</strong><code>{item.artifact_id}</code></div><StatusBadge label={item.status} tone={item.status === 'active' ? 'verified' : 'danger'} /></header><dl><div><dt>Source</dt><dd>{item.source_resource}</dd></div><div><dt>Owner</dt><dd>{item.owner_human_id}</dd></div><div><dt>Storage</dt><dd>OS-protected ciphertext</dd></div></dl><div className="artifact-fields">{item.fields.map((field) => <div key={field.field}><span>{field.field}</span><Classification value={field.classification} /><code>{shortHash(field.value_hash)}</code></div>)}</div></article>)}</div>;
}
function MessageTable({ state }: { state: ContextBrokerState }): React.JSX.Element {
  if (!state.messages.length) return <Empty icon={ShieldCheck} title="No governed handoffs" detail="Signed agent messages appear after connector tasks exchange artifact references." />;
  return <div className="context-table-scroll"><table className="context-table"><thead><tr><th>Message</th><th>Route</th><th>Authority</th><th>Content reference</th><th>Status</th></tr></thead><tbody>{state.messages.map((item) => <tr key={item.message_id}><td><strong>{item.speech_act}</strong><code>{item.message_id}</code></td><td><code>{item.sender_passport_id}</code><small>to {item.recipient_passport_id}</small></td><td><code>{item.mandate_id}</code><small>{item.context_grant_id}</small></td><td><code>{item.content_ref}</code><small>{shortHash(item.content_hash)}</small></td><td><StatusBadge label={item.status} tone={item.status === 'delivered' ? 'verified' : item.status === 'rejected' ? 'danger' : 'approval'} /></td></tr>)}</tbody></table></div>;
}

interface FieldDraft { id: string; field: string; classification: ContextClassification; value: string; }
function ArtifactDialog({ organization, onProofRequired, onClose, onSubmit }: { organization: OrganizationAuthorityState; onProofRequired(): void; onClose(): void; onSubmit(state: ContextBrokerState): void }): React.JSX.Element {
  const [name, setName] = useState('Supplier risk record'); const [source, setSource] = useState('supplier-records');
  const [fields, setFields] = useState<FieldDraft[]>([{ id: crypto.randomUUID(), field: 'supplier_name', classification: 'internal', value: '' }]); const [error, setError] = useState('');
  async function submit(): Promise<void> { const actor = currentActor(organization); if (!actor || !window.h2a) { onProofRequired(); return; } try { onSubmit(await window.h2a.createContextArtifact({ actor, organization_id: organization.organizations[0].organization_id, name, source_resource: source, fields: fields.map(({ field, classification, value }) => ({ field, classification, value })) })); } catch (reason) { setError(errorMessage(reason)); } }
  return <Dialog title="Add protected artifact" detail="Values are sealed by the trusted Electron process; public state keeps metadata and hashes only." onClose={onClose} footer={<><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button data-control-id="context.artifact.create" className="primary-button" type="button" disabled={!name || !source || fields.some((item) => !item.field || !item.value)} onClick={() => void submit()}><LockKeyhole size={16} /> Seal artifact</button></>}><div className="form-grid"><label className="field"><span>Name</span><input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="field"><span>Source resource</span><input value={source} onChange={(event) => setSource(event.target.value)} /></label></div><div className="field-builder"><div className="field-builder-head"><strong>Classified fields</strong><button className="secondary-button" type="button" onClick={() => setFields([...fields, { id: crypto.randomUUID(), field: '', classification: 'confidential', value: '' }])}><Plus size={14} /> Add field</button></div>{fields.map((item) => <div className="field-builder-row" key={item.id}><input aria-label="Field name" placeholder="field_name" value={item.field} onChange={(event) => setFields(fields.map((field) => field.id === item.id ? { ...field, field: event.target.value } : field))} /><select aria-label="Classification" value={item.classification} onChange={(event) => setFields(fields.map((field) => field.id === item.id ? { ...field, classification: event.target.value as ContextClassification } : field))}><option value="public">Public</option><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select><input aria-label="Field value" placeholder="Protected value" value={item.value} onChange={(event) => setFields(fields.map((field) => field.id === item.id ? { ...field, value: event.target.value } : field))} /><button className="icon-button" type="button" title="Remove field" disabled={fields.length === 1} onClick={() => setFields(fields.filter((field) => field.id !== item.id))}><X size={15} /></button></div>)}</div>{error && <p className="form-error">{error}</p>}</Dialog>;
}

function GrantDialog({ state, organization, identity, collaboration, onProofRequired, onClose, onSubmit }: { state: ContextBrokerState; organization: OrganizationAuthorityState; identity: AgentIdentityState; collaboration: CollaborationState; onProofRequired(): void; onClose(): void; onSubmit(state: ContextBrokerState): void }): React.JSX.Element {
  const assignments = collaboration.workplace.assignments.filter((item) => item.status !== 'complete'); const [assignmentId, setAssignmentId] = useState(assignments[0]?.id ?? ''); const [artifactId, setArtifactId] = useState(state.artifacts.find((item) => item.status === 'active')?.artifact_id ?? ''); const [purpose, setPurpose] = useState('review authorized context'); const [budget, setBudget] = useState(500); const [uses, setUses] = useState(10); const [rules, setRules] = useState<Record<string, ContextTransformation>>({}); const [error, setError] = useState('');
  const assignment = assignments.find((item) => item.id === assignmentId); const passport = identity.passportsV2?.find((item) => item.agent_id === assignment?.assigneeId && item.status === 'active'); const artifact = state.artifacts.find((item) => item.artifact_id === artifactId);
  async function submit(): Promise<void> { const actor = currentActor(organization); if (!actor || !window.h2a) { onProofRequired(); return; } if (!assignment || !passport || !artifact) return; try { onSubmit(await window.h2a.issueContextGrant({ actor, organization_id: artifact.organization_id, task_id: assignment.id, mandate_id: assignment.mandateId, recipient_agent_id: assignment.assigneeId, recipient_passport_id: passport.passport_id, purpose, field_rules: artifact.fields.filter((field) => rules[field.field]).map((field) => ({ artifact_id: artifact.artifact_id, field: field.field, maximum_classification: field.classification, transformation: rules[field.field] })), token_budget: budget, maximum_uses: uses, expires_at: new Date(Date.now() + 30 * 60_000).toISOString() })); } catch (reason) { setError(errorMessage(reason)); } }
  return <Dialog title="Issue Context Grant" detail="Bind selected fields and transformations to one task, agent, passport, mandate, and purpose." onClose={onClose} footer={<><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button data-control-id="context.grant.issue" className="primary-button" type="button" disabled={!assignment || !passport || !artifact || !Object.keys(rules).length || !purpose} onClick={() => void submit()}><FileKey2 size={16} /> Issue grant</button></>}><div className="form-grid"><label className="field"><span>Assignment</span><select value={assignmentId} onChange={(event) => setAssignmentId(event.target.value)}>{assignments.map((item) => <option value={item.id} key={item.id}>{item.title} · {item.assigneeId}</option>)}</select></label><label className="field"><span>Artifact</span><select value={artifactId} onChange={(event) => { setArtifactId(event.target.value); setRules({}); }}>{state.artifacts.filter((item) => item.status === 'active').map((item) => <option value={item.artifact_id} key={item.artifact_id}>{item.name}</option>)}</select></label></div><label className="field"><span>Purpose</span><input value={purpose} onChange={(event) => setPurpose(event.target.value)} /></label><div className="recipient-binding"><div><span>Agent</span><strong>{assignment?.assigneeId ?? 'Not selected'}</strong></div><div><span>Passport</span><strong>{passport?.passport_id ?? 'Active Passport V2 required'}</strong></div><div><span>Mandate</span><strong>{assignment?.mandateId ?? 'Not selected'}</strong></div></div><fieldset className="grant-field-rules"><legend>Field release rules</legend>{artifact?.fields.map((field) => <div key={field.field}><label><input type="checkbox" checked={Boolean(rules[field.field])} onChange={(event) => setRules((current) => { const next = { ...current }; if (event.target.checked) next[field.field] = field.classification === 'restricted' ? 'reference' : 'value'; else delete next[field.field]; return next; })} /><span><strong>{field.field}</strong><Classification value={field.classification} /></span></label><select aria-label={`${field.field} transformation`} disabled={!rules[field.field]} value={rules[field.field] ?? 'value'} onChange={(event) => setRules({ ...rules, [field.field]: event.target.value as ContextTransformation })}><option value="value">Release value</option><option value="mask">Mask</option><option value="summarize">Summarize</option><option value="reference">Reference only</option></select></div>)}</fieldset><div className="form-grid"><label className="field"><span>Token budget</span><input type="number" min={1} value={budget} onChange={(event) => setBudget(Number(event.target.value))} /></label><label className="field"><span>Maximum uses</span><input type="number" min={1} value={uses} onChange={(event) => setUses(Number(event.target.value))} /></label></div>{error && <p className="form-error">{error}</p>}</Dialog>;
}

function Dialog({ title, detail, onClose, footer, children }: { title: string; detail: string; onClose(): void; footer: React.ReactNode; children: React.ReactNode }): React.JSX.Element { return <div className="modal-scrim"><section className="authority-dialog context-dialog" role="dialog" aria-modal="true"><header><div><h2>{title}</h2><p>{detail}</p></div><button className="icon-button" type="button" title="Close" onClick={onClose}><X size={17} /></button></header><div className="authority-dialog-body">{children}</div><footer>{footer}</footer></section></div>; }
function Classification({ value }: { value: ContextClassification }): React.JSX.Element { return <span className={`classification classification-${value}`}>{value}</span>; }
function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof LockKeyhole }): React.JSX.Element { return <div><span><Icon size={16} />{label}</span><strong>{value}</strong></div>; }
function Empty({ icon: Icon, title, detail }: { icon: typeof LockKeyhole; title: string; detail: string }): React.JSX.Element { return <div className="context-empty"><Icon size={28} /><strong>{title}</strong><span>{detail}</span></div>; }
function currentActor(state: OrganizationAuthorityState) { const proof = state.assurance[0]; const credential = state.credentials.find((item) => item.membership_id === proof?.membership_id && item.status === 'active'); return proof && credential ? { membership_id: proof.membership_id, human_proof_id: proof.human_proof_id, authority_credential_id: credential.credential_id } : undefined; }
function shortHash(value: string): string { return `${value.slice(0, 18)}…${value.slice(-6)}`; }
function formatTime(value: string): string { return new Intl.DateTimeFormat(undefined, { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'Context operation failed.'; }
